Hacker0x01/react-datepicker

- .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details
> Switch to faster travis builds

- example.html
> Add min height to avoid issues with Firefox

- react-datepicker.js
- src/util/date.js
> Switched arguments to fix deprecation warning

- react-datepicker.css
- react-datepicker.js
- src/calendar.js
- src/stylesheets/datepicker.scss
> Add hover state for inactive day

- example.html
See http://cdn.rawgit.com/Hacker0x01/react-datepicker/livedemo/example.html
> Use online resources to support an online demo

- example.html
- react-datepicker.js
- src/calendar.js
- src/date_input.js
- src/datepicker.js
- src/util/date.js
- test/util/date_test.js
This PR adds the ability to initialize a datepicker with a null value. This also introduces placeholder text.
You can test this [live](http://cdn.rawgit.com/hahahana/react-datepicker/21464e529b72d17a2075ea55c26eb449c0d3d2fe/example.html).
----
This should close https://github.com/Hacker0x01/react-datepicker/issues/53
> Support for null date states

- example/bundle.js
- grunt/tasks/browserify.js
- gruntfile.js
- package.json
- react-datepicker.js
I was getting tired of the dependency troubles caused by all the separate requirements of this simple project, so I decided to try and see how hard it would be to replace grunt-browserify with our own task, turns out: not that hard.
> Replace grunt-browserify with own grunt task

- README.md
I'm assuming that this is the official module:
https://www.npmjs.com/package/react-datepicker
> add npm installation instruction

- src/calendar.jsx
- src/date_input.jsx
- src/datepicker.jsx
There might be a way to do this already without this pull request, but I couldn't figure it out. =(
I have a form with date fields and each date field is nullable. This means the value can either be a valid date (datepicker handles this great), or it can be empty, which means `null` right now.
This PR is one approach to supporting the ability to "clear" a date value if the input text is empty. 
I realize `null` might not be the best thing to emit to onChange. Open to any ideas like an empty string etc.
Hoping this PR can be a first step towards a good solution.
> First attempt at ability to clear date inputs.

- src/date_input.jsx
- src/datepicker.jsx
Added name attribute support for usage in forms. Default name can be added but not required (with this change if none is provided the behavior is the same as before).
> DateInput component name attribute support

- .scss-lint.yml
- README.md
- example/node-rendering.js
- package.json
- src/popover.jsx
Should merge #112 before
This fixes the server side rendering in node (#107)
> Fix ssr rendering

- src/datepicker.jsx
Issue: #124 
Makes `onChange` property optional and provides `getValue` method for retrieving the current value
> support uncontrolled datepicker

- .travis.yml
- grunt/tasks/jest.js
- gruntfile.js
- karma.conf.js
- package.json
- test/date_input_test.js
- test/index.js
- test/util/date_test.js
Decided it was time to replace Jest with Karma, as:
- Karma seems way more stable/better maintained
- Karma runs with mocha/sinon/chai which are way better maintained than the stuff jest comes with
- Karma runs in browsers, which is cool!
> Replace Jest with Karma

- index.html
- src/app.jsx
- src/reset.scss
- src/style.scss
- src/topbar.scss
Turns the old fashioned example page into a fancy example overview with code examples.
> Basics of improving example

- README.md
Seems like this was removed in https://github.com/Hacker0x01/react-datepicker/pull/144/files
> remove note about server rendering

- src/datepicker.jsx
- src/stylesheets/datepicker.scss
> Fix clear button

- src/calendar.jsx
> Remove required check for selected

- README.md
Tried to make the current documentation more clear and update stuff where needed. Anything we want to add?
> First pass on improving documentation

- package.json
- src/date_input.jsx
- src/popover.jsx
- test/date_input_test.js
I updated to React 0.14, all the tests pass.
> fix #198: Updated to react 0.14

- src/datepicker.jsx
> Prevent page nav when clicking clear button

- src/calendar.jsx
- src/datepicker.jsx
- src/day.jsx
- src/stylesheets/datepicker.scss
- src/util/date.js
- test/util/date_test.js
This patch is a fork of #79 with the suggested modifications and
merge conflicts resolved. The credit should go to the original
author. This is simply something I wanted and the original author
appears to have gone MIA.
> Allow for date range selection

- src/day.jsx
- test/day_test.js
> Read inRange from prop passed to Day

- README.md
Just updated some grammar for the readme to make it easier to comprehend.
> updated grammar and spelling for README

- README.md
- src/calendar.jsx
- src/datepicker.jsx
- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
- src/util/date.js
- src/year_dropdown.jsx
- test/util/date_test.js
- test/year_dropdown_test.js
This Pull Request would close issue/feature request #90.
I've written some tests that cover the new functionality. I'm fairly new to submitting pull requests for open source projects. So let me know if there's any improvements I can make or additional test coverage you'd like to see.
> Year dropdown implementation

- karma.conf.js
- package.json
Decided to get rid of Sauce labs since this doesn't work with external Pull Requests. Preferring running tests for everyone instead of just for us.
> Get rid of Sauce Labs

- docs/src/example_components.jsx
- docs/src/examples/tab_index.jsx
- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
> Add tabIndex for input fields

- src/stylesheets/datepicker.scss
> Fix positioning of the popover when the popover is shown on top

- docs/src/examples/date_range.jsx
Fixes #267 some more
This changes the `handleChange` method for the date range example to be a more plausible use case
> Make date range selection example more realistic

- docs/src/example_components.jsx
- docs/src/examples/year_dropdown.jsx
- src/calendar.jsx
- src/datepicker.jsx
- test/calendar_test.js
> Change showYearDropdown default to false

- .travis.yml
- README.md
- karma.conf.js
- package.json
> Add codecov reporting

- .jscsrc
- package.json
- src/day.jsx
This will hopefully catch cases where we accidentally mutate moment objects.
Re: #293
> Add JSCS moment immutability rule

- src/day.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
Partially addresses #296, relates to #78
> Add CSS class to days outside of month

- docs/src/example_components.jsx
- docs/src/examples/filter_dates.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/day.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
> Add ability to filter dates by predicate

- webpack.config.js
> don't expose tether anymore

- docs-site/src/example_components.jsx
- docs-site/src/examples/today.jsx
- docs/datepicker.md
- server.js
- src/calendar.jsx
- src/datepicker.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
> Today Button

- src/calendar.jsx
- src/datepicker.jsx
- test/calendar_test.js
Cleanups; mainly removing the `moment` prop, which looks like didn't work anyway
> Moment prop refactor

- src/datepicker.jsx
- test/datepicker_test.js
Re: #357 
Right now this is just a failing unit test which should pass when we get a fixed version of react-tether.
> Fix unmount error from react-tether

- package.json
- src/datepicker.jsx
Fixes #352, fixes #354, fixes #357
> Upgrade react-tether to 0.3.3

- scripts/release.sh
@martijnrusschen, hopefully this will help us avoid problems with the releases
> Change release script to wipe node_modules

- src/stylesheets/datepicker.scss
> Add z-index to tether-element

- src/datepicker.jsx
- test/datepicker_test.js
Addresses #343, my specific issue with appending the calendar to the body has to do with triggering a mouseout of the datepicker container.
> Parameterize the calendar's parent node

- docs/datepicker.md
- src/datepicker.jsx
Continuing work from #369. Added proptype and used generator to add the prop to the docs. Also renamed the prop to a more descriptive name. (**Breaking change**)
> Rename className prop and add to docs

- docs/datepicker.md
- src/datepicker.jsx
Reverts Hacker0x01/react-datepicker#370
> Revert "Rename className prop and add to docs"

- .eslintrc
- package.json
Did a first pass on setting up the rules. I'll enforce and fix the issues once we've settled on the rules. I used Standard config, combined with a more specific React config.
> Set up ESLint with Standard and React config

- src/calendar.jsx
- src/date_input.jsx
- src/datepicker.jsx
- src/day.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- src/week.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
- test/calendar_test.js
- test/datepicker_test.js
- test/day_test.js
- test/month_test.js
- test/week_test.js
- test/year_dropdown_test.js
> CSS refactor

- README.md
> Add IE9 compatibility note

- src/calendar.jsx
- src/date_utils.js
- test/date_utils_test.js
> Hide month navigation buttons when dates are disabled

- src/calendar.jsx
- src/date_utils.js
- test/calendar_test.js
- test/date_utils_test.js
Continues #435
Incorporate `includeDates` in the initial calendar view.
> Date in view improvements

- src/calendar.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
Fixes #440, continues #441
Separates weekday headers into a new CSS class
> Day name class

- package.json
> Upgrade react-onclickoutside to 4.8.0

- .babelrc
- .travis.yml
- package.json
- src/date_input.jsx
> Allow react 15

- src/datepicker.jsx
- test/date_input_test.js
For issue https://github.com/Hacker0x01/react-datepicker/issues/465
> Support autoComplete prop

- src/date_input.jsx
https://facebook.github.io/react/warnings/unknown-prop.html
This PR removes unsupported props from the <input>.
> React "Unknown Prop Warning" fix

- README.md
- src/datepicker.jsx
- test/datepicker_test.js
as mentioned in #409 here is the pull request.
This change contains:
* tests
* update of the readme
* the feature
> feat: add keyboard accessibility support

- src/calendar.jsx
- src/datepicker.jsx
- src/month.jsx
- src/week.jsx
This should provide `Event` obj to `onChange` etc.. (Related to #488).
> Propagate datepicker events up the chain

- docs-site/src/hero_example.jsx
- src/datepicker.jsx
- test/datepicker_test.js
> Add autoFocus prop

- karma.conf.js
- src/calendar.jsx
- test/calendar_test.js
> Fix for openToDate bug

- docs-site/src/examples/clear_input.jsx
> Fix example "clear Input"

- docs-site/src/example_components.jsx
- docs-site/src/examples/week_numbers.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- src/week.jsx
- src/week_number.jsx
- test/week_number_test.js
- test/week_test.js
> Add the ability to show week numbers on the calendar.

- src/datepicker.jsx
- test/datepicker_test.js
> Save time for selected date

- src/stylesheets/datepicker.scss
> Today button should clear float from calendar

- src/datepicker.jsx
https://github.com/Hacker0x01/react-datepicker/issues/628
> Calendar pop-up window does not close if using Macbook touchpad [fix #628]

- src/stylesheets/datepicker.scss
- src/year_dropdown.jsx
I hope this doesn't break anything.
> fix some styling issues (fixes #646)

- src/calendar.jsx
- src/datepicker.jsx
- test/calendar_test.js
* forceShowNavigation - allow to show navigation between month when "includeDates" disable it.
* onMonthChange - call when month changed
> Month change callback + force show month navigation

- docs-site/src/example_components.jsx
- docs-site/src/examples/month_dropdown.jsx
- docs-site/src/examples/year_dropdown.jsx
- src/calendar.jsx
- src/month_dropdown.jsx
- src/month_dropdown_options.jsx
- src/stylesheets/datepicker.scss
- test/month_dropdown_test.js
The styles are horribly broken, but apart from that, it works.
Oh, and it has no tests...
> add month dropdowns

- src/month_dropdown.jsx
- src/year_dropdown.jsx
Fixes warnings I introduced in c4c76c6f174d378f97f1b60089cdbb4bee00e651 and ea93c7e2dd89dfefb5dcc8753ffeee8baca86d74.
> add missing keys

- docs-site/src/example_components.jsx
- docs-site/src/examples.scss
- docs-site/src/examples/children.jsx
- src/calendar.jsx
- src/datepicker.jsx
Allows adding extra content within the calendar.
Also, fix stylesheet so &lt;pre&gt; works.
> Render Calendar children

- src/year_dropdown_options.jsx
- test/month_dropdown_test.js
- test/year_dropdown_options_test.js
- test/year_dropdown_test.js
Fixes #683 
- Add future years to dropdown
> Year dropdown presents future years by default

- src/calendar.jsx
- src/datepicker.jsx
- src/day.jsx
- src/month.jsx
- src/week.jsx
Fixes https://github.com/Hacker0x01/react-datepicker/issues/745
> Hide keyboard-selection highlighting in inline mode

- src/calendar.jsx
- src/datepicker.jsx
> Fix broken openToDate by not defaulting initialDate to preSelection

- docs-site/src/example_components.jsx
- docs-site/src/examples/inline_portal.jsx
- src/datepicker.jsx
I need open the datepicker in a portal after click on an icon in a my custom field.
> Improve the datepicker for using inline and portal props together.

- README.md
- docs/datepicker.md
- package.json
- src/datepicker.jsx
* Added 'onClickOutside' callback
* Fixed issue #786 in 'setPreSelection'
* Added 'cros-env' for windows builds
> * Added 'onSelect' and 'onClickOutside' props, some fixes

- docs-site/src/example_components.jsx
- docs-site/src/examples/disable_date_auto_correction.jsx
- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
These are the suggested changes to address issue #768 .
> Changes to support disabling auto correction of dates

- README.md
> Delete extra commas

- README.md
that effects what react you can use.
> Added note about react-onclickoutside dependency 

- src/datepicker.jsx
This pull-request addressed the solution I proposed in #885.
> Fix re-focusing problem related with usage of `Tab` (#885)

- docs-site/src/examples/timezone_date.jsx
- src/datepicker.jsx
> Take utcOffset into account when creating a defaultPreSelection date

- src/calendar.jsx
- src/datepicker.jsx
> Fix PropTypes ref

- src/datepicker.jsx
> Fix inline datepicker month switch bug

- src/popper_component.jsx
- src/stylesheets/datepicker.scss
and anyone who wants can redefine It.
> fixed wrapper div, now it has own class

- docs-site/bundle.js
- docs-site/style.css
- src/date_utils.js
- src/day.jsx
- test/day_test.js
Hi!
Thank you for the useful react component.
@jochenberger has been requested on [this Issue](https://github.com/Hacker0x01/react-datepicker/issues/644), I also wanted to add class of the day of the week, so I implemented it.
I attached the following class to day elements. 
| day | class |
|:--|:--|
| Mon | react-datepicker__day--mon |
| Tue | react-datepicker__day--tue	 |
| Wed | react-datepicker__day--wed |
| Thu | react-datepicker__day--thu |
| Fri | react-datepicker__day--fri |
| Sat | react-datepicker__day--sat |
| Sun | react-datepicker__day--sun |
The request is only Sunday in the issue, but in Japan, there is a custom to use blue color on Saturday, and I thought that someone want to use other color on other day of week, so I attached the class on each day.
If there is no problem, …
> Added day of week className to the day.

- docs-site/bundle.js
- docs-site/style.css
- src/day.jsx
- test/day_test.js
Hi!
Specifying the same day multiple times in `highlightDates` only applies the first class. I think that all classes should be applied, what do you think?
> Same day in highlightDates

- src/datepicker.jsx
- test/datepicker_test.js
Also remove semicolon by eslint checking.
fixes #927
> Change selection of inline picker. fix #927.

- docs-site/bundle.js
- src/datepicker.jsx
- test/datepicker_test.js
change ref to official usage: https://facebook.github.io/react/docs/refs-and-the-dom.html
> no more this.refs

- docs-site/src/examples/show_time.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/time.jsx
- test/time_format_test.js
Also:
- Added a test case
- Updated the docs
> Added support for timeFormat prop #1034

- docs-site/bundle.js
- docs-site/src/example_components.jsx
- docs-site/src/examples/open_by_default.jsx
- src/datepicker.jsx
When using react-datepicker, I had a tricky time finding how to make the picker open by default, so I thought it'd be helpful to create an example for it.
Thanks --
> Adding example for OpenByDefault

- src/calendar.jsx
- src/date_utils.js
- src/datepicker.jsx
- src/day.jsx
- test/datepicker_test.js
> Change default back to local time

- src/datepicker.jsx
- test/datepicker_test.js
solves https://github.com/Hacker0x01/react-datepicker/issues/962
> Clear button is not working when date is given as input #962

- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
- test/year_dropdown_options_test.js
Hi, guys. Thanks for the awesome plugin!
Actually, I've just cleared #824 and made the changes that were requested by @aij. It would be great if you could merge it 🐨 
Also I think that this PR closes #1000.
> Limit year list in Dropdown Scroll Mode by minDate and maxDate

- docs-site/bundle.js
- docs-site/style.css
- package.json
- yarn.lock
Temporary fix for #975 and #1003 while there are still compatibility issues with react-onclickoutside@6.1.0 and above. Credits to @dhruvparmar372 and @Deraen.
> Downgraded react-onclickoutside dependency to 6.0.0

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
This tiny patch will give us the opportunity to set font color of these headers.
> Extract font color of month and time headers to vars

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
Need the font to be a variable to customize
> Make default font a variable

- src/stylesheets/datepicker.scss
Stop a UI issue causing flickering when the datepicker was near the bottom of the screen
fixes #1085
> fix(date-picker): Remove negative margin

- docs/datepicker.md
- src/calendar.jsx
- src/index.jsx
- test/calendar_test.js
- test/datepicker_test.js
We've got `onMonthChange`, why not have this as well.
> Added onYearChange prop

- src/index.jsx
- test/datepicker_test.js
> Added preventOpenOnFocus prop

- package.json
- yarn.lock
> Downgrade dependencies to fix starting webpack

- src/calendar.jsx
- src/stylesheets/datepicker.scss
> issue-1204 replaced the datepicker navigation links with buttons

- docs-site/src/examples/show_time.jsx
- src/calendar.jsx
- src/index.jsx
- src/stylesheets/datepicker.scss
- src/time.jsx
- test/show_time_test.js
According to issue https://github.com/Hacker0x01/react-datepicker/issues/1237 I have added `timeCaption` property.
> Time caption property

- src/index.jsx
- test/datepicker_test.js
- test/helper_components/custom_input.jsx
- #1230 check the handleChange arguments before using it as en event object
> issue #1230 - handleChange arguments checks

- package.json
- src/index.jsx
- test/datepicker_test.js
- test/timepicker_test.js
> Fix for time selection not allowing other changes

- package.json
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/month_dropdown.jsx
- src/month_dropdown_options.jsx
- src/month_year_dropdown.jsx
- src/month_year_dropdown_options.jsx
- src/popper_component.jsx
- src/stylesheets/variables.scss
- src/time.jsx
- src/week.jsx
- src/week_number.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
- test/timezone_date_picker.jsx
#1189 ran prettier on all the `.jsx` files but was missing jsx in the pre-commit hook.
> Add jsx to prettier lint-staged and rerun prettier

- package.json
- yarn.lock
Updating react-popper to 0.8.3.
> fix: Updated react-popper version

- docs-site/src/example_components.jsx
- docs-site/src/examples/inject_times.jsx
- docs/datepicker.md
- docs/index.md
- docs/time.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/time.jsx
- test/inject_times_test.js
Proposed feature according to https://github.com/Hacker0x01/react-datepicker/issues/1328
> Ability to inject times outside of default time interval

- docs/datepicker.md
- src/index.jsx
- test/datepicker_test.js
- test/week_number_test.js
To resolve an accessibility issue, a title attribute was added to the clear button that will read and display as a tooltip "Clear date"
> Adds title attribute to clear button

- test/datepicker_test.js
- test/month_dropdown_test.js
Seems to work locally, lets see what Travis says.
> Re-enable tests

- docs-site/src/examples/inline.jsx
- src/index.jsx
- test/datepicker_test.js
> Bk fix year pre selection bug, fixes #1345

- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- test/calendar_test.js
Sorry for large diff, i think this is prettier changes
> Add formatWeekDay prop for weekdays custom formatting

- docs-site/bundle.js
- docs-site/src/example_components.jsx
- docs-site/src/examples/multi_month_inline.jsx
- src/index.jsx
- test/datepicker_test.js
> Fix month jumping in inline multiple month calendar

- README.md
> add -> app

- docs-site/bundle.js
- src/calendar.jsx
- src/index.jsx
- src/stylesheets/datepicker.scss
Improves accessibility and facilitates custom localisation by having a default value for the month navigation.
> Adding a label to the month navigation buttons

- CONTRIBUTING.md
Fixed few things in CONTRIBUTING.md.
> chore(docs): Fixes broken link and typo

- src/date_utils.js
Addressing issue https://github.com/Hacker0x01/react-datepicker/issues/1594
> date-fns compatibility update for weekday formatting

- docs-site/bundle.js
- docs-site/src/example_components.jsx
- docs-site/src/examples/month_picker.jsx
- docs-site/style.css
- src/calendar.jsx
- src/index.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
- test/month_test.js
This is the first step towards range month picker. I am adding this as a new variation of the date picker. 
It also solves some of the issues people are facing in https://github.com/Hacker0x01/react-datepicker/issues/1249
> Month year picker

- docs-site/bundle.js
- docs-site/src/example_components.jsx
- docs-site/src/examples/range_month_picker.jsx
- docs-site/style.css
- src/date_utils.js
- src/inputTime.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- test/date_utils_test.js
- test/month_test.js
- test/time_input_test.js
Description: Add a new variant of Date picker <Range month/year picker>.
Issue: https://github.com/Hacker0x01/react-datepicker/issues/1249
Demo:
> Range month year picker

- docs/index.md
Multiline statements aren't allowed in a table cell
> No multiline statements in cells

- docs-site/src/examples/on_blur_callbacks.jsx
Fixed type for example 'onBlur callbacks in console'
> Fixed type for example 'onBlur callbacks in console'

- src/date_utils.js
- src/index.jsx
- test/date_utils_test.js
Resolution for https://github.com/Hacker0x01/react-datepicker/issues/1668
> Fix manual changing time (issue #1668)

- src/month.jsx
> Fixed month aria-label date format (Fixes: #1767)

- src/month.jsx
I need range start & range end class because I want to edit css these elements.
Can you review and build up the release version because I have a urgent project?
Thanks a lot!!
> Add range-start and range-end class in month range

- src/date_utils.js
- src/month.jsx
- test/date_utils_test.js
Hi @martijnrusschen ,
Can you review and build up the release version because I have a urgent project?
Thanks a lot.
> Fix adding range-start and range-end class in month range, MinDate, MaxDate is not working in Month Range Picker

- docs-site/src/components/App/index.js
Hehe, you were too fast with merging. Should also be included. Sorry for so much PRs...
> fix: example at the top was not closable

- docs-site/src/components/App/index.js
- docs-site/src/components/Examples/index.js
- docs-site/src/examples/quarterPicker.js
- docs-site/src/examples/rangeQuarterPicker.js
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
- test/date_utils_test.js
- test/month_test.js
Similar to the month year picker, I have added this variation to choose quarters within a year. The quarter translates into a date of the first day of the quarter.
This solves issue #1773
> Quarter year picker

- README.md
- Add yarn install example
- Add additional steps needed to get a working test site from first install
> Update instructions for local dev

- src/popper_component.jsx
Submitting new PR with minimal changes, as asked by @martijnrusschen on https://github.com/Hacker0x01/react-datepicker/pull/1448
> Added class to Manager to allow for percentage width

- README.md
📖 DOC: npm & yarn links added to easily understand.
> 📖 DOC: Links added

- src/stylesheets/datepicker.scss
This will update the triangle placement when `bottom-end` or `top-end` are used for placement.
Still might need another update for `left-end` and `right-end`?
> Update triangle placement

- src/calendar.jsx
Sorry for separate pull requests - their are just must be as one transaction :)
> monthClassName  - Update calendar.jsx

- src/calendar.jsx
> Use correct aria labels for Next Month/Year

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/monthPickerFullName.js
- src/calendar.jsx
- src/index.jsx
- src/month.jsx
- Add a flag to allow month pickers to show full month name instead of short
> Add full month name flag for month picker

- src/calendar.jsx
- test/calendar_test.js
> Fixes issues when using renderCustomHeader with alt pickers

- src/calendar.jsx
- test/calendar_test.js
When selected prop is not set, InputTime initial value should be an empty string
> InputTime initial value

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/monthPickerTwoColumns.js
- src/calendar.jsx
- src/index.jsx
- src/month.jsx
Add a flag to allow month pickers to show in a two column month display layout
> Add two column month display layout flag for month picker

- src/day.jsx
- src/index.jsx
> add preventScroll option to programmatic focus

- src/time.jsx
- test/timepicker_test.js
added more flexibility to time.jsx to account for non-standard time intervals
resolves #2169
> handle non-standard time intervals - resolves #2169

- docs/datepicker.md
https://github.com/Hacker0x01/react-datepicker/issues/1040
> Added wrapperClassName prop

- src/calendar.jsx
- src/date_utils.js
- src/stylesheets/datepicker.scss
- src/year.jsx
- test/calendar_test.js
- test/date_utils_test.js
- test/year_picker_test.js
Update work with change year by next/previous buttons,
update render of years with saving position of years,
add preselected year styles,
cover by tests for next/previous buttons and showing periods of years,
add work with min/max dates.
solutions for #2167, #2166, #2154
> YearPicker upgrades

- .travis.yml
See these errors which spammed the CI: https://travis-ci.org/github/Hacker0x01/react-datepicker/builds/706480820#L1628
> ci: fixes ENOSPC warnings

- src/date_utils.js
Benefits:
- Reduces bundle size very slightly
- Improves readability
> Use set for setTime

- docs-site/src/examples/customTimeInput.js
- docs/inputTime.md
- src/calendar.jsx
- src/inputTime.jsx
- test/helper_components/custom_time_input.jsx
- test/time_input_test.js
This PR allows using pure date object in custom time input.
> Pass pure date object to time input

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/.eslintrc
- docs-site/src/examples/filterTimes.js
- docs/datepicker.md
- docs/index.md
- docs/time.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/time.jsx
- test/date_utils_test.js
- test/filter_times_test.js
Works similarly to filterDate. Includes tests and an example. Let me know if there are any problems!
Related issue: #2378
> Add filterTime property

- docs-site/src/examples/filterTimes.js
- src/time.jsx
> Bind renderTime to selected date

- docs-site/package.json
- docs-site/src/examples/configurePopper.js
- docs-site/yarn.lock
- package.json
- src/index.jsx
- src/popper_component.jsx
- src/stylesheets/datepicker.scss
- yarn.lock
Fixes https://github.com/Hacker0x01/react-datepicker/issues/2656, https://github.com/Hacker0x01/react-datepicker/issues/2647
> Revert popper v2 upgrade

- yarn.lock
Reverts Hacker0x01/react-datepicker#2655
> Revert "chore(deps-dev): bump webpack from 4.45.0 to 4.46.0"

- src/date_utils.js
- test/date_utils_test.js
> Fix parseDate default locale handling

- docs-site/src/components/Example/index.js
- docs-site/src/examples/.eslintrc
- docs-site/src/examples/customInput.js
Hello! I changed the example code for the doc site, which should answer #2497.
This was based on the example provided by @YanaLugina, and was tested working in my own project.
I read through the contributing guidelines etc but let me know if there's anything I've missed or should add.
Rob.
> Fix doc-site example for custom input

- examples/hello-world/package.json
- examples/hello-world/yarn.lock
Reverts Hacker0x01/react-datepicker#2764
> Revert "chore(deps): bump react-datepicker from 3.5.0 to 3.6.0 in /examples/hello-world"

- docs/datepicker.md
- docs/index.md
- src/index.jsx
- test/datepicker_test.js
I added a property named clearButtonClassName which will be added to the clear button classname property, to make it customizable !
> make the clear button customizable

- src/calendar.jsx
- test/calendar_test.js
Condition for renderCustomHeader with showTimeSelect prop was changed, now it works correctly.
Changes are [here](https://github.com/enflaer/react-datepicker/commit/6b8540a753144a3e4323dc0b54aec3fb55ad2aa8#diff-ba0a2548ba8e373159fbf38d080f9db8c4738205898b7357963178048223dc70R687-R691), other things are linting.
> #2846, changed condition for renderCustomHeader with showTimeSelect prop

- src/day.jsx
- src/week.jsx
- test/day_test.js
Need this for a project with a federal agency who has very strict 508 standards. 
fixes #2820
> Use locale when generating day aria label 

- src/stylesheets/datepicker.scss
Set width to 100% inside the component's container, so using it with e.g. the col-* classes of Bootstrap will become possible
> update datepicker.scss with full width

- src/stylesheets/mixins.scss
Produces identical result with dart-sass, but is compatible with both
dart-sass and libsass. libsass does not support math.div().
Fixes #3144.
> Replace math.div(..., 2) with ... * 0.5

- package.json
fixes Hacker0x01/react-datepicker#3301
> Fix sideEffects

- src/month.jsx
- test/month_test.js
To be consistent with display of year text today
> Fix: month text today not displayed

- README.md
if I don't do this - ide throws error for typescript
https://github.com/Hacker0x01/react-datepicker/issues/3050
> fix for typescript

- src/stylesheets/datepicker.scss
Fixed following issue of dropdowns overlap :
https://github.com/Hacker0x01/react-datepicker/issues/3518
Before fix:
After fix:
> fixed dropdowns overlap issue

- src/stylesheets/datepicker.scss
Fixed following issue of date and time select overlay:
https://github.com/Hacker0x01/react-datepicker/issues/3588
Before fix:
After fix:
> fixed time and date picker overlay issue

- docs/index.md
Just make the markdown render correctly.
> Cleanup table formatting

- README.md
Hi folks,
Thank you so much for providing and maintaining this repository. Kudos!
I tripped over the ```date:Date``` parameter in the ```onChange``` event in the Installation section of the README.md. Is this a typo?
Please feel free to use, study, share or edit this pull request.
Cheers!
> fix: adjust Installation section

- src/date_utils.js
- test/calendar_test.js
Fixes https://github.com/Hacker0x01/react-datepicker/issues/3918
Ref https://github.com/Hacker0x01/react-datepicker/pull/3582
> Fix regressions pull/3582

- docs-site/package.json
- docs-site/yarn.lock
Reverts Hacker0x01/react-datepicker#4038
> Revert "chore(deps): bump react-live from 2.4.1 to 4.1.2 in /docs-site"

- src/index.jsx
- test/datepicker_test.js
Calendar closes on Shift + tab (onBlur is now called)
Related issues:
- https://github.com/Hacker0x01/react-datepicker/issues/3685
- https://github.com/Hacker0x01/react-datepicker/issues/3561
> [FIX][A11Y] Close calendar when unfocused

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
Reverts Hacker0x01/react-datepicker#3998
Fixes https://github.com/Hacker0x01/react-datepicker/issues/4045#issuecomment-1578237779
> Revert "Replace all `rem` units with `em` units"

- src/stylesheets/datepicker.scss
> fix: Uneven margin in inline calendar

- src/stylesheets/datepicker.scss
> Fixes off centered clear button

- src/day.jsx
- test/day_test.js
Not sure how to link these, but this can be linked 
https://github.com/Hacker0x01/react-datepicker/issues/4066
> aria-selected true for range selected as well

- src/stylesheets/datepicker.scss
Reverts Hacker0x01/react-datepicker#4044
> Revert "fix: Uneven margin in inline calendar"

- .eslintrc
- package.json
- src/date_utils.js
- src/day.jsx
- src/month.jsx
- src/tab_loop.jsx
- test/calendar_test.js
- test/day_test.js
- test/filter_times_test.js
- test/include_times_test.js
- test/inject_times_test.js
- test/month_dropdown_test.js
- test/month_test.js
- test/time_input_test.js
- test/year_picker_test.js
- yarn.lock
Based on the config from https://www.npmjs.com/package/eslint-plugin-unused-imports
> Add eslint plugin to detect unused imports

- karma.conf.js
- package.json
- yarn.lock
Refs https://github.com/Hacker0x01/react-datepicker/issues/4133
https://webpack.js.org/migrate/5/
> webpack: upgrade to v5

- .github/workflows/build-docs-site.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- README.md
- scripts/release.sh
FYI @martijnrusschen 
This is better inline with our https://github.com/Hacker0x01/react-datepicker/blob/main/CODE_OF_CONDUCT.md
> rename master branch to main

- docs-site/yarn.lock
- examples/hello-world/yarn.lock
ran `yarn upgrade` on `/docs-site` and `/examples/hello-world`
> update docs site and examples

- .github/workflows/deploy.yml
Refs https://github.com/Hacker0x01/react-datepicker/issues/4133
> investigate failure on CI

- .github/workflows/deploy.yml
Because I'm slightly silly and cannot type, a hotfix to fix deploys..
> fix: use `@v4` rather than just `@4`

- docs-site/config-overrides.js
- docs-site/src/components/Examples/index.js
- docs-site/src/examples/excludeTimePeriod.js
- docs-site/src/examples/excludeTimes.js
- docs-site/src/examples/filterTimes.js
- docs-site/src/examples/includeTimes.js
- docs-site/src/examples/injectTimes.js
- src/date_utils.js
- src/month_dropdown.jsx
- src/month_year_dropdown.jsx
- src/month_year_dropdown_options.jsx
- src/popper_component.jsx
- src/portal.jsx
- src/tab_loop.jsx
- src/time.jsx
- src/year.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
This should avoid more PRs with prettier changes going forward.
> Run prettier on all files

- src/index.jsx
- src/stylesheets/datepicker.scss
- test/datepicker_test.test.js
> Disable clear button when the component is disabled

- README.md
> Fix Localization example in README.md

- test/exclude_time_period_test.test.js
- test/month_dropdown_test.test.js
- test/month_year_dropdown_test.test.js
- test/multi_month_test.test.js
- test/show_time_test.test.js
- test/time_format_test.test.js
- test/time_input_test.test.js
- test/week_test.test.js
- test/year_picker_test.test.js
Continuation from last time PR(#4559);
Ref https://github.com/Hacker0x01/react-datepicker/issues/4300
> fix: enzyme to RTL (some files) 2

- test/calendar_test.test.js
Continuation from last time PR(#4559);
Ref #4300
> fix: enzyme to RTL (calendar_test.test.js)

- docs-site/src/index.js
- examples/hello-world/src/index.js
Fixes https://github.com/Hacker0x01/react-datepicker/issues/4300
> Update Render methods of Docs site and example to React 18

- package.json
- yarn.lock
**Linked issue**: #4580
**Problem**
https://github.com/Hacker0x01/react-datepicker/issues/4580#issuecomment-1997729284
**Changes**
> Fix: update @types/node

- .github/workflows/test.yml
- package.json
- yarn.lock
> Update Codecov step in test suite

- .github/workflows/test.yml
---
title: ""
labels: ""
assignees: ""
---
**Problem**
**Changes**
> Try using native codecov package

- src/calendar.jsx
- src/input_time.tsx
- test/time_input_test.test.js
---
name: Migrate input_time.jsx
---
**Changes**
`input_time.jsx` was migrated to ts + added JSDocs
> [typescript-migration] input_time.jsx 

- src/tab_loop.tsx
---
name: Migrate tab_loop.jsx
---
**Changes**
`tab_loop.jsx` was migrated to ts + added JSDocs
> [typescript-migration] tab_loop.jsx

- src/date_utils.ts
- src/week_number.tsx
**Changes** `week_number.jsx` was migrated to ts + fix isSameDay args type
> feat: convert week_number.jsx into ts

- src/date_utils.ts
- src/day.tsx
---
name: Migrate day.jsx
---
**Changes**
`day.jsx` was migrated to ts + added JSDocs
> [typescript-migration] day.js

- src/week.tsx
- src/week_number.tsx
**Changes** `week.jsx` was migrated to ts
> [typescript-migration] week.jsx

- package.json
---
---
name: Added package manager property
---
Description: 
**Changes**
Added package manager property to package.json to avoid wrong behavior when you locally use yarn version 2 and newer.
> feat: added package manager property

- .github/workflows/test.yml
---
name: add type-check to gh actions
---
**Changes**
I extended the existing Github action called `test.yml` rather than creating a new one because this action already contains the rest of the checks, including eslint and prettier
> [typescript-migration] add type-check to gh actions

- src/date_utils.ts
- test/date_utils_test.test.ts
---
name: Migrate date_utils_test.test.ts
---
**Changes**
`date_utils_test.test.ts` was migrated to ts
> [typescript-migration] date_utils_test.test.ts

- test/week_number_test.test.tsx
---
title: "Change unit test to Typescript week_number_test"
labels: ""
assignees: "alvaromartinez986"
---
**Linked issue**: #4700 
**Problem**
Change to ts the unit test file
**Changes**
Add correct types
> Change unit test to Typescript week_number_test

- src/calendar_icon.tsx
- test/calendar_icon.test.tsx
---
title: "Change the calendar Icon unit test to TS"
labels: ""
assignees: "alvaromartinez986"
---
**Problem**
Change the unit test to ts, also I noticed the icon prop was not defaulted,so I changed to default
**Changes**
> Change the calendar Icon unit test to TS

- jest.config.js
Attempting to fix code coverage report, which was only fetching test files for some reason. Ref #4700
> Fix code coverage report

- src/day.tsx
- src/week_number.tsx
- test/month_test.test.tsx
---
name: [typescript-migration] month_test.test.js
title: [typescript-migration] month_test.test.js
labels: ""
assignees: ""
---
**Changes**
Converts month_test.test.js to typescript and makes handleOnKeyDown optional for day and week
> [typescript-migration] month_test.test.js

- jest.config.js
- src/calendar.tsx
- src/calendar_container.tsx
- src/index.tsx
- src/month_year_dropdown_options.tsx
- src/popper_component.tsx
- src/tab_loop.tsx
- src/test/calendar_test.test.tsx
- src/test/week_test.test.tsx
- src/time.tsx
- src/week.tsx
- src/week_number.tsx
**Changes**
- migrate fix src/test/calendar_test.test.tsx
> [typescript-migration] some tests

- src/index.tsx
**Linked issue**: #4899
**Problem**
- See issue
**Changes**
- fix DatePickerProps
> Fix: DatePickerProps

- docs-site/src/components/App/index.js
**Linked issue**:  closes #4936
**Problem**
See issue
**Changes**
Change dependency badge to coverage badge to match readme
> fix badge in docs site

- src/input_time.tsx
**Changes**
Fixed the Time Input's placeholder typo
> ✏️ Fix the time input's placeholder typo

- docs-site/package.json
- docs-site/yarn.lock
Reverts Hacker0x01/react-datepicker#5267
> Revert "chore(deps): bump react from 18.3.1 to 19.0.0 in /docs-site"

- LICENSE
- README.md
- package.json
- yarn.lock
Use latest stable yarn for package management
> Use newer yarn

- src/calendar.tsx
- src/calendar_icon.tsx
- src/input_time.tsx
- src/tab_loop.tsx
- src/with_floating.tsx
- src/year_dropdown_options.tsx
> 🚨 Fix TypeScript Linting warnings for React 19 upgrade

- package.json
- src/click_outside_wrapper.tsx
- src/test/datepicker_test.test.tsx
- src/test/helper_components/shadow_root.tsx
- yarn.lock
**Linked issue**: #5149
**Problem**
Calendar not clickable when wrapped with shadow-dom
**Changes**
The new test fails when removing the changes to `click_outside_wrapper`
> fix: fix click outside within Shadow DOM

- package.json
- rollup.config.mjs
- src/date_utils.ts
- src/test/calendar_test.test.tsx
- src/test/date_utils_test.test.ts
- src/test/month_test.test.tsx
- yarn.lock
Reverts Hacker0x01/react-datepicker#5326
> Revert "chore(deps): upgrade date-fns to v4.1.0"

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
The issue is due to the upgrade of "stylelint-config-standard" to v37.  I added more details regarding the issue and the fix in this comment - https://github.com/Hacker0x01/react-datepicker/pull/5343#issuecomment-2609094123
> 🎨♻️ Fix lint errors of combine css values combined with scss variable - due to an update of  "stylelint-config-standard" to v37

- src/stylesheets/datepicker-cssmodules.scss
Used https://sass-lang.com/documentation/breaking-changes/import/#automatic-migration
> Move away from @import

- docs-site/eslint.config.js
> fix preview: custom header with two months displayed
