Hacker0x01/react-datepicker

- bower.json
- package.json
- react-datepicker.js
- src/calendar.js
- src/date_input.js
- src/datepicker.js
I noticed that I wasn't able to select a date or cycle through the months on IE11. If I tried to increment the month, the calendar would close, same with trying to select a date. I even checked that it wasn't just my codebase by throwing up the example file on BrowserStack.
I believe the bug comes from the blur event firing twice in IE11 (don't ask me for any literature to back this up though!). I put a breakpoint in handleBlur and it was indeed firing one more time than in Chrome, which obviously would then set focus to be false since _shouldBeFocussed was never reset to true since handleCalendarMouseDown was not being fired again, just handleBlur.
The primary purpose of both handleBlur and handleCalendarMouseDown was to detect if the blur came from clicking inside or outside the …
> Fix issues with clicking on the calendar, primarily for IE11

- example.html
- react-datepicker.css
- react-datepicker.js
- src/calendar.js
- src/datepicker.js
- src/day.js
- src/stylesheets/datepicker.scss
- src/util/date.js
- test/util/date_test.js
Live example [here](http://cdn.rawgit.com/hahahana/react-datepicker/23f3362c1e3b7be530d2891fe4238be13a1c5469/example.html).
The example is getting a bit gnarly, what do you guys think? Maybe separate pages for different functionality with some documentation on the page too?
---
Should close https://github.com/Hacker0x01/react-datepicker/issues/69
> Add ability to disable dates in the future and/or past

- react-datepicker.css
- src/day.js
- src/stylesheets/datepicker.scss
While working with the react-datepicker I discovered that days in the
previous and/or next months look like they're disabled, but they're
not.
We should make it more clear dates in the previous and/or next month
are selectable. In order to achieve this, I propose to remove this
`this-month` state and make the day's color default to black.
Screenshot:
> Remove disabled-look from days in previous/next month

- package.json
React I believe should be a `peerDependencies` item since I believe this qualifies as a plugin component. This will help reduce this chance of duplicates in the bundle. Also, I believe `reactify` is only for dev.
> Moved react to peerDependencies, and reactify to devDependencies

- README.md
- package.json
since `./node_modules/.bin` is added to your PATH when running npm
scripts, add grunt-cli to deps to cut out `npm install -g grunt` step
> add grunt-cli to devDependencies

- src/calendar.jsx
- src/date_input.jsx
- src/datepicker.jsx
- src/day.jsx
- src/popover.jsx
- test/date_input_test.js
The peer dependencies in package.json show "react": "^0.12" as a peer dependency, which means that the JSX pragma is no longer needed for valid consumer modules.
This also fixes some deprecation error messages with tools like babel-loader.
> Remove unneeded old JSX pragma

- src/popover.jsx
In Firefox, I was seeing behavior like this:
I also noticed that on pages that scrolled, the datepicker would fix to the top of the page, due to the pin constraint. I don't think that this component needs to have scroll constraints - we really just want it to appear next to the input.
Also, has the build process changed? If so, can someone update the docs? I have no idea how to update the stuff in /example.
> Remove tether constraints on popover [fixes FF bug]

- README.md
The discussion about `npm i` or `npm install` isn't worth it's time. At least not in this context.
@RSO prefers `npm install` over  `npm i` so I have changed it to `npm install`.
> changing npm i to npm install

- .scss-lint.yml
I couldn't build the application without removing this rule in the `.scss-lint.yml`
> fix: remove `NameFormat` rule breaking `grunt build`

- src/date_input.jsx
- src/datepicker.jsx
With default of "datepicker__input". I know there is a pull request, but it wasn't merged yet. Its an absolute showstopper that there is currently no way to define a class name. This seems like the most unobtrusive, non-breaking way.
> Add className as prop

- package.json
Lodash is required in the source of 'calendar.jsx'. It should be a regular dependency instead of a 'devDependency'. The current dep configuration won't work for build environments that don't already have lodash installed.
> Change 'lodash' from a devDependency to a regular dependency

- src/datepicker.jsx
This change will allow a parent component to control the selected value of the date picker.  Use case is:
1. Initialize component with null value
2. User selects a date
3. A separate "Clear" button clears out the field by setting the selected prop to null
Fixes #133
> Allow parent to pass updates to selected

- package.json
This allows packages like [postcss-import](https://github.com/postcss/postcss-import) to look in the node package and find the correct css file for this component.
> Adds the style definition to package.json

- src/date_input.jsx
- src/datepicker.jsx
When using the datepicker on mobile the keyboard will pop up when selecting a date, using readonly will prevent this from happening.
> Added readonly

- README.md
I copied and pasted this and got a failure. This will prevent lazy folks like me from having the same issue.
> Remove long dash from npm install command.

- src/calendar.jsx
- src/util/date.js
- test/util/date_test.js
This PR fixes errors being thrown when either `startDate` or `endDate`
props are not supplied.
Fixes https://github.com/Hacker0x01/react-datepicker/commit/9715c69f4ad68866de35c350a6b0c42c5bd6cc0e#commitcomment-14071280
/cc @Reggino
> startDate and endDate props should not be required

- src/datepicker.jsx
Refs allow for external access to components without having to rely on component functions which may change if you decide to rejigger the implementation.
Addresses https://github.com/Hacker0x01/react-datepicker/issues/205
> Adding some handy refs

- package.json
> Limit version of react-clickoutside to be between 4.0.1 - 4.1.1

- package.json
This reverts commit 7dbc7eda795efed9bebe505df5d83b5d8aa8734c.
OnClickOutside's issue was fixed upstream ([very quickly](https://github.com/Pomax/react-onclickoutside/issues/51)! :smile: ), so the caret range won't install the bad version any more.
> Revert "Limit version of react-clickoutside to be between 4.0.1 - 4.1.1"

- karma.conf.js
- src/calendar.jsx
- test/calendar_test.js
Fixes #209
If minDate is after the current date, the focus is set to minDate, and if maxDate is before the current date, the focus is set to maxDate.
> Show valid date range in initial view

- src/datepicker.jsx
- test/datepicker_test.js
Fixes #156 
It seemed fishy that `hideCalendar` was only called when an `onBlur` function is passed in as a prop.  I could have simply refactored the `if` statement, but I decided to follow the style of `onFocus` by having a default no-op `onBlur`.
> Properly hide calendar on blur

- docs/src/example_components.jsx
- docs/src/examples/hide_year_dropdown.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
In many of my use cases, the user will be selecting dates near the present and will rarely need to navigate several years.  Having the year dropdown menu on a separate line takes up valuable screen real estate and IMO somewhat spoils the sleek look of the date picker.  This PR adds a `showYearDropdown` option to toggle its display (default true).
> Add option to hide year dropdown menu

- src/date_input.jsx
- test/datepicker_test.js
The null check in date_input.jsx introduced a bug (from e39175a9) where the date was no longer clearable. Not sure why the null check was added, but removed it and added a test.
> Fix bug with clearing dates

- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
- test/year_dropdown_options_test.js
- test/year_dropdown_test.js
Fixes #262
I refactored the year dropdown menu to separate the options into a separate component so that I could use `react-onclickoutside`.  As a bonus this improved the component's testability.
> Close year dropdown when clicking outside

- src/util/date.js
- test/util/date_test.js
Fixes #267 
The `inRange` method is modifying the input dates, which cascades into other failures.
> Don't modify dates when calling inRange

- server.js
Most of my dev'ing happens on a box running node v0.12.  This is the only line that needs to be changed to make running the docs page compatible.
> Remove Object.assign for node v0.12 compatibility

- docs/src/example_components.jsx
- docs/src/examples/on_clear_callbacks.jsx
- src/datepicker.jsx
Sometimes it is useful to have different callbacks for on change and on clear events. For example in on change handler we can't distinguish incorrect data input from clear button click because in both cases the handler will receive null. Of course there are maybe another use cases.
> Add on clear callback

- docs/src/example_components.jsx
- docs/src/examples/typeable.jsx
- docs/src/hero_example.jsx
- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
- test/datepicker_test.js
This improvement is connected with #250 issue. I haven't found better solution to make this enhancment and this one has one disadvantage that it is impossible to reset date to null when the date input has focus. 
P.S. I named the datepicker prop as 'isTypeable' because 'isEditable' may confuse user like it is imposible to change date.
> Make datepicker to be editable by user input

- src/calendar.jsx
- src/date_input.jsx
- src/datepicker.jsx
- test/calendar_test.js
- test/date_input_test.js
- test/datepicker_test.js
Re: #273; addresses #106, #161, #302, #309; supersedes #315; sets up #283 
The `setTimeout`s around showing and hiding the calendar were becoming a bit unwieldy and difficult to reason about/test.  Instead of using `focus` state, I instead started thinking in terms of `open` state, and refactoring with this mindset cleaned up the logic magnificently.  Many bug fixes easily fell into place.
> Refactor calendar open state

- src/date_input.jsx
- test/date_input_test.js
Fixes #106
When blurring the date input, either sets the value to the formatted date, or clears it if no date is selected.  Has the effect of wiping out invalid dates.
> Revert invalid date input when blurring

- package.json
- src/datepicker.jsx
- src/popover.jsx
- src/stylesheets/datepicker.scss
This deletes a large portion of untested code implementing the popover functionality and replaces it with [`react-tether`](https://github.com/souporserious/react-tether), a small wrapper around `tether`.
> Use react-tether for popovers

- package.json
- src/datepicker.jsx
- webpack.config.js
The last remaining dependency on lodash in implementation code is in `shouldComponentUpdate`, which compares props/state to determine if an update should occur.  I thought about this for a bit and I think it is safe to remove -- it is an optimization that is probably no longer necessary.  Some good insights in this article: http://buildwithreact.com/article/optimizing-with-shouldcomponentupdate  Namely, "...If you have one take away from this article, only use `shouldComponentUpdate` if you know you need it."
> Remove lodash as a consumer dependency

- src/datepicker.jsx
Re #373
Adding `dateFormat` to the prop types will make it appear in the API docs
> Add dateFormat to prop types

- package.json
I guess this is a side effect of me upgrading to NPM 3. Did anyone else encounter the same issue? Didn’t had this issue with NPM 2.x
> Add peerDependency of webpack-dev-middleware

- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
As part of our localization overhaul, I think we should use the default date format for the selected locale in `DateInput`.  The `L` format expands to the locale-specific format.  Examples:
* `en` : `MM/DD/YYYY`
* `en-gb` : `DD/MM/YYYY`
* `ko` : `YYYY.MM.DD`
> Use localized date format for DateInput

- src/date_input.jsx
- test/datepicker_test.js
The props locale wasn't being used when typing into the date input field and not using the calendar
and instead would clear the input, even if it was exactly what would be output by the clicking on a date in the calendar.
This passes the locale to moment.
> use locale for text input date

- src/date_input.jsx
- test/date_input_test.js
Hello,
I changed `componentWillReceiveProps` to compare formatted date instead of raw date - and added arguments locale and dateFormat to `safeDateFormat` because props are not set at this time.
Also added test cases for rerendering on format change...
Regards
> respect date format change on rerender

- src/stylesheets/datepicker.scss
There were a couple regressions caused by the CSS refactor in #391 -- only mismatched class names.
cc @martijnrusschen
> Fix CSS refactor regressions

- .gitignore
- gruntfile.js
- package.json
- src/year_dropdown.jsx
Reduced-bloat packaging for npm & webpack
`react-datepicker`'s npm module has a main file
`./dist/react-datepicker.min.js`. This file is built by webpack, so it
inlines both `classnames` and `react-tether` dependencies.  
The `classnames` and `react-tether` dependencies in package.json are
hence unused by consumers of `react-datepicker`. Right now they'd be
more appropriate in devDependencies. But this commit proposes another
solution.
I'm using `react-datepicker` with npm, and importing via webpack. My app
also uses `classnames`, and could presumably use `react-tether` too. But
since these `react-datepicker` dependencies are inlined, they cannot be
shared with the host application, despite being present in package.json.
This commit proposes that the main file for distribution via npm is …
> Reduced-bloat packaging for npm & webpack

- docs-site/src/style.scss
- src/date_input.jsx
- src/stylesheets/datepicker.scss
Addresses #396
Removes the default styling applied to the `<input>` in `DateInput`, allowing for greater styling flexibility.  Moves the default styles to the CSS of the demo site so that the examples still look nice.
> Remove date input styles

- src/stylesheets/datepicker.scss
`input` elements are inline-block but `div` is a block element.
react-datepicker wraps its input with a div. As far as I can tell, the
purpose of the wrapper is setting up a positioned container for the
absolutely positioned `react-datepicker__close-icon`. But since the
`input` isn't a block element, the close-icon doesn't line up with the
`input`. Making the wrapper `div` have `display: inline-block` fixes 
that.
Before:
After:
> Add inline-block to react-datepicker__input-container

- package.json
- src/datepicker.jsx
- test/datepicker_test.js
If the default clickoutside class were to change it would be an API break, so theoretically we are already protected against that.  But manually specifying the class avoids having to match the "magic" string in the clickoutside library.
> Manually control clickoutside class

- gruntfile.js
- scripts/release.sh
Currently the file extensions from `src` are being preserved, which means that the transpiled files have the `.jsx` extension.  This makes it semi-painful to consume `lib` because the module bundler must be configured to recognize `.jsx`.
In the long run I think we should probably just rename `.jsx` files in `src` to `.js`
> Transpile to .js

- src/datepicker.jsx
- test/datepicker_test.js
Fix issue w.r.t disabled state.
Currently, if you disable the date picker and click on it, nothing happens until the date picker  is enabled again. Then, it shows the calendar without any user interaction.
This fix prevents this from happen, disabling any status change meanwhile the component is disabled.
> Prevent setOpen after clicking the input meanwhile component is disabled

- .babelrc
- package.json
- src/datepicker.jsx
- src/tether_component.jsx
Part of React v15 support (#444)
Unfortunately react-tether has changed their API, so we need to inline the component until the old API can be supported.  Perhaps we can revisit adding it back as a dependency in the future.
> Remove react-tether dependency

- docs-site/src/example_components.jsx
- docs-site/src/examples/inline.jsx
- src/datepicker.jsx
- test/datepicker_test.js
Hi,
I needed inline version of calendar for my project (calendar rendered directly without TetherComponent), so I added new prop `inline` to achieve this behavior for the user and implemented this functionality. I also added new example with `inline` prop.
I can use my enhanced component directly, but maybe you will find this feature useful for other people and you will merge it directly into your code.
Thank You very much for awesome date picker!
Michal
> Inline calendar

- docs-site/src/example_components.jsx
- docs-site/src/examples/fixed_calendar.jsx
- docs/datepicker.md
- src/calendar.jsx
- src/datepicker.jsx
- src/month.jsx
Lets to set fixed size of the calendar (6 rows of weeks). In addition, lets to prevent issue with top position of the calendar.
Without fixed size:
Fixed size:
> Add option for fixed size of the calendar

- src/calendar.jsx
- test/calendar_test.js
See #525 
With this PR, when setting an openToDate along with a minDate and/or a maxDate, the calendar will initially open to the openToDate if it falls within the range.
> Make openToDate work with minDate and maxDate

- src/day.jsx
- src/month.jsx
I was writing a ui test and realized that I can't click the div element containing a specific day text without using XPath. The unique aria-labels will change that while also helping screen readers better understand the elements and their roles as date options.
> Add accessibility tags to month and day jsx

- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
First, thanks for creating react-datepicker!
I would like to suggest allowing multiple formats for date entry. Our users often use the input box for manually typing or pasting dates. If the date provided does not __exactly__ match the specified dateFormat, this will fail. For example, if dateFormat is 'MM.DD.YYYY' and the user inputs '1.1.2016', the date will be rejected as invalid. 
As Moment.js already offers this functionality by simply providing an [array for formats](http://momentjs.com/guides/#/parsing/multiple-formats/). This requires only minimal changes (I hope I didn't miss anything).
If an array of formats is provided, the first format will be used to format the output but all other formats would be used to parse the input.
Would you please consider merging this PR? Thank you …
> Allow multiple formats for date input.

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
The rem units I used were calculated such that the calendar would appear the same on a page with `html, body { font-size: 14px; }` as it does currently on a page with any font size.
> Use rem units for size to improve visibility on pages with a larger font

- docs-site/src/example_components.jsx
- docs-site/src/examples.scss
- docs-site/src/examples/custom_input.jsx
- src/date_input.jsx
- src/datepicker.jsx
- test/date_input_test.js
Addresses https://github.com/Hacker0x01/react-datepicker/issues/529
Added a `customInput` prop which allows you to pass in your own component, allowing you to add custom functionality and styling.
> Add ability to pass a custom input

- docs-site/src/example_components.jsx
- docs-site/src/examples/highlight_dates.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/day.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
- src/week.jsx
- test/day_test.js
This just adds another parameter `highlightDates` to the `DatePicker` component which accepts an array of Moment objects representing the dates to be highlighted.
Highlighted dates will display with a green background in the calendar.
I've used this in my own log/journal app to indicate days that already have existing entries.
> Highlight dates

- src/date_input.jsx
- test/date_input_test.js
With custom inputs, sometimes you could get a DOM event vs. a JS event. This change accommodates both.
> support other specs for preventDefault

- src/calendar.jsx
In 441edf887e76f51e631527d6c03c45bda673c046 we manually updated the docs, this won’t hold if we’re releasing new docs. I updated the code that’s used to generate docs. Please make sure this is correct.
> Correct proptypes to reflect updated docs

- src/stylesheets/datepicker.scss
When manually testing my other pull request, I noticed that the month navigation arrows were missing. I added a z-index to the react-datepicker__navigation class to fix.
> Fix month arrow visibility issue

- src/datepicker.jsx
- test/datepicker_test.js
A regression was introduced in this pull request #608
DateInput calls it's `onChange` prop with a `null` date if the input value is and empty string (https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_input.jsx#L64). That value is then parsed by moment into an 'Invalid Date' in the DatePicker (https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L149) and then passed as a parameter to it's `onChange` prop.
This pull request fixes the regression and passes `null` instead. This is the same behavior that DatePicker had before #608
> fix regression when clearing input field

- .eslintrc
- src/day.jsx
Since the PropTypes are the only documentation for a lot of features, they should be correct. Otherwise, they only cause confusion.
> emit errors for unused prop types

- package.json
- src/calendar.jsx
- src/datepicker.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
I moved the wrapping code outside of the actual class implementations to be able to unit-test those.
> Upgrade react-onclickoutside

- src/datepicker.jsx
This resolves #607 by ensuring that there is a valid date available to start the keyboard navigation/selection from.
> Use default date when initiating keyboard navigation

- webpack.config.js
TLDR: react-onclickoutside [exposes itself](https://github.com/Pomax/react-onclickoutside/blob/v5.3.3/index.js#L222) as `onClickOutside`, not `OnClickOutside`.
Having externalized React Date Picker (i.e. including `react-datepicker/dist/react-datepicker.js` via HTML rather than bundling it with webpack), I end up with the following warning:
> Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined
After some digging¹, I figured out that what's missing is [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) (I'd already externalized React, ReactDOM and Moment.js anyway).
However, including (externalizing²) that …
> Fix onClickOutside reference

- src/tether_component.jsx
If this loop:
```
Children.forEach(children, (child, index) => {
if (index === 0) {
firstChild = child
return
}
```
don't returned any value (now return `undefined`), this code will be compiled (only for minimize version) to:
```
return s.Children.forEach(e, function(e, n) {
if (0 === n) return void(t = e)
}), t
```
(You can see `dist/react-datepicker.min`). And the expression in operator `void` will not be invoked. And component will not be rendered.
I added `return false` in the loop, and now for minimize version operator `will not appear` will not appear.
> Returned false in forEach in the render of TetherComponent components

- docs-site/src/examples/month_dropdown.jsx
It doesn't accomplish anything useful here, in fact, it rather confused me that the year was not shown.
> remove `dateFormatCalendar` prop from example

- src/datepicker.jsx
According to issues  #679 and #498 date representation should be local or correct utcOffset must be used. Now `moment.utc().utcOffset()` as a default value for `utcOffset` is incorrect, because is 0. It must be `moment().utcOffset()`. Now when `utcOffset` is not set default value is user's local offset.
> Default value for utcOffset props should be moment().utcOffset()

- docs-site/src/example_components.jsx
- docs-site/src/examples/disabled_keyboard_navigation.jsx
- docs-site/src/examples/disabled_navigation.jsx
- docs/datepicker.md
- src/datepicker.jsx
- test/datepicker_test.js
Optionally disables arrows, page up/down, home and end keys
While I think it is nice to have the keyboard interaction available, it is also good to be able to turn it off.
The motivation for this is that we found that users in equal part either wanted to edit the date as text with keyboard functions (e.g. arrow keys) or wanted to click a date. So in our case, disabling the navigation only allows the former without affecting the latter. This PR makes that possible.
> Add an option that disabled navigation keys

- .gitignore
- docs-site/src/example_components.jsx
- docs-site/src/examples/portal.jsx
- src/datepicker.jsx
- src/stylesheets/datepicker.scss
- test/datepicker_test.js
This PR adds a new prop which creates a Portal/Overlay version of the calendar, and fixes issue #695 
This helps if the calendar is being used by a mobile device, or other small screen.
If the prop `withPortal` is passed, it will create a portal version of the calendar.
Example:
```js
<DatePicker
selected={this.state.startDate}
onChange={this.handleChange}
withPortal />
```
The docs have been updated. No tests have been updated as this did not affect any, and no new tests added as the logic is very straight forward.
Happy to hear feedback/changes.
> Add portal for mobile support

- src/datepicker.jsx
This is a minor bug fix. The portal wasn't 'click blocking', meaning if you clicked the 'background' to close the calendar you would interact with any elements/links behind.
> Added click blocking to portal

- docs-site/bundle.js
- src/datepicker.jsx
- test/datepicker_test.js
This PR fixes [issue](https://github.com/Hacker0x01/react-datepicker/issues/731) with datepicker trying to set state after being already unmounted thus resulting in React warning.
Things that were done:
- timeout id is now stored inside datepicker component,
- whenever component wants to unmount, timeout is cleared if it's created
> PreventFocus timeout is now cleared when datepicker is unmounted #731

- docs-site/src/examples/raw_change.jsx
This example is showing incorrect syntax. Removed extra closing tag.
> Removed extra closing tag in example for onChangeRaw

- src/calendar.jsx
- src/datepicker.jsx
- src/month_dropdown.jsx
As discussed in Issue #749, this removes Lodash from the datepicker.
Takes file size from 77kb to 57kb.
Lodash is still in dev deps because it uses in some of the tests.
Before:
After:
> Remove lodash and replace with inbuilt native functionality

- src/datepicker.jsx
- test/datepicker_test.js
This fixes the regression where the default was no longer
within the selectable calendar dates. (Mentioned in #736)
> Improve default pre selection

- src/stylesheets/datepicker.scss
- src/stylesheets/mixins.scss
- src/stylesheets/variables.scss
Changing the colors used in this library is somewhat painful. Either you have to copy over the `.scss` files and change `variables.scss` yourself or you have to override the colors with the same CSS rules. Instead, this PR makes the variables default, allowing you to import the stylesheet and set the colors easily:
``` scss
$datepicker__selected-color: #990c41;
@import "node_modules/react-datepicker/src/stylesheets/datepicker";
...
```
Because the variable names are relatively simple and could conflict with existing variables, I went ahead and modified the variables to add a `datepicker__` prefix, as there was already a variable called `datepicker__margin`. Let me know if you would like for me to revert that change.
> Make Sass variables overridable

- src/stylesheets/datepicker.scss
Fix #845
- Add z-index 1 to month and year dropdown to prevent the year dropdown to shine through month dropdown in scroll mode
> Add z-index 1 to month/year dropdown

- src/calendar.jsx
- src/month_dropdown.jsx
- test/month_dropdown_test.js
resolves #849 
- pass dateFormatCalendar down to MonthDropdown
- use the format to determine nominative or genitive display of month names
> Pass dateFormatCalendar to MonthDropdown

- src/datepicker.jsx
- test/datepicker_test.js
possible fix for #848 
I couldn't see any reason why we don't want the calendar to open on every InputKey event or change the preSelection on change of the selected input property.
Did I miss something?
> Change selected date on input + enter

- docs-site/src/examples/placement.jsx
- src/stylesheets/datepicker.scss
This allows the triangle to be positioned relative to the right side of the popover if the user passes `popoverAttachment="right"` as a prop.
> Better Popover Triangle Orientation

- .babelrc
- docs-site/bundle.js
- package.json
- yarn.lock
Resolves #836 by generating the missing display names for all components via babel-plugin-react-add-displayname.
I'm lazy, so I preferred this solution over a static property for each component.
> Generate component display names

- src/calendar.jsx
- test/calendar_test.js
I think that current behavior when `selected` and `openToDate` both specified and `selected ` take a precedence over `openToDate` is totally incorrect. Every time calendar is open it must be opened at `openToDate` if specified regardless of other values. It's should be treated as a constant value at which calendar will open every time. It's not a selection of any kind, it's just a page on which calendar will be opened.
See this issue #736 and my arguments for and some use cases.
> 'openToDate' prop is now take a precedence over 'selected' value

- src/datepicker.jsx
This adds a boolean prop that allows a user to click on the same day again. It is turned off by default.
I added this option because we created an inline calendar where the user can select a start date and end date from the same calendar, and a use case exists for selecting the same day for both.
> Allow Re-Selecting the same day

- scripts/generateMarkdown.sh
- src/datepicker.jsx
fixes #880 
Currently the `generateMarkdown.sh` creates a name-value pair for the props. This is not very readable since the page can get long. eg: https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md
updating the script, changes it to a table layout which makes the props docs more readable. eg: https://github.com/hozefaj/react-datepicker/blob/generate-docs/docs/datepicker.md
I have not generated the new docs, since this will done during the release process.
> updating doc generation script to create props as table

- scripts/generateMarkdown.sh
Added escaping for "|" symbol in typeValue to avoid shifting cells in documentation
> Added escaping for "|" symbol at documentation

- docs-site/bundle.js
- docs-site/src/example_components.jsx
- docs-site/src/examples.scss
- docs-site/src/examples/custom_day_class_names.jsx
- src/calendar.jsx
- src/datepicker.jsx
- src/day.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
This adds `dayClassName` prop. This can be set to function which gets called for each day of rendered calendar. Function can return any object supported by classnames utility and it will be added to classnames of that day. Function gets rendered day's date as an argument.
This for example enables completely custom highlighting without the need to specify highlighted days upfront.
If function returns undefined, no class is added.
> Add prop to enable adding custom classes to days based on days date

- src/datepicker.jsx
While testing in node.js environment unmounting the component with enzyme didn't clear the timeout which lead to setting the state after component is unmounted. clearTimeout had `global` context, but setting timeout had `window`. it must be the same.
> fix for mismatch of global context

- src/calendar.jsx
- src/datepicker.jsx
- test/calendar_test.js
Example of code:
<DatePicker
autoFocus
useWeekdaysShort
selected={this.state.startDate}
onChange={this.handleChange}
/>
> Adding option to use MomentJS's weekdaysShort instead of weekdaysMin.

- src/datepicker.jsx
- test/datepicker_test.js
Related to #945 I think the correct behaviour should be exactly as if you click outside when the data is wrong.
The input field keep the wrong data as it is and the implementer should handle the error if needed.
Let me know if you find this interesting and if there is anything else to do I can keep working on it.
> Handling wrong data in input when Enter is press

- src/datepicker.jsx
During a previous pull request (#921), I added a check for `utcOffset` when computing the `defaultPreSelection`.  This _almost_ worked.  As it turns out, it works for any non-zero `utcOffset`, however, if the `utcOffset` is passed as `0` (GMT), the check returns falsey and does not evaluate properly.  This change also checks for a value of `0`.
Fixes #920
> Added check on utcOffset to see if it was passed with a zero value

- src/calendar.jsx
- src/datepicker.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- src/week.jsx
- src/week_number.jsx
- test/week_test.js
Example:
<DatePicker
showWeekNumbers
onWeekSelect={(firstDayOfTheWeek, weekNumber) => {
alert(firstDayOfTheWeek.format() + ', ' + weekNumber)
}}
/>
> Adding clickable week number feature.

- src/popper_component.jsx
- src/stylesheets/datepicker.scss
This is a PR to fix the issue highlighted in #952.
Since hardcoding values into component style props isn't considered a good practice, the `<Popper />`'s `z-index` attribute is now applied via the `.react-datepicker-popper` CSS class to allow users to overwrite it without having to use `!important` rule.
```JSX
// src/popper_component.jsx (new-implementation)
<Popper
  className="react-datepicker-popper"
  modifiers={popperModifiers}
  placement={popperPlacement}>
  {popperComponent}
</Popper>
// src/popper_component.jsx (old-implementation)
<Popper
  style={{zIndex: 1}}
  modifiers={popperModifiers}
  placement={popperPlacement}
  className="popper">
  {popperComponent}
</Popper>
```
> Move z-index from style props into CSS rule-set (#952)

- src/datepicker.jsx
- test/datepicker_test.js
This addresses a problem introduced in #960 (not yet part of a release version) where if a date picker is `inline` then it will crash when `selected` is null, due to the check added in #960 assuming that it will not be null.
> Avoid crash when inline and selected is null

- src/stylesheets/datepicker.scss
fixes #994
can be reproduced when the element is located in Bootstrap grid's .col-*-*
> fix width problem

- test/datepicker_test.js
Previously, this test would fail for the first 2 days of the month (where left arrow twice would result in
selecting the previous month).
> Fix flaky failing test

- src/datepicker.jsx
- src/popper_component.jsx
- test/datepicker_test.js
- test/test_wrapper.jsx
react-popper will place the popover in the same constraints as the
parent div. For cases where the parent div is somehow constrained -- a
scrollable div -- the popper will appear inside the div and will be
constrained by it to.
There are cases where you want the popover to be unconstrained it's
parent. To do this, you must place the popover in a container outside of
the constrained container.
demo: https://codesandbox.io/s/1ozy5ol5vl
Adding a popperContainer would allow a user to implement the following
function CalendarContainer (props) {
const containerId = document.getElementById('container-outside-root')
return (
<Portal container={containerId}>
{props.children}
</Portal>
)
}
// somewhere else
<DatePicker ... popperContainer={CalendarContainer} />
Which will then permit rendering the …
> Optionally wrap the popper element with a user-supplied container

- src/stylesheets/datepicker.scss
Address unnecessary nested 'calc' function which crashes webpack
> Fix #1049 nested css calc function

- docs-site/src/examples/configurePopper.jsx
- src/popper_component.jsx
- test/datepicker_test.js
The prop `popperClassName` is passed into the `PopperComponent`, however, it is ignored and never actually makes it to the `Popper` component.
Fixes #1019
> Implemented popperClassName prop

- docs-site/src/examples/timezone_date.jsx
Should fix https://github.com/Hacker0x01/react-datepicker/issues/1054, see my answer there for details.
> Fix timezone example in docs

- src/stylesheets/datepicker-cssmodules.scss
- src/stylesheets/datepicker.scss
I use [node-sass-chokidar](https://github.com/michaelwayman/node-sass-chokidar), it transforms *.scss files to *.css and keeps them near *.scss origins.
So, during the first build everything is ok, but during the next, it fails because it sees 2 files (e.g `variables.scss` & `variables.css`) and can't decide which file should be included.
Here is my output:
```
{
"status": 1,
"file": "./node_modules/react-datepicker/src/stylesheets/datepicker.scss",
"line": 1,
"column": 1,
"message": "It's not clear which file to import for '@import \"variables\"'.\nCandidates:\n  variables.scss\n  variables.css\nPlease delete or rename all but one of these files.\n",
"formatted": "Error: It's not clear which file to import for '@import \"variables\"'.\n       Candidates:\n         variables.scss\n …
```
> Add .scss extensions

- docs/datepicker.md
- src/index.jsx
When using react-datepicker with material-ui's `TextField`, you get an error because `TextField` is a stateless fn component and you can't pass `ref` to it. It however accepts `inputRef`. Allow users to define how the ref is passed to the custom input.
> Allow passing ref via custom props

- src/calendar.jsx
- src/date_utils.js
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
Highlight dates with custom class names and ranges, like this:
```
{ "react-datepicker__day--highlighted-custom-1": [
moment().subtract(4, "days"),
moment().subtract(3, "days"),
moment().subtract(2, "days"),
moment().subtract(1, "days") ]
},
{ "react-datepicker__day--highlighted-custom-2": [
moment().add(1, "days"),
moment().add(2, "days"),
moment().add(3, "days"),
moment().add(4, "days") ]
}
```
were calculated each time on day rendering and that caused slow performance with long arrays.
Now this array of objects is calculated just once in costructor and is kept in state as javascript flat Map of {dateString: className}
> Improved performance on rendering 'day' with highlighted days

- src/index.jsx
When the time selector is displayed, only close the picker when a time is selected (issue described in #1149)
Also, when passing in a custom input element, don't try and call a non existent `focus()` function #636
> Time selector close

- package.json
- yarn.lock
I got annoyed by the long waiting times when making a commit. This change moves the linter to `pre-push`, and only lints the changed files (which is way faster).
Based on option 1 from https://prettier.io/docs/en/precommit.html. Basically what this PR does is changing from option 2 to option 1.
> Replace pre-commit with lint-staged

- src/index.jsx
Hello ReactDatepicker maintainers,
Kudos for this library,
I use the `Datepicker` component with `isCleareable={true}`, but whenever I try to clear the datepicker, it messes with my urls, and the browser tries to go to "#" and navigates me to the home page of my app
I couldn't do anything with event.preventDefault() but changing to `javascript:void(0)` in my sources solves it. 
Would you consider merging this PR ?
Thanks,
Nassim
> Change close icon link href from # to javascript:void(0)

- package.json
- yarn.lock
Upgrades react-onclickoutside to fix production `findDOMNode was called on an unmounted component.` bug.
Fixes #1213
> Upgrade react-onclickoutside to 6.7.1

- src/index.jsx
- test/datepicker_test.js
First of all, thank you so much for all the hard work that's gone into `react-datepicker`. It's been invaluable to our company to have such a well-made react date picker available. 
I ran into a small issue where after a date is selected, passing `null` to the `selected` prop wouldn't actually clear out the input. After looking through the code I realized I could call `onClearClick` manually to clear the input without needing to display the clear button. This works in my case but it does currently require that an event object be passed to the `onClearClick` function or it crashes. This pull request makes a small change to not require that event object. It also adds a new `clear` function that could be included in the docs as part of the public API. 
If this all looks acceptable I would be …
> Added public function for programatically clearing the input

- src/calendar.jsx
- test/calendar_test.js
This makes month and month-year dropdown work with same logic as year-dropdown. 
Before this PR, month dropdown was duplicated as show in the image below:
> Show only one month and month-year dropdown when showing multiple months

- docs-site/src/example_components.jsx
- docs-site/src/examples/include_times.jsx
- docs/datepicker.md
- docs/index.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/time.jsx
- test/include_times_test.js
This option is the same idea as "includeDates" but applies to the time select. Only times that are included in the "includeTimes" list and also match up with settings like "timeIntervals" will be included. All other times are disabled.
This uses the same helper function as "excludeTimes" for implementation.
> Add an includeTimes prop

- docs-site/src/examples/date_range.jsx
Fixes the issue on the site docs when you select a start date that is after the end date.
> DateRange endDate doc bugfix

- src/stylesheets/datepicker.scss
Enforce the time-list to have a default box-sizing, which is content-box.
> added box-sizing to time-list

- package.json
There was a problem in the build script because it launched build:umd:dev and build:umd:prod.
build:umd:dev was setting NODE_ENV to 'development' so .babelrc.js was adding react-transform-hmr in the compiled file.
I changed package.json creating build-dev for development env and left build for production only.
FIXES: Local build issue #460
> Created two different builds for production and development enviroments.

- docs-site/src/example_components.jsx
- docs-site/src/examples/show_time_only.jsx
- src/calendar.jsx
- src/index.jsx
- src/stylesheets/datepicker.scss
- test/show_time_test.js
Now that react-datepicker has a time component, it would be nice to use this widget to _ONLY_ pick a time.  Added a `showTimeSelectOnly` prop that will only render the time container portion of the datepicker.
> feat: Time picker only

- package.json
I encountered an issue while trying to install this package as part of our Azure deployment. The error was in the `build` script:
> 'NODE_ENV' is not recognized as an internal or external command
I noticed that the `build` and `build-dev` scripts are the only 2 which don't use `cross-env` to set the Node environment variable(s) necessary for the script to run. Is this intentional?
Adding `cross-env` to the scripts fixed the deployment for us as our Azure service is a Windows environment.
> Use cross-env for build scripts to fix Windows usage.

- docs-site/src/examples/inject_times.jsx
- src/date_utils.js
- src/time.jsx
- test/inject_times_test.js
Following up on https://github.com/Hacker0x01/react-datepicker/pull/1329
Feature proposed at https://github.com/Hacker0x01/react-datepicker/issues/1328
Added ability to :-
- Insert multiple times in between each interval. Previously only one injected time allowed per interval.
- Auto sort injected times so that they appear chronologically
> Improvements to injectTimes

- .flowconfig
- package.json
- src/week_number.jsx
- yarn.lock
This is a pretty minimal conversion. We could make `onClick` and `handleClick` be functions that take a `SyntheticEvent` for stricter checking.
> Convert week_number.jsx to flow (as a simple example)

- src/index.jsx
`handleBlur()` calls `deferFocusInput()` if the date picker is open. `deferFocusInput()` schedules a later `setFocus()` call, which didn't make sure the input element is still mounted before focusing it, yielding an unhandled exception.
I'm getting this exception with a DatePicker component embedded in a react-tippy tooltip, when leaving the tooltip with an opened date picker.
> Fix potential exception after unmounting

- src/index.jsx
- test/datepicker_test.js
A button in a form gets the type attribute set to submit by default, if the type is not specified.
Submitting a form with a clearable datepicker component by pressing enter in a field currently triggers the clearing of the datepicker component, instead of submitting the form.
This can be fixed by setting the type attribute of the clear button to "button".
> Set type attribute of the clear button to "button"

- docs-site/src/example_components.jsx
- docs-site/src/examples/calendar_container.jsx
- src/calendar.jsx
- src/calendar_container.jsx
- src/index.jsx
- test/datepicker_test.js
This patch lets you specify a container for the calendar, solving #1384.
Example usage:
```js
<DatePicker
selected={this.state.startDate}
onChange={this.handleChange}
calendarContainer={MyFancyBox}
/>
```
Implementation notes:
* I modeled the feature after the existing `popperContainer` prop.
* The approach was stolen from [react-day-picker](http://react-day-picker.js.org/examples/input-custom-overlay/). Their approach is good because it is composable, letting you add elements to the top or bottom, inside or outside the container, and in extreme cases even manipulating or replacing the children.
* This patch obviates the need for supporting `children` as a prop, however I left that feature untouched.
* The original container is exported from the entrypoint as a component so it can be …
> Add calendarContainer prop

- src/index.jsx
Calendar in withPortal mode doesn't close on mobile devices when timeSelect added.
> fixed calendar withPortal closing

- src/index.jsx
- test/datepicker_test.js
Some users prefer editing dates without using the calendar. However, whenever you press a key, the calendar automatically pops up. Even worse, left and right arrows are double booked: they navigate the cursor in the input control but also move to another day in the calendar.
This PR changes the behavior such that the calendar is only opened if you press the up or down arrow and not for all keys except tab, escape and Enter. That way, you can close the calendar with Escape and edit the date in place and the calendar you just closed doesn't suddenly pop up again with each key press.
> Only open the calendar for ArrowUp and ArrowDown

- test/datepicker_test.js
The test 'should update the preSelection state when a day is selected with mouse click' was failing because today is at the start of the month. Hence today is rendered multiple times and findRenderedDOMComponentWithClass was throwing an error.
By switching to scryRenderedDOMComponentsWithClass and taking the first element the test passes when multiple months are rendered.
> Fixed test which fails when today is at the start of the month

- README.md
It's fine, but I want to fix it.
before the change:
```js
<DatePicker selected={this.state.date}
onSelect={this.handleSelect //when day is clicked}
onChange={this.handleChange //only when value has changed}
/>
```
after the change:
```js
<DatePicker selected={this.state.date}
onSelect={this.handleSelect} //when day is clicked
onChange={this.handleChange} //only when value has changed
/>
```
> Move '}' for js code markdown.

- src/index.jsx
- test/datepicker_test.js
This is a bugfix for a weird keyboard interaction.
The problem: A user is scrolling through dates with the arrow keys. Then they accidenatlly press <kbd>Ctrl</kbd>, an innocuous keypress which should not affect the UI state at all. But instead, the preselect date is cleared, and if they try to keep scrolling, all their progress is reset and the datepicker will take them back to today's date.
The solution: Only set the preselect date when the keypress is a navigation key.
There was a slight conflict with #946. To solve this, I tried to keep track of the most recent user intent in React state. If the user is typing, chances are they care most about the input text. Likewise, if they are navigating with arrows keys, the preselect should likely take priority.
> Preserve the preselect date when the user is typing

- src/calendar.jsx
I found out a duplicated default prop. There are two `previousMonthButtonLabel` definitions in `Calendar` component. This PR will fix one of the default props into `nextMonthButtonLabel`.
> Fix duplicated defaultProps in Calendar

- src/stylesheets/datepicker.scss
The scroll top of a list of times is calculated assuming a height of 30px for each list item in` time.jsx`:
`this.list.scrollTop = 30 * (multiplier * currH);`
However, the actual height of the time-list-item is 31px, so the scroll top is often inaccurate.
This change ensures the selected time-list-item will be scrolled into view.
fixes #1396
> Selected time scrolltop fix (#1396)

- docs-site/bundle.js
- src/month.jsx
- test/month_test.js
I want to click the calendar day with multiple months in the Selenium test. Currently, there is no way to specify the element with the text in `react-datepicker__current-month`. Tests using text are fragile.
So I added 'aria-label=month-2018-09` attribute on the element of the month, following the elements of the day.
> Add aria-label to month.

- src/stylesheets/datepicker.scss
An extra 70px of padding is turning up on the time picker in the latest versions of Firefox, Chrome and Safari, this is forcing hte time select to be clipped and not displayed properly. This is related to issue #1489 https://github.com/Hacker0x01/react-datepicker/issues/1489
> Fix the spacing on the time picker

- docs-site/bundle.js
- docs/datepicker.md
- docs/index.md
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/calendar_test.js
- test/date_utils_test.js
- test/datepicker_test.js
Moment, which ultimately consumes the offsets, accepts either numbers or strings. So I updated the relevant prop types and added a few tests with offsets specified as strings.
> Allow utcOffset to be specified as a string

- src/index.jsx
- test/datepicker_test.js
Sample usage:
```javascript
import React from "react";
import DatePicker from "react-datepicker";
class DateRangePicker extends React.Component {
constructor(props) {
super(props);
this.state = {
open: false,
selectsStart: true,
selectsEnd: false,
selected: null,
startDate: null,
endDate: null
};
this.handleChange = this.handleChange.bind(this);
this.openCalendar = this.openCalendar.bind(this);
this.closeCalendar = this.closeCalendar.bind(this);
}
handleChange(date) {
if (this.state.selectsStart) {
this.setState({
selected: date,
startDate: date,
selectsStart: false,
selectsEnd: true
});
} else {
this.setState({
open: false,
selected: date,
endDate: date,
selectsStart: true,
selectsEnd: false
});
this.props.onRangePicked &&
this.props.onRangePicked(this.state.startDate, date);
}
} …
```
> Makes open state controllable through props

- docs/datepicker.md
- docs/index.md
- docs/time.md
- src/calendar.jsx
- src/index.jsx
- src/time.jsx
```
type ReactNode = ReactChild | ReactFragment | ReactPortal | string | number | boolean | null | undefined;
```
PropTypes.node is more appropriate for this prop.
related change to DefinitelyTyped: https://github.com/skvale/DefinitelyTyped/commit/894260b8e7fd107c7f372f4623ff4c962c1229c8
> Change todayButton to PropTypes.node.

- src/calendar.jsx
- src/time.jsx
- test/time_format_test.js
Hi, I've come up to a problem with Time component when using complete custom stylesheet - the selected time wasn't centered properly because of some hardcoded height values, so I made some tweaks to calculate the scroll needed in order to have selected time scrolled in the middle of the list.
basically it works like this pseudocode:
`listScrollNeeded = centerLi.offsetTop - (list.height/2 - centerLi.height/2)`
where `list` is previously added ref to `<ul>` and `centerLi` is newly added ref to `<li>`, which matches hours and minutes of the `selectedDate` prop, or fallbacks to at least `currH` (either `selectedDate` or `new Date()`) - just like before.
Was also wondering about adding tests, but supposedly, enzyme doesn't support DOM properties (like `height`, or `scrollTop`), as it doesn't …
> Calculate initial scroll of TimeSelect

- docs-site/src/examples.scss
Using `position: sticky` if supported for more always visible navbar
> More convenient examples navigation

- src/index.jsx
- src/popper_component.jsx
Adds the ability to send props to the `Popper` component
> Allow passing popperProps. Fixes #1525

- src/index.jsx
- test/timepicker_test.js
This PR resolves #1394 
If anything is wrong or needs improvements, please tell me.
> Add verification to time picker when shouldCloseOnSelect is false

- docs-site/bundle.js
- src/index.jsx
It will fix the blur event. Blur is called only in the `setOpen` and it has new parameter `skipSetBlur`. The blur is called when `open===false` and `skipSetBlur===false`. The issue was noticed when we tested our redux-form forms.
After calendar close the `inputValue` is set to `null`
> Fix blur events

- docs-site/bundle.js
- docs-site/src/examples/on_blur_callbacks.jsx
- src/index.jsx
Fixes an issue where onBlur was firing two times (#1547), one of which had no event associated with it. Also fixed demo site example for the same event.
> onBlur Fix

- README.md
The README had an incorrect prop name that gave me a bit of confusion until I looked further in the docs folder. Hopefully this saves someone else a couple minutes of digging.
> Fix prop name typo in README

- src/date_utils.js
- test/date_utils_test.js
Fix for https://github.com/Hacker0x01/react-datepicker/issues/1563.
Instead of an uncaught exception, the error is handled simply as a `false` when considering if the dates are in range.
> Fix range error

- docs-site/src/examples/locale.jsx
It's confusing because the default date-fns version is not compatible. Added a few lines of comments about how to install the compatible version.
> Update locale example, clearify date-fns version

- package.json
- test/calendar_test.js
My bundler gets confused and tries to get `lib.js` instead of `lib/index.js`.
Most packages use `lib/index.js` _https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/package.json#L5_, and pointing to an actual file is a standard.
> Updating main field in package.json and fixing january test

- docs-site/src/examples/locale.jsx
Just a small addition to improve the docs.
I started to use react-datepicker these days. I tried to reproduced the code of the locale example, and I didn't have success. Seems like other people faced the same problem (https://github.com/Hacker0x01/react-datepicker/issues/1643). I think this can improve the docs.
> (docs) improve locale section

- docs-site/src/example_components.jsx
- docs-site/src/examples/locale_without_global_variable.jsx
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/calendar_test.js
This lets you set a datepicker's locale without registering it in a global variable first. Instead, you can now just pass the locale object directly. This matches the way all date-fns functions accept locales. https://date-fns.org/v2.0.0-alpha.27/docs/I18n
It's backwards-compatible, tested, and comes with an example. Closes #1658.
> Locales without globals

- docs-site/src/example_components.jsx
- docs-site/src/examples/strict_parsing.jsx
- docs/index.md
- src/date_utils.js
- src/index.jsx
- test/date_utils_test.js
Fixes #1655 
The date value entered in the input should be parsed strictly based on the provided `dateFormat`. For example, the provided `dateFormat` is `MM/dd/yyyy`. When changing the date value in the input from `03/04/2019` to `03/04/20`, one would expect the date picker to reject `03/04/20` as a valid date value since it does not conform to the date format. However, the date in the calendar is updated to March 4th, 2020 as it accepts `20` as a valid year even when the format has a 4-digit year.
This change is to make date parse conform strictly to the provided date format.
> Make date parsing conform strictly to the date format.

- src/inputTime.jsx
Bug
https://github.com/Hacker0x01/react-datepicker/issues/1670
Resolution
Marked the Input as "Required" in case of showTimeInput=true.
> Fix for Issue #1670

- src/date_utils.js
Removed an unused "dateformat" parameter from getMonthShortInLocale that was never sent when called. The unused variable was taking the value of the "locale" variable, creating a bug when setting a locale with the month/year picker.
> removing unused dateformat parameter from getMonthShortInLocale 

- .babelrc.js
- package-lock.json
- package.json
- rollup.config.js
- src/inputTime.jsx
Fixes #1606.
Before there were all packages of date-fns included into the bundles. 
Now I added a filter as @glebtv suggested (it doesn't look fine, I think, but it works), and whole packages of data-fns are marked as externals by rollup.
Also I noticed that lodash was imported fully because of 'isEmpty' script. I'm not sure that it is actually needed so I removed it.
And, last thing, I found out that prop types weren't removed during building. So I removed them.
Before:
```
./dist:
22K react-datepicker-cssmodules.css
20K react-datepicker-cssmodules.min.css
20K react-datepicker.css
172K react-datepicker.js
18K react-datepicker.min.css
172K react-datepicker.min.js
./es:
840K index.js
./lib:
841K index.js
```
Now:
```
./dist:
22K react-datepicker-cssmodules.css
20K …
```
> Drastically decrease size of the bundles

- docs-site/src/examples/date_range.jsx
I want to make it impossible to select the end date before the start date when specifying the period.
If I add `minDate={this.state.startDate}`, `handleChange` method is easier.
like this.
> Refactor date_range example

- src/time.jsx
- yarn.lock
Within the `Time` component, the height of the container is calculated in the `render` method. This is not bad practice, but in this specific scenario, `monthRef` is null because React calls `componentDidMount` on *children* first, not parents. 
As updating the prop of a component does not re-render the DOM, there are two ways we can solve this issue:
1. Put the height in the component's state
2. Implement `componentWillReceiveProps`
In this PR, I chose option 1. It should fix #1596.
> Fix the time container whitespace issue

- src/date_utils.js
Actually:
```const scope = window || global;``` 
causes an error if window is not defined, so there is a need to validate typeof window
> Fixes SSR (window is not defined)

- docs-site/bundle.js
- src/date_utils.js
- test/date_utils_test.js
Fixes issue https://github.com/Hacker0x01/react-datepicker/issues/1765
Easier to read the logic in `isMonthinRange`, and grays out the appropriate months in month picker.
> Month picker minDate disabled state (issue #1765)

- README.md
In the documentation it points to import directly from `import {registerLocale, setDefaultLocale} from DatePicker;` which generates a `Module build failed` error.
This is solved by pointing to the main module `" react-datepicker ";`. I take this opportunity to improve the doc section as well.
> Localization integration with the correct module

- docs-site/src/example_components.jsx
- docs-site/src/examples/locale_with_time.jsx
- src/calendar.jsx
- src/time.jsx
- test/time_format_test.js
Up to now, the time select did not use locale for formatting, even if using `p+` formatting tokens. This PR aims to fix this bug.
Before:
In the picture below, you can see that even using `timeFormat="p"` and `locale="pt-BR"` the options in the time select are still using the default locale (`en-US`) AM/PM style.
After:
Now, it's respecting the format of the locale (`pt-BR`) 24-hour style.
> Format time select based on locale

- src/index.jsx
- test/datepicker_test.js
I thinks it logical mistake – change date to the one that was entered if it is out of bounds. And `isDayDisabled` includes check `isOutOfBounds`.
Fix for https://github.com/Hacker0x01/react-datepicker/issues/1713
> Fix not working max and min date when change it manually (issue 1713)

- src/stylesheets/datepicker.scss
Since PR #1437, the close button (that appears when the prop `isClearable` is passed) is not vertically centered anymore, as becomes especially clear with large font sizes for the input. This PR should fix that (and while at it, it cleans&reorders the relevant rules a bit for clarity).
> Vertically center the 'close icon' again.

- docs/datepicker.md
Incorrect `dateFormat` and `dateFormatCalendar` defaults. See https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx
> Incorrect dateFormat default values

- src/month.jsx
When datepicker is rendered with `showMonthYearPicker` prop and an option is selected, then `onChange` method is called, but without the event as second param. Instead it is `undefined`.
> Pass event as second param when onChange is called at monthYearPicker

- src/date_utils.js
- src/day.jsx
- test/date_utils_test.js
Prior to this change, dates that were passed in via the excludedDates array prop used only had the same CSS class as all other disabled days, `react-datepicker__day--disabled`. 
This made it difficult to target only excluded days with custom styles. I've added an extra CSS class to these days, `react-datepicker__day--excluded`, which makes custom styling easier.
- One of the existing tests was already failing on a fresh checkout of `master`, `DatePicker should not manual select date if after maxDate`.
- I didn't commit them, but `/docs-site/bundle.js` and `/docs-site/style.css` were changed a lot by the build script, I assume by `prettier`. If you want me to go ahead and commit those as well, just let me know (I'm assuming you update the docs site as part of release).
> Added a specific css class to excluded dates

- .travis.yml
- package.json
- server.js
- webpack.docs.config.js
- yarn.lock
Fixes:
- That a dev build was included in the docs
- That the docs were not build on Travis and a clean version was deployed: reactdatepicker.com
- Fixes yarn start
> feat: docs optimizations

- docs-site/src/examples/render_custom_header.jsx
Custom Header example is breaking on month change because the month is being passed as string (for e.g. May, June) instead of month index. Fixed it and working fine now.
> Fixed custom header example issue when month changed

- src/date_utils.js
- test/date_utils_test.js
See https://github.com/Hacker0x01/react-datepicker/issues/1867 for more details.
This simply sets the `startDate` and `endDate` to have times of 12:00AM and 11:59PM, respectively, before checking if `date` is within `startDate` and `endDate`.
> Fix keyboard bug selecting last day on calendar

- src/stylesheets/datepicker.scss
Some of our users were having an issue with the date & time selector. On Windows the width of the scrollbar causes the time to wrap. This commit fixes that.
See before:
And after:
> Stop time-list-item wrapping on windows

- src/day.jsx
- test/day_test.js
When I applied styling that shows disabled dates as grayed out, my accessibility checker of choice ([React-axe](https://github.com/dequelabs/react-axe)) warned about insufficient color contrast. 
With the aria-disabled attribute with the right value, the warning is gone.
> set aria-disabled attribute when day is disabled

- src/calendar.jsx
- test/calendar_test.js
PR to fix #1890 
It adds a wrapping div to have a ref to give to "react-onclickoutside", we have to do so if we don't want to delegate to "Container" to forward the ref.
> Fix find dom node warning

- src/index.jsx
I'm seeing that when a custom input does not implement the classname property or does not have a specified classname, the value is undefined, resulting in `undefined` as a classname on the output.
Issue: #1897 
Used classnames to handle undefined classname
> [Fix] Fix classname undefined on custom inputs

- src/month_dropdown_options.jsx
- test/month_dropdown_test.js
Fixes a typo in the MonthDropdownOptions class where the BEM modifier class for the selected month was not being applied properly.
> Fix typo in month dropdown selected option class

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/noAnchorArrow.js
- src/calendar.jsx
- src/calendar_container.jsx
- src/index.jsx
- src/popper_component.jsx
- test/datepicker_test.js
Addresses #1029 
This adds a new prop called `showPopperArrow` and corresponding example to the docs.
The property defaults to `true` to ensure backwards compatibility. Setting it to false results in the popper anchor arrow not being displayed.
> Add showPopperArrow prop

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/multiMonthPrevious.js
- src/calendar.jsx
- src/index.jsx
- test/multi_month_test.js
Opening this PR based on #1007 with current codebase.
> Adding showPreviousMonth property

- package.json
This sets the package.json field sideEffects to false. This allows for better tree shaking by downstream consumers, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free for more information.
I skimmed over all included files and I did not see anything that would count following webpack's definition of tree shaking.
> Declare package side effect free

- src/calendar.jsx
- src/date_utils.js
- test/date_utils_test.js
Check prev/next year instead of month when showMonthYearPicker is set.
> fix: Prev/next buttons when using showMonthYearPicker

- src/index.jsx
I wanted to apply aria-labelledby HTML property to the component, but there was no related props. This will allow us to pass aria-labelledby for the text field as ariaLabelledBy.
This is intended to be an optional props. Not specifying it should not cause any changes to the existing component.
> Added ariaLabelledBy property for screen-reader support

- docs/datepicker.md
I updated the documentation and added ariaLabelledBy to the available props list. Sorry for my repeated mistakes; I should've done this in the first PR.
> Add ariaLabelledBy to the list of available props

- package.json
Fixes #1967
I've included the css files in the sideEffects for webpack.
> Don't mark .css files as side effect free

- src/date_utils.js
This is alternative to #1906
Fixes same problem but with different approach - this keeps bundling longFormatters but avoids the `__esModule` problem
> Use module version of longFormatters

- docs-site/src/examples/dateRange.js
Days in datepicker get highlighted when changing the start date but not when changing the end date. Related to this issue: https://github.com/Hacker0x01/react-datepicker/issues/1251
> Highlight days when changing the end date

- src/calendar.jsx
Currently, those buttons don't have any ARIA labels, which is a Section 508 Requirement.
> Add Aria Labels to the next and previous navigation buttons

- package.json
- src/calendar.jsx
When the renderCustomHeader prop is present, always use the custom header. All the order times, pick the right header based on month/quarter picker properties.
Also add year functions to the custom header render props.
> Render custom header for month/quarter pickers.

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/customTimeInput.js
- docs/index.md
- docs/inputTime.md
- package.json
- src/calendar.jsx
- src/index.jsx
- src/inputTime.jsx
- test/time_input_test.js
Added a `customTimeInput` prop of PropTypes.element type to render a custom input in place of the default one used in the inputTime component. This enable the user to implement a custom time input control with low effort.
We already use this edited version of react-datepicker in production because our end users are used to work with a smarter time input we developed. We also have to support Safari which doesn't work with stardard date time inputs.
This doesn't affect other behaviours and should be easy to document!
Thanks!
> Custom time input element with customTimeInput prop

- docs/datepicker.md
- docs/index.md
- src/index.jsx
#2031 
By default, react-onclickoutside will not register clicks on the scrollbar if the users scrollbars are constantly visible (an OS setting).
The property is available to disable but it makes sense to enable this by default.
I wanted to create a test case for this, but testing onClickOutside on a scrollbar in a headless browser is really REALLY difficult.
> excludeScrollbar prop for react-onclickoutside

- docs-site/src/examples/customClassName.js
The "Custom class name" example in the documentation was a duplicate of the "Custom day class name" example.
> Custom class documentation example fix

- src/calendar.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/datepicker_test.js
Props for controlling aria-labels/aria-label prefixes were missing in the parent components
> Dynamic aria labels fix

- src/date_utils.js
- src/week.jsx
Leverage date-fns getWeek function to get correct week numbers. 
This solves problems with wrong week numbers for some non us locales like danish (da).
For example 1 Jan 2021 is in week 53 but is reported as 1.
This also fixes #1878
> Fix week numbers for non us locales.

- src/day.jsx
- src/month.jsx
fixes #2095 
role "option" changed to "button", removed unnecessary "listbox" role
> Updated the aria role attributes for benefit of screenreaders

- CONTRIBUTING.md
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/calendar_test.js
fixes #2094 
As you navigate through months with "previous month" and "next month" buttons, the preselection is applied to that calendar month.
This way a keyboard user always has a way to tab back into the calendar days.
**note**
while working on this fix, I was unable to run the local example page in IE11.
This was true for the master branch as well as my feature branch.
I'm confident it's unrelated to my code, but I could not figure out why this was happening.
> Feature/2094  month navigation day selection

- src/index.jsx
- test/datepicker_test.js
Hello. For now date picker purges away selected time. This should not happen when it used without time picker.
I see that today overall code base looks over complicated. So I think you are going to rewrite it completely. Please keep date and time values separately and call `onChange` with merged value.
> Do not change time if date picker only

- docs-site/src/components/App/index.js
- docs-site/src/components/Examples/index.js
**Description of PR**
* currently on document website on click to example navigation anchor tag it's not scroll to particular example. which is inconvenient for developer to see the things and utilise the documentation properly and efficiently. this PR will solve this issue and give a nice and smooth scrolling to reach particular example.
* fixed bug of browser in search page. user can now search for text and it will navigate to the found text inspite of staying at the top of page.
* fixed bug of when user doble click on page it navigate it to top.
**Type of PR**
**Relevant Issues**  
Fixes #2106, Fixes #2109 
**Checklist**
**Screenshots**
<br>
<br>
<br>
<br>
<br>
Thanks & Regards,
Binu Kumar
> fixed search in page, navigation to example and scroll back to top on second click.

- docs/index.md
- src/calendar.jsx
- src/index.jsx
This updates the prop type and docs for `previousMonthButtonLabel` and `nextMonthButtonLabel` to allow any renderable content to be passed in. For my use case, I'm passing in some custom svgs for the icons. The code already supports this use, it just needs the updated prop type definitions.
> Allow React elements as button labels

- src/month_dropdown.jsx
- src/month_dropdown_options.jsx
- src/month_year_dropdown.jsx
- src/month_year_dropdown_options.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
- yarn.lock
I have removed unused refs that were causing crashes for multiple users in multiple variations of datepicker. Please see the screenshots below:
**Before**:
**After fix:**
These are the issues which were reported for this:
https://github.com/Hacker0x01/react-datepicker/issues/1953
https://github.com/Hacker0x01/react-datepicker/issues/2129
https://github.com/Hacker0x01/react-datepicker/issues/2118
https://github.com/Hacker0x01/react-datepicker/issues/2093
https://github.com/Hacker0x01/react-datepicker/issues/2088
https://github.com/Hacker0x01/react-datepicker/issues/2023
https://github.com/Hacker0x01/react-datepicker/issues/1953
https://github.com/Hacker0x01/react-datepicker/issues/1939
> removing unused refs

- src/index.jsx
- test/datepicker_test.js
Return the preventFocus state to false after closing the calendar popper with Escape key. This issue prevented the calendar popper to open on the following navigations to the input with the keyboard.
It solves #2146
> Reset preventFocus after closing the popper with Escape.

- src/calendar.jsx
`PopperComponent` passes `arrowProps` to `Calendar` and `CalendarContainer` is expecting `arrowProps`. However, `Calendar` does not pass `arrowProps` to `CalendarContainer` which prevents the props (ref and style) to not be propogated.
> Pass arrow props to CalendarContainer

- docs-site/src/components/Example/index.js
- docs-site/src/components/Examples/examples.scss
- docs-site/src/components/Examples/index.js
- docs-site/src/examples/portalById.js
- src/index.jsx
- src/popper_component.jsx
- src/portal.jsx
Using createPortal from ReactDOM the popper is added in a portal and displayed outside of Root Element in order to avoid overflow
Docs added
Unit tests are not added because when unit testing the portal is rendered inside by default
> Render popper in a Portal by Id to avoid overflow of parent

- docs/index.md
- src/index.jsx
- test/datepicker_test.js
`focusSelectedMonth` works like `inlineFocusSelectedMonth`
but doesn't depend on `inline`, nor `monthsShown`.
It  solves https://github.com/Hacker0x01/react-datepicker/pull/1541#issuecomment-569304221
> Replace `inlineFocusSelectedMonth` with `focusSelectedMonth`

- src/stylesheets/datepicker.scss
- src/year.jsx
- test/year_picker_test.js
Feature for [#2162](https://github.com/Hacker0x01/react-datepicker/issues/2162) I've noticed that this behavior wasn't implemented. 
Added some logic to add class.
Added class name to styles the same way as for months.
Covered with a test.
Also, I noticed this issue [#2167](https://github.com/Hacker0x01/react-datepicker/issues/2167) I think I could check this. Maybe #2167 needs to add a new prop to choose where to show selected year(beginning or end of the calendar) ?
> Add selected class for year picker - Feature #2162

- src/index.jsx
- test/datepicker_test.js
1. Updates the onChangeRaw callback such that it fires on all changes, including when a date is selected from the calendar. It would be useful to users if there was a callback that fires on every change. For example, I am performing date validation for user error messaging and it's necessary to perform that validation on every change. 
2. Updates the onSelect callback so it only fires for a calendar date selection. Currently, onSelect and onChange fire on the same events. It would be helpful to differentiate the two. This change also matches the behavior to the docs.
Fixes #1951
> Update onChangeRaw and onSelect - Fixes #1951

- src/stylesheets/datepicker.scss
Fix for rendering issue on time section:
Bug visible on Chrome: Version 81.0.4044.138 (Official Build) (64-bit)
> border bottom right time section

- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
When using an inline date picker, you can navigate the days with the keyboard but they do not style correctly so it doesn't appear that it is working
> remove inline check for keyboard selected

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/selectsRange.js
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/datepicker_test.js
- test/day_test.js
Tried to implement one datepicker for range. Thanks to the guys from #584 discussion, their examples are the base for this PR. I hope this will help.
> Range on one datepicker for #584

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/closeOnScroll.js
- docs-site/src/examples/closeOnScrollCallback.js
- src/index.jsx
- test/datepicker_test.js
Add closeOnScroll prop to enable. The prop accepts either a boolean or a function. If true, the datepicker will be closed when the document is scrolled. If function, then it executes the function to see whether the datepicker should be closed or not.
> Add closeOnScroll prop

- src/date_utils.js
- test/date_utils_test.js
When using the yearpicker the navigation is disappearing while clicking on next. The user can´t get to the initial state.
> fix(date_utils): fixing navigation on yearpicker

- src/calendar.jsx
- src/stylesheets/datepicker.scss
- src/time.jsx
- test/calendar_test.js
- test/timepicker_test.js
- Fix border radius issues when using date + time and time only
- Fix next month button position for date + time
Screenshots of the issue I changed the `$datepicker__background-color` to red to better highlight problems.
> Fix border radius issues

- README.md
- src/calendar.jsx
- src/month.jsx
- test/month_test.js
This PR:
- Allows the user to pick a month using keyboard only
- Adds test coverage for recent changes
- Updates readme with new keybinds
- resolves #2078
> Adds keyboard navigation for month picker

- src/month.jsx
- test/month_test.js
The prop monthClassName was been already passed by its parent,
the calendar component, but it wasn't used at any time. fix #2407
> add & call 'monthClassName' to use its value

- package.json
As described in #2343, applications created with Create-React-App do not recognize CSS modules unless the module's filename is in the format ```filename.module.css```.
This PR changes the scripts `css:modules:prod` and `css:modules:dev` in `package.json` from redirecting the output of node-sass to a file to instead piping to tee and then to two files, one with the original filename and one with the CRA recognized filename.
**Original**
"css:modules:prod": "node-sass --output-style compressed src/stylesheets/datepicker-cssmodules.scss **> dist/react-datepicker-cssmodules.min.css"**
**New**
"css:modules:prod": "node-sass --output-style compressed src/stylesheets/datepicker-cssmodules.scss **| tee dist/react-datepicker-cssmodules.min.css dist/react-datepicker-min.module.css"**
> Copy generated css module to file with filename format CRA expects

- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
This fixes a big issue we were having -- the inline DatePicker at the bottom of our home page was grabbing focus upon page load.  This caused an accessibility issue where, if the user pressed the Tab key, they were unexpectedly on the footer instead of on the first clickable link.  
I made this a very narrow fix to only change the one line in day.jsx that was causing the issue, but it required a lot of prop drilling to get down to it.  I added a couple of unit tests to test when inline=false and =true.
> fix autofocus on selected day when inline prop is true

- src/calendar.jsx
- src/day.jsx
- src/month.jsx
- src/week.jsx
- test/datepicker_test.js
- test/day_test.js
This PR does two things. 
1. Solves #2284 . As described in issue, keyboard focus does not update in inline version. By updating preSelection date when changing date by click the keyboard date and selected date will be in sync.
Before:
After:
2. While solving 1, i broke a the test: "should not switch months in inline mode when a day is clicked". After looking into it i saw that the test is not actually testing if the month is switched or not. But i found the case interesting. Firstly, i mean that in default inline case, if you click on a outside-month day, it should change month (and it currently does). Secondly believe it should be the case if its multiple months shown. The current version will switch between months when clicking on an outside-month day (the inline design of two months …
> Feature hide duplicate days

- docs-site/src/components/Examples/index.js
Had a hard time figuring out what the props were for the popper stuff until I discovered popper was a separate component.  So, I added a description that contains a link to the documentation for the popper.
> Added link to docs for popper component

- docs-site/src/components/Examples/index.js
Hello! This is an awesome project, and recently I wanted to suggest its use, with an example from the docs site. Unfortunately, there was no easy way to share a link to a particular example, and I instead manually created `https://reactdatepicker.com/#example-input-time` after looking into the markup.
I notice that anchor click behavior is overridden in order to animate the scroll. This looks really clean, but we lose the shareable links. With [`window.history.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) we can update the address bar without causing a page refresh. And using `replaceState` instead of `pushState`, we don't clutter browser history when the user navigates between examples.
Additionally, I noticed that when scrolling an element we …
> Show links to examples and scroll an example to the top

- src/time.jsx
Fixed 'Elements that have scrollable content should be accessible by keyboard' WCAG violation for the scrollable time panel.
Before the fix "axe" chrome plugin was showing the following error: 
After the fix "axe" chrome plugin was not showing "Elements that have scrollable content should be accessible by keyboard" and it is possible to scroll time panel
I have followed the recommendation from dequeuniversity: 
https://dequeuniversity.com/rules/axe/4.0/scrollable-region-focusable?application=AxeChrome
> Fix for accessibility issue 'Elements that have scrollable content should be accessible by keyboard' for scrollable time panel 

- src/month.jsx
Fixed bug introduced in version 3.2.0 (PR #2389).
The fill method was used, but it is not supported in IE.
The method was removed and replaced with different syntax that gets transpiled and works in IE.
Fixes #2577
> Replace fill method with different syntax for IE compatibility

- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/datepicker_test.js
When the autoFocus issue of the inline version was fixed in v3.3.0 ([this commit](https://github.com/Hacker0x01/react-datepicker/commit/d09a14dc3d7e61d59069cd51acc9e78bc822524e)), the keyboard navigation stopped working after switching between months with ArrowLeft/Right/Up/Down, PageUp/Down, End/Home keys.
With this PR the autoFocus issue remains fixed, but keyboard navigation got restored
fixes #2578
> Fix keyboard navigation in inline version

- CONTRIBUTING.md
The `yarn install` shall precede `yarn build`, that's all...
Oh, and using ordinals in markdown ordered list is not needed, it just needs to be number, so I changed the ordinals to `1.` everywhere, it is easier to maintain -- there is no need to reorder when changed.
> docs: order of "Getting setup" in CONTRIBUTING.md

- docs/month_year_dropdown_options.md
- src/month_year_dropdown.jsx
- src/month_year_dropdown_options.jsx
Hello, always thank you for maintaining this nice library.
I found that a `locale` prop is not used in `MonthYearDropdownOptions` component.
It might be great if the component has a `locale` prop like other components.
As-is 
To-be
> Add locale props to MonthYearDropdownOptions

- docs-site/src/examples/weekNumbers.js
- src/date_utils.js
- src/week.jsx
- test/date_utils_test.js
The current `showWeekNumbers` return wrong result because (from `getWeek` date-fns function).
Example : 
`console.log(dfgetWeek(new Date())); // 2, it's wrong, want 1`
`console.log(dfgetWeek(new Date('2020-01-01'))); // 1, it's wrong, want 53`
We need to use `getISOWeek` function for return iso result : 
`console.log(getISOWeek(new Date())); // 1, good`
`console.log(getISOWeek(new Date('2020-01-01'))); // 53, good`
From #2572
> Fixing wrong weekNumber by using getIsoWeek

- src/stylesheets/datepicker.scss
Gents, a quick fix with this one, a well-shot photo will speak more words than I ever could type in here, so here are the screenshots 
🙇🏼
> fix(Layout): Fix Input Time input width being cut off

- src/calendar.jsx
- test/calendar_test.js
Custom header now gets rendered for every month when monthsShown prop > 1;
Introduced customerHeaderCount prop to be able to conditionally render and adapt content in custom header, e.g. manipulate the displayed month value based on the date and customHeaderCount props
fixes #2351
> Display custom header when monthsShown prop is bigger than 1

- package.json
- yarn.lock
This will only fix the peer-dependencies of this package.
~Installing this package will still fail with react@17 and npm@7. We still depend on react-onclickoutside, which also needs to be updated to support peer-dependencies of react@17.~ https://github.com/Pomax/react-onclickoutside/issues/346 (done)
react-popper@1 doesn't support react@17 either, so this is also blocked by the react-popper@2 upgrade #2686 .
Addresses #2677
> Update react & react-dom peer-dep to support 17.x

- .husky/pre-commit
- test/date_utils_test.js
- test/datepicker_test.js
- test/month_dropdown_test.js
- Comment out failing test
- Re-enable a disabled test that should just work
- Fix precommit to the original behavior
> Fix build and some minor improvements

- docs/datepicker.md
In #1181, the feature was added, but it was not added to the documentation.
> Add documentation for preventOpenOnFocus

- docs-site/config-overrides.js
- docs-site/src/examples/configurePopper.js
- package.json
- src/index.jsx
- src/popper_component.jsx
- src/stylesheets/datepicker.scss
- src/stylesheets/mixins.scss
- yarn.lock
This PR updates `react-popper` to its latest version while addressing the visual regressions the update caused. This required special care to the display of the arrow.
There's a lot of noise coming from the linting defined as a precommit hook, sorry about that.
This PR should also fix #2653 by setting an alias for react in the docs, see `docs-site/config-overrides.js`.
Thanks to @czabaj  and his PR #2686 that was the starting point of this PR.
> Upgrade react-popper to v2.x

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/renderCustomHeaderTwoMonths.js
- src/calendar.jsx
- test/calendar_test.js
When rendering a custom header and displaying more than one month, like this, it becomes possible to sync the month displayed in header and in calendar
fixes #2981
> Add monthDate to renderCustomHeader render props function

- src/stylesheets/datepicker.scss
As detailed in #3009, `Popper` complains about `margin-*` statements in the CSS for the pop-up date selector. Changing these to `padding-*` calls silenced the error and gave the same visual effect in my testing.
I'm not sure how to write a test for this, but I'm happy to do so if anyone can point me in the right direction.
Closes #3009
> Fix Popper CSS warnings

- src/index.jsx
- test/datepicker_test.js
Fixes #3015
The locale we defaulting to 0, via the default props. This meant that 0 was passed all the way down to the function `getStartOfWeek`. The result of this is that the week will always start on a Sunday, ignoring the locale that is set.
The solution is just to make this undefined, which will then use the correct locale version if its set.
This should be fine as any uses where the number is overridden is still passed down, and those without a locale set will be defaulting to the US, which is 0 (sunday)
> Fix start of week not using the registered locale

- src/date_utils.js
Without this change, VS Code complains:
"Type annotations can only be used in TypeScript files."
This invalid syntax worked because it was considered to be Flow syntax by Babel. Flow type-checking is not enabled for date_utils.js, so it also passed type-checking (`yarn flow`).
> Fix invalid syntax

- docs/datepicker.md
This PR adds `focusSelectedMonth` in date-picker props documentation
> fix(doc): add focusSelectedMonth docs props

- src/stylesheets/datepicker.scss
* Set explicit 0 width for navigation icon span container to render consistently on Safari
Chrome, Firefox, Edge, and other browsers implicitly sets the navigation button's width to 0 (collapsed) due to the combination of absolute and relative positioning. Safari, on the other hand, calculates a width based on left/right and other values, which leaves the icon outside of the button's hidden overflow. Setting an explicit width of 0 does not change rendering on other browsers, but helps Safari render the icon as expected.
Tested on Chrome, Firefox, Edge, Opera, and Safari.
**Original navigation rendering in Safari:**
**Updated navigation rendering in Safari:**
> Bugfix - Navigation button icons are hidden in Safari

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/inlineVisible.js
- docs-site/src/examples/withPortalById.js
- src/index.jsx
- test/datepicker_test.js
* providing `portalId` when used in conjunction with `withPortal` will render the portal version calendar in a ReactDOM portal (using the Portal component).
* Removes confusing logic of inline portals. Inline always renders the calendar. Providing the `withPortal` prop only wrapped the calendar in the portal class.
* Adds documentation for portal versions rendered with ReactDOM portals.
* Removes documentation for InlinePortal which was not used.
* Adds documentation for toggling an Inline calendar.
* Tests inline prop will ignore withPortal prop
* Tests withPortal and portalId will render a portal version with the portalId
> Uses react dom portals for portal version when portalId is provided

- test/show_time_test.js
Hi,
This pull request fixes an issue where the tests under "Time Select Only" would always pass regardless of whether the property "showTimeSelectOnly" is true or false.
> Fix 'Time Select Only' tests

- package.json
- yarn.lock
Related to issue https://github.com/Hacker0x01/react-datepicker/issues/3227
react-onclickoutside recently pushed an update to support shadow-dom interactions. This update is working successfully, however when npm publishing using react-datepicker as a dependency it is not pulling in 6.12.0 version, instead it is respecting the yarn-lock and keeping version 6.10.0 which causes the resulting package not to support shadow-dom.
Update react-onclickoutside to 6.12.0
If you want to create an npm package that uses react-datepicker, you will not be able to use the latest version of react-onclickoutside which support shadow dom.
Related react-onlickoutside PR for supporting shadow-dom Pomax/react-onclickoutside#363
> chore: updated react-onclickoutside support shadow-dom

- src/date_utils.js
- test/date_utils_test.js
Argument `minDate` suggest that date should be equal or higher than it, but previous version wasn't accepting equal date. This solves the issue of not being able to input `minDate` via keyboard when `dateFormat` array was set.
> Fix isValid helper so it accepts dates equal to minDate (#3262)

- docs/datepicker.md
- docs/popper_component.md
- docs/portal.md
- src/index.jsx
- src/popper_component.jsx
- src/portal.jsx
- test/datepicker_test.js
When passed a shadow root through the portalHost prop, all portals will be created as children of that shadow root. This enables style encapsulation for consumers that are using the shadow DOM.
Resolves #3312
> Added portalHost prop to DatePicker component.

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/excludeDateIntervals.js
- docs-site/src/examples/includeDateIntervals.js
- docs/datepicker.md
- docs/index.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/date_utils_test.js
- test/datepicker_test.js
- test/day_test.js
Added properties to exclude and include dates from one or many intervals.
This is intended to make it easier to define these ranges when there are a large number of dates included (eg: a year or more), since it only needs pairs of start and end dates, instead of the array of all the specific dates needed for excludeDates and includeDates.
The term "intervals" is kept instead of "range" because both props need to be fed with intervals as defined by date-fns. It could be changed, however, if needed.
> Add ability to exclude and include date intervals

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/selectsRangeWithDisabledDates.js
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/day_test.js
By default, disabled dates are not considered for highlighting when hovering over an end date when range selection is enabled (the disabled Day component does not get the `react-datepicker__day--in-selecting-range` class).
This PR adds a prop `selectsDisabledDaysInRange` for changing this behavior and allow for disabled dates to be highlighted on range hover.
By default `selectsDisabledDaysInRange` is set to false so the current functionality is maintained.
Tests and an example for using the prop were added as well.
> Add selectsDisabledDaysInRange prop to allow highlighting disabled dates in range

- .github/workflows/test.yml
- test/day_test.js
- test/month_test.js
- test/time_input_test.js
Ref https://github.com/Hacker0x01/react-datepicker/issues/3325
Skipping 2 tests results in running more tests overall:
- Before: 468
- After: 625
4 tests appear to be broken in the set of tests that were skipped before. Skipping this for now too, but need to investigate if the test or functionality is broken.
> Disable tests that are skipping other tests

- src/day.jsx
- src/month.jsx
- src/year.jsx
- test/day_test.js
- test/month_test.js
- test/year_picker_test.js
**What does this PR do?**
This PR adds aria-current to the element which represents the current date/month/year.
Actual Result:
Narrator Behaviour: "Choose Wednesday September 29, 2021, button"
Expected Result:
Narrator Behaviour: "Choose Wednesday September 29, 2021, **current date**, button"
Related Issue
#3229
> Accessibility: current date should use aria-current="date"

- src/day.jsx
- src/month.jsx
- src/month_dropdown_options.jsx
- src/month_year_dropdown_options.jsx
- src/time.jsx
- src/year_dropdown_options.jsx
- test/day_test.js
- test/month_dropdown_test.js
- test/month_test.js
- test/month_year_dropdown_test.js
- test/time_format_test.js
- test/year_dropdown_options_test.js
What does this PR do?
This PR adds aria-selected to the element which represents the current selection, i.e. has the `*--selected` class
It also groups up some of the tests into describe blocks to reduce code duplication and show that some tests are related
Actual Result:
Narrator Behaviour: "Choose Wednesday September 29, 2021, button"
Expected Result:
Narrator Behaviour: "Choose Wednesday September 29, 2021, button,  **selected**"
Related Issue:
#3160
> VPRB-221  Accessibility: [react-datepicker] add aria-selected to current selection

- src/day.jsx
- test/day_test.js
Existing test cases missed to check a scenario when out of bound day is more than one week (i.e. when fixedHeight or peekNextMonth is set). This PR change hardcoded number of days to hide to a more generic one.
Related issue: https://github.com/Hacker0x01/react-datepicker/issues/3250
> Fix multi months on fixedHeight

- src/calendar.jsx
- src/index.jsx
- src/month.jsx
- test/datepicker_test.js
- test/month_test.js
Though `<Month>` component has `ariaLabelPrefix` prop, it is not currently possible for react-datepicker users to specify this prop. Here I added `monthAriaLabelPrefix` prop to `<DatePicker>` component and pass it to `<Month>` component to fix this issue.
> Enable specifying aria-label prefix for month

- test/date_utils_test.js
Fixes the test currently failing for all builds as mentioned in https://github.com/Hacker0x01/react-datepicker/pull/3548#issuecomment-1124820851.
Test was wrongly assuming quarters had no more than 40 days. Fixed by using `addQuarters(day, 1)` rather than `addDays(day, 40)`.
> Fix test `isQuarterDisabled should be disabled if not in included dates`

- src/day.jsx
- test/day_test.js
- Apply the `react-datepicker__day--selecting-range-end` class on the day component while user is selecting the end date for the range
- Added unit test
I observed that for datepicker having the `selectsRange` prop, when the user is selecting a range only the `react-datepicker__day--selecting-range-start` is set on the day component starting the range. While the user is moving the mouse on other day components, the class `react-datepicker__day--selecting-range-end` would not be applied on the hovered day to indicate that he is selecting that day as the end date.
I would need this class to be applied to perform custom styling for achieving this kind of styling:
This would help me to not continue the blue line after the end date.
> Fix class not applied on day component for datepicker with `selectsRange` prop

- src/index.jsx
- test/datepicker_test.js
Fix for [ISSUE-3593](https://github.com/Hacker0x01/react-datepicker/issues/3593)
When prop `showTimeSelectOnly` is set and `dateFormat` does have only time format (i.e.: _h:mm aa_), there is a problem with changing time input value. It is not preserving `selected` date.
This PR fixes this.
Example: 
```
const tomorrow = new Date();
tomorrow.setDate(today.getDate() + 1);
const [startDate, setStartDate] = useState(tomorrow);
return <DatePicker
selected={startDate}
onChange={(date) => setStartDate(date)}
showTimeSelect
showTimeSelectOnly
dateFormat="h:mm aa"
timeFormat="h:mm aa"
/>
```
> Fix same date time only prop

- package.json
- yarn.lock
- [the `react-onclickoutside` in v. 6.12.1 specifies React 18 in`peerDependencies` 
](https://github.com/Pomax/react-onclickoutside/blob/master/package.json#L82)
- as a result annoying incompatibility warning flies away ;-)
> Bump `react-onclickoutside` to 6.12.1

- src/date_utils.js
- test/calendar_test.js
`props.formatWeekDay` of `DatePicker` will be passed to `getFormattedWeekdayInLocale` via argument `formatFunc` as a callback.
The naming of the prop suggests that it is designed to provide flexibility for users to format the weekday. So I think the expected behavior is taking the source date and locale as input and returning the formatted value (i.e. As the replacement of the built-in `formatDate`). But now it  takes the formatted string as input.
```js
import DatePicker from 'react-datepicker';
import { format } from 'date-fns';
const myCustomFormatString = 'EEEEE'
const myCustomPrefix = '#'
function formatWeekDay(date, dateFnsLocale) {
return myCustomPrefix + format(date, myCustomFormatString, { locale: dateFnsLocale })
}
function App () {
// ...
return (
<DatePicker …
```
> fix: formatFunc should take source params

- src/month.jsx
- test/month_test.js
Add two more cases to onMonthKeyDown function to handle navigating using up and down arrow keys.
> Navigate in month-year picker using up and down arrow keys

- src/calendar.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.js
Fixed following issue of children content alignment:
https://github.com/Hacker0x01/react-datepicker/issues/3654
Before fix:
After fix:
> fixed children alignment issue

- src/calendar.jsx
- test/datepicker_test.js
Fixes #3723 
The `preSelection` value was not getting set to today's date on clicking Today button link.
Because of this, `isKeyboardSelected` was returning true and adding the `react-datepicker__day--keyboard-selected` class to the already selected date. This resulted in the Today button not jumping to today's date
Before the fix:
[Before the fix.webm](https://user-images.githubusercontent.com/35288242/187060267-5a6286d5-a342-438b-b471-83017986c6a3.webm)
After the fix:
[After the fix.webm](https://user-images.githubusercontent.com/35288242/187060269-57aa4986-cec8-48c0-a05c-712c3b6fd359.webm)
> Fixes #3723: Calendar does not jump back to today's date when using inline and Today button

- src/stylesheets/datepicker.scss
The keyboard selected styling was creating a ton of confusion as it always looked like the wrong date was selected when you changed months:
https://github.com/Hacker0x01/react-datepicker/issues/2930#issuecomment-1261099842
I just made that particular styling a little bit different so that it's clear that this selection status is not the same as the regular selection status. [modified colors](https://i.imgur.com/59nntuM.jpg)
> modified &--keyboard-selected to be lighter in color than regular selected

- package.json
React 18 projects that use this package will get these warnings:
```
warning "react-datepicker > react-onclickoutside@6.12.1" has incorrect peer dependency "react@^15.5.x || ^16.x || ^17.x".
warning "react-datepicker > react-onclickoutside@6.12.1" has incorrect peer dependency "react-dom@^15.5.x || ^16.x || ^17.x".
warning "react-datepicker > react-popper@2.2.5" has incorrect peer dependency "react@^16.8.0 || ^17".
```
This PR updates the minor versions of `react-onclickoutside` and `react-popper` to stop these warnings. Both of these packages include React 18 in these versions.
Bumped react-popper 1 minor version. 
v2.5.5 > v2.3.0
> Support for React 18
Bumped react-onclickoutside 1 patch version:
v6.12.1 > v6.12.2
Couldn't find patch notes but …
> Update deps react-onclickoutside & react-popper

- src/index.jsx
- test/datepicker_test.js
I'm using this date picker with the withportal prop, I noticed there's no tab loop enabled on this case, This PR uses the `TabLoop` component to wrap the portal contents.
Also, I added a onKeyDown handler to allow closing the datePicker using the `Escape` key, previously it was ignored especially when focus was on the header.
> fix: fix accessibility issues adding tab loop to datepicker with portal

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/excludeDatesMonthPicker.js
- docs-site/src/examples/includeDatesMonthPicker.js
- src/month.jsx
This fix will allow disabled months in the Month picker, to be styled as disabled, based on IncludeDates and excludeDates
> Monthpicker month disabled class

- src/time.jsx
this PR fixes the crash that may occur on timezone change, when condition  'if (isBefore(time, activeTime) || isEqual(time, activeTime))' is false and  'this.centerLi' is undefined.
> Offset top crash fix 2

- CONTRIBUTING.md
When I was setting up node 11.10.1 did not work, I think that changing to 16.0.0 would cover required packages
> fix contributing docs minimum node version

- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/year.jsx
- test/date_utils_test.js
- test/datepicker_test.js
- test/month_test.js
- test/year_picker_test.js
Nice to meet you. We have fixed some of the issues mentioned in the issue.(#2912 #3804 )
- YearMonthPicker and yearPicker can now select the same month/year as the specified minDate and maxDate.
- Some Unit test case added
> Fix month and year picker disabled

- src/month.jsx
- test/month_test.js
Description bug:
This PR fixes the issue when using month picker with disabledKeyboardNavigation enabled still showing the keyboard navigation classes on the respective months resulting in weird styling.
Fixes this issue #3876
> fix(months): disabledKeyboardNavigation not hiding classname in month picker

- src/date_utils.js
- src/index.jsx
- test/date_utils_test.js
- test/datepicker_test.js
**See the expanded commit messages for details.**
After this fix, the parsing behavior of `react-datepicker`…
a) is more consistent between locales/browsers/OS platforms
b) has fewer bugs
c) may feel slightly more "strict" in certain situations.
Item "c" results from parseDate no longer falling back (with string values for `props.dateFormat`) on free-form `new Date(value)` parsing of input values when `date-fns` has already declared the value as "invalid".
However, there's **still** a lot of flexibility in the parsing, as `date-fns/parse` provides very sensible flexibility based on localized RegExp configs, and also since `props.dateFormat` can be an Array of valid formattings.
It thus seems fairly sensible (and more deterministic) to fully place the responsibility of parsing on …
> fix: Inconsistent/broken behavior in `parseDate` 

- src/year_dropdown_options.jsx
Description bug:
The scroll position of the year dropdown is not scrolled towards the currently selected year. The scroll position will always stay in the center.
Issues:
#3747 
#3646
> Fix(year dropdown options): Year dropdown scroll defaults to center of list

- src/date_utils.js
- src/month.jsx
- test/month_test.js
> Enable keyboard navigation of quarters (fixes #3464)

- src/index.jsx
App would crash when an invalid time was provided to the Select Time Only input field
I fixed it by preventing a null date from being provided to the set function in handleChange
https://github.com/Hacker0x01/react-datepicker/issues/3759
> added change to fix Select Time Only "Invalid Date" bug

- src/date_utils.js
- src/index.jsx
- test/date_utils_test.js
- test/datepicker_test.js
Reverts Hacker0x01/react-datepicker#3903
Fixes https://github.com/Hacker0x01/react-datepicker/issues/3921, https://github.com/Hacker0x01/react-datepicker/issues/3952
> Revert "fix: Inconsistent/broken behavior in `parseDate` "

- src/index.jsx
This fix is related to https://github.com/Hacker0x01/react-datepicker/issues/3952
Specifically when, we try and Input a custom time into a blank input field, the component crashes.
It appears to be because the `set` method is being called on a null object ( i.e the.props.selected )
> Added check for date-fns set

- src/day.jsx
When using the keyboard navigation to select a day that also exists as hidden duplicate on the next month while displaying multiple months, this hidden day will be focused instead of the visible day in the current month.
This pull request prevents that behavior.
> prevent focusing of hidden duplicate days

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
This fixes small calendars on sites where something like `html { font-size: 62.5%; }` is set (see #624)
> Replace all `rem` units with `em` units

- docs-site/src/examples/excludeDateIntervals.js
- src/month.jsx
- test/datepicker_test.js
- test/month_test.js
- test/test_utils.js
- test/time_input_test.js
- test/timepicker_test.js
- test/year_dropdown_options_test.js
Fix the tab loop when the calendar is open for the monthYear Calendar
and some chores:
- factorize test utils
- remove logs in tests
Associated issue: https://github.com/Hacker0x01/react-datepicker/issues/3930
> [FIX][A11Y] Inescapable tabbing on month

- docs-site/src/examples/dateRangeWithShowDisabledNavigation.js
**Purpose**: The [Date Range with disabled navigation shown](https://reactdatepicker.com/#example-date-range-with-disabled-navigation-shown) is supposed to be date range but it misses some props and acts as default date picker.
> fix: fix selects range acts as default picker

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/rangeYearPicker.js
- docs-site/src/examples/rangeYearPickerSelectsRange.js
- docs/index.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/stylesheets/datepicker.scss
- src/year.jsx
- test/date_utils_test.js
- test/datepicker_test.js
- test/month_test.js
- test/year_picker_test.js
- Add missing range modifiers (`--selecting-range-start`, `--selecting-range-end`) for month calendar
- Add range modifiers for year calendar
- Which made it possible to expose `onYearMouseEnter` `onYearMouseLeave` as props
https://github.com/opendatasoft/react-datepicker/assets/117300300/00587d71-6e4b-4d82-86f5-803904eef809
(Internally reviewed: https://github.com/opendatasoft/react-datepicker/pull/4)
related issues:
- https://github.com/Hacker0x01/react-datepicker/issues/4048
> [FEAT][Year calendar] Add range modifiers for year calendar

- src/calendar.jsx
- test/datepicker_test.js
Currently, externaly provided onMonthChange handlers are not called when the current month is changed via the keyboard navigation.
This change detects if the preSelection coming from the keyboard navigation will move the date of the calendar over a month border and calls onMonthChange handlers if necessary.
> ensure provided onMonthChange handlers are called when month change is caused by keyboard navigation

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/renderCustomMonth.js
- docs-site/src/examples/renderCustomQuarter.js
- docs-site/src/examples/renderCustomYear.js
- docs/index.md
- src/calendar.jsx
- src/date_utils.js
- src/index.jsx
- src/month.jsx
- src/year.jsx
- test/month_test.js
- test/year_picker_test.js
I work for an organization that requires this UI for day, month and year elements in selected / selecting range.
| Day | Month | Year |
|---|---|---|
|![Screenshot 2023-06-22 at 15 35 47](https://github.com/Hacker0x01/react-datepicker/assets/117300300/217f4cb8-a558-4f6c-8afc-864200c7607c)|![Screenshot 2023-06-22 at 15 42 29](https://github.com/Hacker0x01/react-datepicker/assets/117300300/1523a95b-d0b7-4419-aecc-1269b0e192b0)|![Screenshot 2023-06-23 at 11 19 34](https://github.com/Hacker0x01/react-datepicker/assets/117300300/f9b6ca9a-b564-48d8-a0cd-824229197748)|
To do this UI, it required to use custom content renders:
- One div `.react-datepicker__{precision}` for the background.
- Another div `.react-datepicker__{precision}-content` to wrap the text in some kind of chip.
This PR aims to …
> [FEAT] Custom content renders for month, quarter and year

- .github/workflows/build-docs-site.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
Giving some love to existing github actions and paving the path to upgrading the CI to Node 18 (and 20) later down the line.
In a nutshell:
- Upgrades actions to the latest major versions where it is safe to do so
- Remove Node 14 from the CI matrix as it is unsupported
- https://endoflife.date/nodejs
> github actions: update to latest versions where applicable

- src/index.jsx
- test/datepicker_test.js
Fixes [Prop className did not match](https://github.com/Hacker0x01/react-datepicker/issues/4125#issue-1795689523)
> Prop className did not match

- src/index.jsx
- test/datepicker_test.js
> fix: always show date select

- .github/workflows/build-docs-site.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- docs-site/package.json
- docs-site/yarn.lock
> Use NodeJS 18 in CI

- src/time.jsx
- test/time_format_test.js
* Explicitly declare the Time picker as a listbox
* Add support for keyboard Arrow events to navigate the Time picker (per listbox [keyboard interaction requirements](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role#keyboard_interactions))
* When Time picker focused, initially focus the currently selected time, or whatever time was initially scrolled into view, rather than always focusing the last time (fixes #3785)
> Improve time picker accessibility

- src/index.jsx
This PR changes focus behaviour to fix portal usage.
Using portals, tab moves focus out of datepicker but leaves portal open.
A check was removed that only closed the portal on Shift + Tab, and replaced with just Tab
Without portal, user can still enter the picker with arrow keys.
Tabbing through a form with a datepicker should not land the user into a tab loop/trap.
closes #3522
> Improve focus with portals

- src/date_utils.js
- src/index.jsx
- src/time.jsx
- test/date_utils_test.test.js
- test/time_format_test.test.js
- test/timepicker_test.test.js
This is a fix for  #4243.
I would gladly add tests but time zones are involved which makes things complicated. In Node.js timezone could be changed only with environment variable which requires significant changes in test running process if we want to test several of them.
Signature of `timeClassName` changed as currH and currM don't make sense anymore. This is a potentially breaking change and also add inconvenience for the user willing to highlight selected time.
Time range is also prone to DST bugs (if someone accidentally would set a date on the DST boundary) and the interface looks somewhat strange to me. I think it should either accept an array of ranges or start and end times in `HH:mm` format.
> fix: timepicker on 23 and 25-hour days

- src/calendar.jsx
- test/calendar_test.test.js
> fix: showPreviousMonths calendar jump

- test/datepicker_test.test.js
Closes https://github.com/Hacker0x01/react-datepicker/issues/4283
- Added logic to the it("should change dates of range change startDate when endDate set before startDate") test case in datepicker_test.test.js to ensure proper date selection.
- Fixed the issue where the test was failing under specific conditions, particularly when the current date was at the beginning of a month.
> Fix: Ensure Proper Date Selection in DatePicker Test Case

- src/inputTime.jsx
- test/time_input_test.test.js
Closes #4268
This PR addresses an issue where the component was resetting the selected date of the component to the current date when changing the time. The fix ensures that the selected date remains unchanged when modifying the time, enhancing the user experience.
- Implemented logic to preserve the selected date when updating the time.
- Refactored the onTimeChange function to check if the prop date is null before using the current date
> Fix #4268: Retain the selected date when changing the time

- src/index.jsx
- test/datepicker_test.test.js
- test/timepicker_test.test.js
When using the `Escape` or `Enter` keys as well as after selection with pointer, focus did not return to input.
Accessibility [guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/) suggest that in these instances focus should return to the input.
- Adds a `sendFocusBackToInput` method for handling returning focus. There were already two separate (nearly identical) implementations to handle this within `handleSelect` and `onPopperKeydown`. The `sendFocusBackToInput` is simply an abstraction to facilitate reuse in those instances as well as several others.
- Adds tests around possible consumer implementations.
This work makes considerations not only for default implementations but as well as:
- `isClearable` - Clicking clear now returns focus to …
> fix(3635): a11y - Sets focus to input on select

- src/time.jsx
- test/time_format_test.test.js
Closes https://github.com/Hacker0x01/react-datepicker/issues/4290 and https://github.com/Hacker0x01/react-datepicker/issues/4289
Summary
This PR addresses an issue where the Time component scroll position was not accurate to the selected time, especially when the last option in the Time list got selected.  The fix ensures that the time component scrolls to the correct selected time item.  This PR will also fix the issue #4289 where the selected time is not getting auto scrolled when we use portalId
Changes Made
- Added the scroll logic inside the `requestAnimationFrame` method to schedule the scroll position update, ensuring that it occurs after the next repaint, when the DOM should be updated.
- Ensures the availability of the list ref before using it inside `requestAnimationFrame` …
> Fix #4290 and #4289: Time component scroll issue

- package.json
- src/calendar_icon.jsx
- src/stylesheets/datepicker.scss
- test/datepicker_test.test.js
The calendar icon in the React Date Picker was not displaying as expected due to a conflict arising from a global `* {box-sizing: border-box;}` style, as discussed in issue #4291. Specifically, the icon container's `padding` interfered with its available space for content, causing the icon to not render visibly.
Two main solutions were pondered:
1. **Remove Padding:** Adjust the position using `left` and `right` properties.
2. **Change Box-Sizing:** Explicitly set `box-sizing: content-box;` for the icon.
The second solution was opted for in this PR due to its straightforwardness and minimal impact on existing style setups. By assigning `box-sizing: content-box;` to the icon, it assures the padding does not encroach on the icon’s space, thereby permitting it to be displayed even when a …
> Fix: Display Issue of Calendar Icon in React Date Picker (#4291)

- test/exclude_times_test.test.js
Closes #4317
This PR addresses the issues in the test file `exclude_times_test.js` and also migrated the test cases to use `@testing-library/react` instead of `enzyme` as requested by @martijnrusschen
- Fix the `setTime` call
- Open the `<DatePicker />` component to test it, by passing the `open` prop
- Use `.toHaveLength(4)` instead of using `.not.toBeNull`
- Migrated the file to use `@testing-library/react`
> Fix #4317: Fix Enzyme Test file in exclude_times_test.js and migrate it to use @testing-library/react

- src/time.jsx
- test/exclude_times_test.test.js
- test/filter_times_test.test.js
- test/include_times_test.test.js
Closes #4259
This PR addresses an issue where the Time component is missing the attribute `aria-disabled` on it's disabled items.
- Updated the Time component to add the `aria-disabled` attribute over it's disabled items
- Made the logic to find the disable time unit sharable in a reusable helper function
- Updated the corresponding test cases to also check for the existence of the `aria-disabled` attribute along with the class `.react-datepicker__time-list-item--disabled`
- Migrated the test cases to use `RTL` from `enzyme` as suggested by @martijnrusschen in the issue #4300 for React 18 upgrade
> Fix #4259: Add the aria-disabled on the Time component's disabled time units 

- src/calendar_icon.jsx
[fix issue](https://github.com/Hacker0x01/react-datepicker/issues/4316)
> fix default props

- test/exclude_times_test.test.js
- test/filter_times_test.test.js
- test/include_times_test.test.js
Closes: #4334
I have made changes to improve the maintainability of certain test cases mentioned in the issue and removed magic numbers and refactored it a bit.  This enhancement aims to make the core more readable and maintainable.
Improving test cases maintainability and removing magic numbers helps in the following ways:
- Enhances code readability
- Eases future maintenance and debugging
- Promotes best coding practices
- `test/filter_times_test.test.js`
- `test/filter_times_test.test.js`
- `test/exclude_times_test.test.js`
1. Replaced the magic values with meaningful constants for clarity.
2. Replaced few other magic values with the actual computation logic for clarity.
3. Splitted test cases for separate one test case from other.
> Fix #4334: Improved Test Cases Readability and Maintainability

- src/index.jsx
- test/datepicker_test.test.js
Closes #4170
This PR addresses an issue where the DatePicker was not clearing the previously selected time when the user deletes the value in the date input via keyboard.  This issue was only coming when the `showTimeSelectOnly` is enabled.
- I updated the new date value only if the value exist, else set the null value, instead of restoring back to the previously selected value
- I added test cases to validate the above case both with and without `showTimeSelectOnly` using React Test Library
> Fix #4170: Clear the previously selected date on empty input with showTimeSelectOnly

- src/calendar.jsx
- src/date_utils.js
- src/month.jsx
- src/year_dropdown.jsx
- src/year_dropdown_options.jsx
1. all `var` declarations changed to `const`  or `let` to be clear
2. change `@param {date}` description to `@param {Date}`
> refactor: change 'var' to 'let' and 'const'

- src/calendar.jsx
Currently the calendar is being rendered wrapped in a div that the sole intent, as i understand, is to wrap a ref arround it.
Considering this and that there are no props to style that div, it should have the display contents property to not affect styling. In some very specific cases it can create issues, for example in the print below, there is a little gap under the calendar*
*Maybe if i used height 100% in the calendar style it would fix it, however it could introduce other issues in the way i want the style to behave.
With a flex parent:
> containerRef div shouldnt affect styling

- README.md
I edited 'Local Development' of README.md related to issue #4362
> Update 'Local Development' instruction of README.md

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/toggleCalendarOnIconClick.js
- src/calendar_icon.jsx
- src/index.jsx
- test/calendar_icon.test.js
- test/datepicker_test.test.js
Closes #4091 
This PR introduces a feature to the `<DatePicker />` component, allowing the open status of the calendar to be toggled upon clicking the calendar icon.  The behavior is controlled by a new prop `toggleCalendarOnIconClick`, which can be set to enable or disable this functionality.  By default, this functionality is disabled.
1. Added the `toggleCalendarOnIconClick` prop to control the calendar toggle behavior.
2. Added the `onClick` event handler for <CalendarIcon /> based on the existence of the `toggleCalendarOnIconClick` prop
3. Added the `onClick` event even on the custom icon component without overriding the user set `onClick` listener of it based on the existence of `toggleCalendarOnIconClick` 
4. Added the test cases
5. Modified the documentation to include information …
> Feature #4091 - Make the Calendar Icon clickable

- README.md
Update the `README.md` file with the corresponding key press handlers update.
[Related PR](https://github.com/Hacker0x01/react-datepicker/pull/4430#pullrequestreview-1801337326)
> Document #4076: 📝 Update the behavior of Home Key and End Key in the README file

- README.md
- src/index.jsx
- test/datepicker_test.test.js
Closes #4456
This PR addresses the navigation behavior in the calendar component to enhance accessibility based on W3C WAI-ARIA principles.  Previously, the shift+pageUp and shift+pageDown key handers navigated one month before and after the selected date (which is the handler for the pageUp and pageDown), which could be confusing for users.  The update modifies the behavior to move to the previous and the next year, providing a more intuitive and accessible experience.
[Reference Link](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/#:~:text=Shift%20%2B%20Page%20Up,of%20the%20month.)
- Updated shift+pageUp and shift+pageDown key handlers in the calendar component.
- Navigation now focuses on the previous and next year, improving usability.
- Added the …
> Fix #4456: Add shift+pageUp key and shift+pageDown key navigation in Calendar component

- src/date_utils.js
`awareOfUnicodeTokens` has been removed in https://github.com/date-fns/date-fns/pull/1069
> Fix options passed to date-fns/format

- src/date_utils.js
To provide symmetry with date formatting, also use the special unicode tokens flags on date parsing.
See #4469
> Fix options passed to date-fns/parse

- src/with_floating.jsx
As of react 18.3, a warning will be displayed when using defaultProps inside a function component. Therefore, I have removed the defaultProps used in the function component.
Fix #4477
> Fix - Removed defaultProps from Function Components for React 18.3.

- src/index.jsx
- test/datepicker_test.test.js
This merge request includes two enhancements in syntax:
1. onMonthChange and autoFocus have been used in the correct camelCase format throughout the project, except in the test file for react-datepicker. All other test titles follow this convention.
2. isDayInRange has a similar issue in the comment within the index.js file.
> fix:enhance-code-syntax

- scripts/generateMarkdown.js
- src/month_year_dropdown.jsx
- test/month_test.test.js
- test/year_picker_test.test.js
This merge request includes two commits:
**First Commit: Enhance Code Readability**
1. Change timepoint to timePoint to follow the camelCase convention.
2. Change maxdate to maxDate to follow the camelCase convention.
**Second Commit: Enhance Code Syntax**
- Correct the spelling of generateDescription which was written incorrectly as generateDesciption.
> enhance code readability and syntax

- src/date_utils.js
- src/month.jsx
- src/year.jsx
- test/month_test.test.js
- test/year_picker_test.test.js
Closes #4482
This PR addresses the date selection behavior in the calendar component to enhance accessibility based on W3C WAI-ARIA principles.  Previously, the `Enter` key alone is used to select a Month picker and a Year Picker.   But As per the W3C WAI-ARIA principle, both the `Enter` & `Space` keys should be able to select a date.  Currently, only the date selector is selecting a date on both the `Enter` and the `Space` key.  Hence I updated the Year Picker and the Month Picker to work like the date picker to select a date both by `Space` and `Enter` keys.
[Reference Link](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/#:~:text=Select%20the%20date%2C%20close%20the%20dialog%2C%20and%20move%20focus%20to%20the%20%22Choose%20Date%22%20button.)
- Updated …
> Fix #4482: Update Month Picker and Year Picker to select dates also on press of "SPACE" key

- src/calendar.jsx
- src/month.jsx
- src/year.jsx
- test/month_test.test.js
- test/year_picker_test.test.js
Closes #4483
**Description**
This PR addresses the missing event handling to handle the key-press event for the month picker and the year picker.  For the Year Picker component, I added `onKeyDown` and mapped it to the corresponding prop.  However, the MonthPicker (`month.jsx`) is already receiving `onKeyDown` event, but that was mapped to the handler `handleOnDayKeyDown` which is the handler specifically we're using on `day.jsx`.  In `month.jsx` we're not directly using it, but passing that to the `Week` component.  Hence for the month.jsx alone, I didn't change any of its current behavior, and I added a new prop named `handleOnMonthKeyDown` which is linked to the `onKeyDown` event handler we pass from the DatePicker component.  So users can still use `onKeyDown` itself for any …
> Fix #4483: Enable onKeyDown handler for the month picker view and the year picker view

- src/calendar_container.jsx
- test/calendar_test.test.js
Closes #4518
This PR addresses the accessibility-related issues in the calendar component by adding props like role and aria-modal to it.
[Reference Link](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/#:~:text=Usage-,dialog,Indicates%20the%20dialog%20is%20modal.,-aria%2Dlabel%3D%22string)
- Updated CalendarContainer component with role="dialog" and aria-modal="true" props.
- Added the corresponding test cases.
> Fix #4518: 🔨 Add accessibility props like role and aria-modal to the Calendar popup

- src/index.jsx
- test/min_time_test.test.js
1. Datepicker with `showTimeSelect` and `minTIme`.
2. The datepicker should be empty.
3. Select any day you want .
Actual Result (AR):
Despite disabling the start time, the Datepicker defaults to selecting the beginning of the day.
Expected Result (ER):
The Datepicker should select the minimum allowable time upon choosing a day.
> Fix: default time selection

- src/index.jsx
- test/calendar_icon.test.js
- test/inject_times_test.test.js
- test/year_dropdown_test.test.js
- test/year_picker_test.test.js
When we heard that the new tests were going to use RTL instead of enzyme, we decided that we needed to rewrite the existing tests with RTL.
Since I do not have the time to change everything at once, I created this PR to try to change things little by little.
(Sorry if there is an existing issue, PR.)
> fix: enzyme to RTL (some files)

- src/month.jsx
- test/month_test.test.js
Closes #4521
**Description**
This PR enhances the month.jsx component to display the selected month and year in the format `Month December, 2024` instead of the previous format `month 2024-12`.  This change improves the clarity and readability of the selected date for screen reader users.
**Changes Made:**
- Adjested the `aria-label` for accessibility to reflect the new date format
- Change the default ariaLabelPrefix from `month` to `Month`
- Remove the unnecessary spaces after the `ariaLabelPrefix` while using it in `aria-label`
**Testing:**
- Updated the existing test cases to check for the new `aria-label` format
- Added two new test cases to test how the component is handling the custom `ariaLabelPrefix` and null `ariaLabelPrefix` values
> Fix #4521: ♻️ Update ariaLabel format in month.jsx to display the selected month and year in "Month MMMM, yyyy"

- src/calendar_container.jsx
- test/calendar_test.test.js
> Add aria-label to calendar container for accessibility

- test/month_dropdown_test.test.js
- test/month_year_dropdown_test.test.js
- test/year_dropdown_options_test.test.js
Some of the tests have been modified to migrate from enzime to the react testing library.
Details:.
Fixed tests to use rtl's render instead of enzime's mount where handleClickOutside is used.
Sorry if a similar modified PR has already been created.
> fix: enzyme to react testing library (3 test files)

- .github/workflows/test.yml
- package.json
Since the prettier execution affects the Codecov Report, we thought it should be enforced by CI.
-- Background --
I did not run prettier on #4553.
When I ran prettier on another PR, a line break occurred and Codecov Report's CI was NG, so I needed to add a test.
https://github.com/Hacker0x01/react-datepicker/pull/4574/commits/dec832a628176f5f513113f8fb6082ed10f650de
This case was not a problem because it was code I created myself, but I don't think well if it was code created by someone else.
> feat: run prettier check in ci

- docs-site/package.json
- docs-site/src/components/Example/index.js
- docs-site/yarn.lock
**Linked issue**: #4503 (PR)
https://github.com/Hacker0x01/react-datepicker/pull/4503#issuecomment-1988309210
**Problem**
when update react-live 4.1.6, faild `yarn --cwd docs-site`
**Changes**
- update react-live
- move dev packages to devDependencies
- Fix `prism-react-renderer` (Included in the react-live dependencies) usage
> fix #4503 : update react-live in docs-site

- src/index.jsx
- test/datepicker_test.test.js
**Linked issue**: close #4594
**Problem**
See issue #4594
**Changes**
Added null check because passing null as the first argument of isBefore causes an error.
> fix: #4594 fix setSelected

- src/index.jsx
- src/month.jsx
- src/week.jsx
- test/week_test.test.js
**Linked issue**:  close #4581,#4560
**Problem**
See issue #4581 and #4560
**Changes**
As per comment #4581, I have made the following changes to the showWeekPicker case.
- Remove processing to correct date and preSelection to the first day of the week.
- Changed the passing of date and preSelection from Month component to Week component so that they are corrected to the first day of the week before passing them to the Month component.
For #4560, a null selected was being passed to getStartOfWeek. This time, the processing timing of getStartOfWeek has been moved to Month, so that null is no longer included.
> fix: #4581 and #4560 selected and preSelection  with showWeekPicker

- src/calendar.jsx
- src/month.jsx
- test/datepicker_test.test.js
**Linked issue**:  close #4401
**Problem**
See issue #4401
**Changes**
- In the loop process that creates the Month component, modified to add the year instead of the month if it is a MonthYearPicker or QuarterYearPicker.
- Modified to take year into account in determining `XX--keyboard-selected` class.
> fix: #4401 monthsShown with MonthYearPicker or QuarterYearPicker

- src/stylesheets/datepicker.scss
- src/stylesheets/mixins.scss
- src/stylesheets/variables.scss
**Linked issue**: #4561
**Problem**
See issue #4561
**Changes**
Removed triangle-arrow mixin and moved style.
The fill and color were left as they are now, as it is correct that the fill and color are different for up and down.
(The colors of the contact datepicker body location are not aligned with the up and down locations.)
The inline color code issue is not addressed in this PR.
> fix: #4561 remove triangle-arrow-up/down mixin

- src/week_number.jsx
- test/week_number_test.test.js
**Linked issue**: close #4489
**Problem**
See issue #4489
**Changes**
Disable weekNumber highlighting when no click handler is assigned.
> fix: #4489 Disable weekNumber highlighting when no click handler is assigned.

- src/index.jsx
- test/min_time_test.test.js
**Linked issue**: close #4588 
**Problem**
See issue #4588 
**Changes**
Set the selected time to `minTime` only if no input to be kept is present.
> fix: #4588 Allow time to be set via typing when minTime is set

- src/week.jsx
- test/week_test.test.js
**Linked issue**: close #4455
**Problem**
See issue #4455
**Changes**
- Pass calendarStartDay props from week to day.
> fix: #4455 Pass calendarStartDay props from week to day.

- src/month.jsx
- test/month_test.test.js
**Linked issue**: close #4360
**Problem**
See issue #4360
**Changes**
Fix click/mouseEnter Event Handler iin months/quarters to determine if it is disabled or not.
> fix: #4360 Cancel Event when clicked/MouseEnter on disabled months/quarters

- src/calendar.jsx
- src/calendar_container.jsx
- test/calendar_test.test.js
Closes #4623
This PR updates the Calendar component to display dynamic aria-label based on the selection purpose (date/date and time/time only).  After this change the `aria-label` will be
- "Choose Date and Time" if either we pass `showTimeInput` or `showTimeSelect`.
- "Choose Time" if we pass `showTimeSelectOnly`.
- "Choose Date" in all the other cases.
- Updated aria-label to reflect selection options like `showTimeInput` or `showTimeSelect` or `showTimeSelectOnly`.
- Added test cases for validation.
> Fix #4623: Add dynamic Calendar Aria Labels for selection clarity

- rollup.config.mjs
**Linked issue**:  close #3840
**Problem**
See issue #3840
**Changes**
- Add banner as copyright to build results
- Add inline sourcemap to output files other than .min.js
- Change compression target to min.js only
In the issue, it was mentioned that it would be useful to have uncompressed code, but for debug purposes, we thought it would be better to add a source map as well, so we set it up.
In the case of cjs,ems, basically, compression is done in the production build of the module bundler on the user's side, so we do not think that compression on the library side is mandatory. (I assume the source map will also be removed at this time.)
（I am a little confused as to whether to compress just min.js or everything.）
I would be glad to hear your comments on the above two points.
> fix: #3840 Rollup config

- package.json
- rollup.config.mjs
- src/calendar.jsx
- src/day.jsx
- src/index.jsx
- src/month.jsx
- src/month_year_dropdown_options.jsx
- src/popper_component.jsx
- src/week.jsx
- src/week_number.jsx
- src/year.jsx
- src/year_dropdown_options.jsx
- test/test_wrapper.jsx
- yarn.lock
**Linked issue**: close #3798
**Problem**
See issue #3798
**Changes**
Replaced classnames with clsx
> feat: #3798 Replaced classnames with clsx

- src/calendar.jsx
- src/date_utils.js
- test/calendar_test.test.js
- test/date_utils_test.test.js
**Linked issue**: #4644
**Problem**
As mentioned in the linked issue, the QuarterYearPicker has some issue with the visibility of the next and the previous arrow buttons based on the minDate and the maxDate.  That's because we are not handling the Quarter year picker separately, but handling it with the month picker logic
**Changes**
- Handled the quarter-year picker separately
- Added helpers in the `date_utils.js` to achieve the result
- Verified the change by test coverage
> Fix #4644: Handle the visibility of the previous and the next year navigation when showQuarterYearPicker is enabled 

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/rangeSwapRange.js
- src/index.jsx
- test/datepicker_test.test.js
---
name: `swapRange` prop
about: Gives more flexibility on input flow
---
**Problem**
When a user works with extensive date ranges, it could be tedious to scroll back and forth if the user makes a mistake. 
**Changes**
The change adds an optional property `swapRange` to `DatePicker` component that allows the user to swap dates if we want the end user to pick dates in any order. This is a real request from the end users, and it will be handy if you work with big date ranges.
> (feature) swapRange optional prop

- src/index.jsx
- test/datepicker_test.test.js
---
name: Fix input behavior
about: input doesn't close popper if swapRange prop passed 
---
**Problem**
After [the 6.7.0 release](https://github.com/Hacker0x01/react-datepicker/releases/tag/v6.7.0), I found that the new `swapRange` feature doesn't allow to close datepicker popper automatically when the range selected in reverse order
**Changes**
Add swapRange into the related check + a new test case
The first video is before the fix
https://github.com/Hacker0x01/react-datepicker/assets/29524085/49ac07c7-106d-458c-8e79-91e4111f341a
The second one is after the fix
https://github.com/Hacker0x01/react-datepicker/assets/29524085/a0561d94-f654-480e-9c16-862b5e8a96f4
> fix: popper dosen't close if swapRange prop was passed

- src/index.jsx
- test/datepicker_test.test.js
**Linked issue**: #4400
**Problem**
Focus calender month when the user presses down or up arrow keys in input field. This makes Datepicker accessible when only using keyboard.
> fix: #4400 Keyboard accessibility MonthYearPicker

- src/date_utils.js
- test/date_utils_test.test.js
- test/include_times_test.test.js
**Problem**
missed out support for seconds in functions in `date_utils.js`
**Changes**
added second support
> Add support for seconds in date_utils

- src/calendar.jsx
- test/calendar_test.test.js
**Linked issue**: #3185
**Problem**
When using a screenreader it reads the days in the header as "Mo", "Tu"... etc. instead of the more understandable full name  See the linked issue for a more detailed description
**Changes**
This PR adds aria-labels to the header dates so that the screenreader now reads days with full name e.g. "Monday" instead of "Mo"
> fix: Add aria-label to read the day of the week instead of the shorthand 

- src/month.jsx
- test/month_test.test.js
Added using locale for aria labels in Month component
Couldn't find any issues on this...
**Problem**
When showing MonthYearPicker the locale is not used when formatting date. -> Screenreaders will always read english months...
**Changes**
I have added using locale when formatting both the month listbox and options.
> Use locale for month aria labels

- src/month.jsx
- test/month_test.test.js
This PR addresses an issue where the Month component is missing the attribute aria-disabled on its disabled items.
- Updated the Month component to add the aria-disabled attribute over its disabled items
- Made the logic to find the disabled month unit shareable in a reusable helper function
- Updated the corresponding test cases to also check for the existence of the aria-disabled attribute along with the classname
> feature: add aria-disabled to Month component

- src/year.jsx
- test/year_picker_test.test.js
**Linked issue**: #4446 
**Problem**
The Year Picker doesn't support the up and down key navigation like the month picker and the date picker.
**Changes**
This PR adds support for updating the selected year in the year picker using the up and down arrow keys.  It also blocks the default page movement on the press of arrow keys.
> Fix #4446: ✨ Added support for up and down arrow key movement in the year picker

- src/with_floating.tsx
---
name: Migrate with_floating.jsx
---
**Changes**
`with_floating.jsx` was migrated to ts + added JSDocs
> [typescript-migration] with_floating.jsx

- src/calendar.jsx
- src/stylesheets/datepicker.scss
- test/calendar_test.test.js
**Linked issue**: #4703
This PR updates the date picker header from a <div> to a semantic <h2> element for improved accessibility.
> ♻️ Refactor date picker header to use semantic <h2> element

- package.json
- src/year_dropdown.tsx
- src/year_dropdown_options.tsx
- test/month_year_dropdown_test.test.js
- test/year_dropdown_options_test.test.js
- test/year_dropdown_test.test.js
- yarn.lock
**Changes** `year_dropdown.jsx and year_dropdown_options.jsx` was migrated to ts and test
> feat: convert year_dropdown.jsx and year_dropdown_options.jsx into ts

- src/time.tsx
- test/show_time_test.test.js
**Changes** `time.jsx` was migrated to ts
> [typescript-migration] time.jsx

- package.json
- src/portal.tsx
---
name: Migrate portal.jsx
---
**Changes**
`portal.jsx` was migrated to ts + added JSDocs
> [typescript-migration] portal.js

- src/month.jsx
- test/month_test.test.js
---
about: Fixes the date picker throwing an invalid time error when selecting excluded month with the keyboard
title: fix: invalid time error when selecting excluded month with keyboard
labels: ""
assignees: ""
---
**Linked issue**: #4731 
**Problem**
When an excluded month is selected with the keyboard, the month appears to not be keyboard selected, and when the arrow keys are used again, the Invalid time value error is thrown
**Changes**
Added a `isMonthDisabled` check to the `onMonthKeyDown` function
> fix: invalid time error when selecting excluded month with keyboard

- .editorconfig
- .prettierignore
- .prettierrc.js
**Problem**
When creating a new file in VSCode, indentation and other settings are not set correctly and must be changed manually.
**Changes**
add .editorconfig file
> feat: add .editorconfig and .prettierrc.js

- src/date_utils.ts
- src/year.tsx
- test/year_picker_test.test.js
---
name: Migrate year.jsx
---
**Changes**
`year.jsx` was migrated to ts + added JSDocs
> [typescript-migration] year.jsx

- src/popper_component.tsx
- src/with_floating.tsx
**Changes** `popper_component.jsx` was migrated to ts
> [typescript-migration] popper_component.jsx

- src/calendar_container.tsx
- src/calendar_icon.tsx
- src/date_utils.ts
- src/day.tsx
- src/input_time.tsx
- src/month.tsx
- src/month_dropdown.tsx
- src/month_dropdown_options.tsx
- src/month_year_dropdown.tsx
- src/month_year_dropdown_options.tsx
- src/tab_loop.tsx
- src/time.tsx
- src/week.tsx
- src/week_number.tsx
- src/with_floating.tsx
- src/year.tsx
- src/year_dropdown.tsx
- src/year_dropdown_options.tsx
- test/datepicker_test.test.js
**Changes** fix types & imports
> [typescript-migration] fix types & imports

- src/index.tsx
- test/time_input_test.test.js
Closes #4514
As mentioned in the linked issue, the input field is loosing it's focus whenever we try to edit the value using keyboard.  As a result of it, it doesn't create a better User experience.  After this change, user can able to change the value of the time input without loosing it's focus inbetween.
**Changes**
- Restrict the auto-focus reset to the input box when the time input is enabled (as we're also not closing the calendar popup when the time input is enabled)
- Added a test case to validate the change
> Fix #4514: 🐛 Retain the Time Input focus on change of the time input value

- .github/workflows/test.yml
It seems the previous config was still using a tokenless config
> Update codecov config

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/excludeDatesMonthPicker.js
- docs-site/src/examples/excludeDatesRangeMonthPicker.js
- docs-site/src/examples/excludeMonths.js
- docs-site/src/examples/excludeWeeks.js
- src/date_utils.ts
- src/day.tsx
- src/index.tsx
- src/month.tsx
- src/time.tsx
- src/week_number.tsx
- src/year.tsx
- test/date_utils_test.test.ts
- test/datepicker_test.test.js
- test/month_test.test.js
---
name: Allow for skipping of excluded dates/weeks/months
title: Allow for skipping of excluded dates/weeks/months
labels: ""
assignees: ""
---
**Linked issue**: #4731 
**Problem**
Currently, the date picker only stops when the user is about to navigate to an excluded month, which, if let's say there are multiple disabled dates side by side spanning the whole row, the user is unable to navigate to the months after it. This only happens on the month picker.
**Changes**
I have made recursive functions in the keydown functionality of the month and day calendar to get a new day/month if the date is disabled/excluded. Even though this is only a month picker thing, I have changed the behavior of the day calendar as well to make it …
> Allow for the keyboard preselection to skip excluded dates/weeks/months

- test/day_test.test.tsx
- test/year_dropdown_options_test.test.tsx
- test/year_picker_test.test.tsx
**Changes** `year_picker_test.test.js` and some tests ware migrated to ts
> [typescript-migration] test/year_picker_test.test.js and some tests

- test/multiple_selected_dates.test.tsx
---
name: Migrate filter_times_test.test.js
---
**Changes**
Converted multiple_selected_dates.test.js to a tsx file.
> feat: convert multiple_selected_dates.test.js into tsx

- src/index.tsx
- test/datepicker_test.test.js
Closes #4011
As mentioned in the Linked issue when the minDate or the maxDate is set to null, the mouse navigations are allowed for all the days and months, but however the keyboard navigation is disabled.  That means when the minDate/maxDate is null, eventhough users are allowed to select any dates, but just they can't do it via keyboard arrows.  I resolved this issue in this PR and added a corresponding test cases to verify the changes
> Fix #4011: 🐛 Handle Arrow Navigation on calendar days even when the minDate/maxDate is nul

- src/index.tsx
- test/datepicker_test.test.tsx
Closes #4844 
Retain the open state of the calendar popup on document visibility change.
**Problem**
As mentioned in the issue description, the calendar gets auto-reopen whenever we switch the browser tab and switch back to the original tab in any of the below 2 cases
1. Switching the browser tab after we enter the date manually into the calendar input by dismissing the calendar popup
2. Switching the tab immediately after selecting any date via calendar popup (In this case, we could have blurred focus from the input, but when I inspect the code, we intentionally refocus the calendar input, upon selection of any date from the calendar popup as a fix for the issue https://github.com/Hacker0x01/react-datepicker/issues/628)
In any of the above cases the input is focused while switching the …
> Fix #4844: 🔨 Retain the open state of the calendar popup on document visibility change

- jest.config.js
- src/calendar.tsx
- src/index.tsx
- src/test/min_time_test.test.tsx
- src/test/month_test.test.tsx
- src/test/multi_month_test.test.tsx
- src/test/multiple_selected_dates.test.tsx
- src/test/week_number_test.test.tsx
- src/test/year_dropdown_options_test.test.tsx
- src/week_number.tsx
**Changes**
- migrate src/test/month_test.test.tsx
- migrate src/test/week_number_test.test.tsx
- migrate src/test/multi_month_test.test.tsx
- migrate src/test/min_time_test.test.tsx
- migrate src/test/multiple_selected_dates.test.tsx
> [typescript-migration] some tests

- .github/workflows/test.yml
- jest.config.js
- src/test/datepicker_test.test.tsx
- src/test/helper_components/custom_input.tsx
**Changes**
- migrate src/test/datepicker_test.test.tsx
- migrate src/test/helper_components/custom_input.tsx
- migrate rollup.config.mjs
> [typescript-migration] some tests and configs

- src/test/week_picker_test.test.tsx
- src/week.tsx
Closes #4902
**Problem**
As described in the linked issue, the problem occurs when we disable the first week of the day and using `excludeDateIntervals`  whereas the other days of the week are enabled.  In this case the select of the week number is not working.
**Changes**
- Select the first-enabled day of the week whenever the first day of the week is disabled (Currently it's returning the first day of the week when the first day is not disabled, else it's not selecting anything)
- Added corresponding test cases to validate the changes
> Fix #4902: 🐛 Fix the click of week numbers when the first day of the week is not enabled

- src/calendar_container.tsx
The `CalendarContainerProps` interface is now exported, allowing other modules to import and use it.
**Problem**
CalendarContainerProps wasn't exported 
**Changes**
Export the interface
> feat: export CalendarContainerProps interface

- src/index.tsx
**Linked issue**: closes #4906
**Problem**
See issue.
**Changes**
export ReactDatePickerCustomHeaderProps IF
> export ReactDatePickerCustomHeaderProps IF

- src/test/datepicker_test.test.tsx
Closes #4934
Pass the default date to the getOnInputKeyDownStuff to avoid switching to the next month view when the current date is in the last row of the current month
- Apply this fix as the render fails to rerender days to the next month view
> Fix #4934: ✅ Fix the broken test case in datepicker_test.test.js

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/selectsMultipleMonths.js
- src/month.tsx
- src/test/month_test.test.tsx
Currently there's a `selectsMultiple` flag that enables the pick of multiple dates, yet the selection styles for when applied together with `showMonthYearPicker` was never implemented.
**Problem**
Current behaviour upon selecting multiple months:
**Changes**
This is a simple change that adds the missing selected class (`react-datepicker__month-text--selected`) to the scenario of having `selectsMultiple` & `showMonthYearPicker` flags enabled
> Add multiple months visual selection

- src/day.tsx
- src/month.tsx
- src/test/day_test.test.tsx
- src/test/month_test.test.tsx
- src/test/year_picker_test.test.tsx
- src/year.tsx
Closes #4933
**Problem**
As I mentioned in the issue, when the auto-selected date (which is the currently selected) is part of a disabled date in the next or previous month/year view, while switching still it'll set highlight the disabled dates.  In this PR I removed the auto-setting of the class '--keyboard-selected' while switching to the previous/next view if the corresponding date is disabled.
> Fix #4933: 🐛Remove the auto set of the '--keyboard-selected' class from the disabled dates while switching to the next or the previous view

- src/month.tsx
- src/test/month_test.test.tsx
**Linked issue**: #4219
**Problem**
Quarter Picker with "excludeDates" is not getting inactive styles.
Please check the issue for details.
**Changes**
- Include "excludeDates" as a condition for calling the Quarter Picker's disable judge function.
> fix style for quarter

- src/index.tsx
**Linked issue**:  closes #4922 
**Problem**
See issue
**Changes**
- Add Partial to`Pick<AdditionalProps, "excludeScrollbar">`
- change to optional onSelect and onChangeProps. (Consider defaultProps)
> fix DatePickerProps

- package.json
- rollup.config.mjs
- src/@types/react-onclickoutside/index.d.ts
- src/calendar.tsx
- src/click_outside_wrapper.tsx
- src/index.tsx
- src/month_dropdown.tsx
- src/month_dropdown_options.tsx
- src/month_year_dropdown.tsx
- src/month_year_dropdown_options.tsx
- src/test/calendar_test.test.tsx
- src/test/datepicker_test.test.tsx
- src/test/min_time_test.test.tsx
- src/test/month_dropdown_test.test.tsx
- src/test/month_year_dropdown_test.test.tsx
- src/test/multiple_selected_dates.test.tsx
- src/test/year_dropdown_options_test.test.tsx
- src/year_dropdown.tsx
- src/year_dropdown_options.tsx
- yarn.lock
Closes https://github.com/Hacker0x01/react-datepicker/issues/4801
Closes https://github.com/Hacker0x01/react-datepicker/issues/4605
**Problem**
React 19 removed `findDOMNode` and `react-onclickoutside` is not supported
**Changes**
- Remove `react-onclickoutside` and replace with custom wrapper
- Update the `onClickOutside` to use `MouseEvent` instead of `React.MouseEvent` since it's a document event listener
> Remove usages of react-onclickoutside to support React 19

- src/stylesheets/datepicker.scss
- src/test/week_number_test.test.tsx
Closes #4986
As described in the issue, the hover style for the disabled items was set to transparent, hence if the programatically pre-selected is a part of the disabled dates, it'll apply the highlight background to the selected date.  On hovering on this date, we shouldn't change it's background color.  
As a fix, instead of changing the background of the disabled date items to transparent, I apply the hover styles to be applied only for the enabled date items.  As a result, even though the disabled date was pre-selected, on hovering over it won't update it's style.
> Fix #4986: 🐛🎨 Update the hover style to be applied only to the non-disabled calendar items

- docs-site/src/examples/customInput.js
**Problem**
The classname "react-datepicker-ignore-onclickoutside" was not applied to custom inputs in the Docs Website example.
This lead to opening and closing of the popper when clicking on the input, because it was not considered clicking outside.
https://github.com/user-attachments/assets/c9499d93-1723-4756-acde-bb982901406a
**Changes**
Passed className as props to the example and moved the "example-custom-input"
> The classname "react-datepicker-ignore-onclickoutside" is not applied to custom input

- src/month.tsx
- src/test/month_test.test.tsx
- src/test/test_utils.ts
- src/test/year_picker_test.test.tsx
- src/year.tsx
Closes #5010
As I elaborate the issue in the above mentioned link, the disabled dates are able to be focused when the initial focus happens on the calendar component.  As a fix, I blocked the focus to be applied for the disabled dates.
> Fix #5010: 🐛 Restrict the focus to the disabled months/quarter/year using the initial Tab key navigation

- src/test/calendar_icon.test.tsx
- src/test/calendar_test.test.tsx
- src/test/datepicker_test.test.tsx
- src/test/day_test.test.tsx
- src/test/min_time_test.test.tsx
- src/test/month_dropdown_test.test.tsx
- src/test/month_year_dropdown_test.test.tsx
- src/test/show_time_test.test.tsx
- src/test/test_utils.test.ts
- src/test/test_utils.ts
- src/test/time_input_test.test.tsx
- src/test/timepicker_test.test.tsx
- src/test/week_number_test.test.tsx
- src/test/week_picker_test.test.tsx
- src/test/week_test.test.tsx
- src/test/year_dropdown_options_test.test.tsx
- src/test/year_dropdown_test.test.tsx
- src/test/year_picker_test.test.tsx
Closes #5038
**Issue**
Currently in our project test cases, in many places we followed a format like `container.querySelector('...')  ?? new HTMLElement()` or `container.querySelectorAll('...') ?? []`. In most of these cases, we wrote a test case on top of it. But this way of using a fallback null elements won't help us to test the actual cases, as missing elements are replaced by new ones, allowing tests to pass whey they shouldn't.
**Contribution**
To address this, a new utility function has been developed that throws an error if the querySelector result is null or if querySelectorAll returns an empty array. This ensures that missing elements are caught early and improves the reliability of our test cases.
This is just a test case update and it won't affect the source code, but just the …
> Fix #5038: Enhance test case querySelector/querySelectorAll reliability with ensuring element existance

- src/calendar.tsx
- src/index.tsx
- src/year_dropdown.tsx
**Linked issue**: #5044 
**Problem**
As described in the linked issue, there are many instances where default prop event handlers are referenced for not reason (they are empty functions, and the code is not actually calling them in most places).
**Changes**
Refactor the groups of 3 lines into 1, and remove default props that are empty functions.
For example
```
onChange
? onChange(changedDate, event)
: DatePicker.defaultProps.onChange;
```
is changed to
`onChange?.(changedDate, event)`
> Simplify event handlers

- src/calendar.tsx
**Problem**
Upgraded to `react-datepicker@7` and `date-fns@3`, and now getting the following error when checking types with `typescript@5.5`:
```
node_modules/react-datepicker/dist/calendar.d.ts:10:26 - error TS2307: Cannot find module 'date-fns/types' or its corresponding type declarations.
10 import type { Day } from "date-fns/types";
~~~~~~~~~~~~~~~~
Found 1 error in node_modules/react-datepicker/dist/calendar.d.ts:10
```
**Changes**
Simply corrected the import from `date-fns/types` to `date-fns`.
> Fix "Cannot find module 'date-fns/types' ..."

- src/date_utils.ts
- src/index.tsx
- src/test/datepicker_test.test.tsx
**Linked issue**: #3596 #3906 #4002 
**Problem**
When selectsRange is false, users can input "03/04/2024" in text box and automatically have 4 March 2024 selected in the calendar.
However when selectsRange is true, if users input "03/04/2024 - 05/06/2024" in the text box, nothing happens.
**Changes**
With this PR, when selectsRange is true and the user inputs "03/04/2024 - 05/06/2024", the start date will be set to 4 March 2024 and the end date will be set to 6 May 2024.
> Parse date range

- src/test/timepicker_test.test.tsx
- src/test/year_picker_test.test.tsx
This PR is regarding enhancement suggested on my previous PR - https://github.com/Hacker0x01/react-datepicker/pull/5039
**Comment Link:** https://github.com/Hacker0x01/react-datepicker/pull/5039#discussion_r1722178122
As suggested in the linked comment I tried removing the usage of `safeQuerySelector` or `safeQuerySelectorAll` usage with `SafeElementWrapper` method chaining to avoid the unnecessary temporary variables.  This is just a test-case refactor.
> ♻️🧪 Refactor test cases with SafeElementWrapper querySelector chain to eliminate the unnecessary temporary variable

- src/test/exclude_dates.test.tsx
**Problem**
The test suite failed on September 1st, and every 1st of the month in the past, because this test assumes `today` and `subDays(today, 1)` are in the same month.
**Changes**
We check if today is the first of the month, and if so, we use `addDays(today, 1)` instead of `subDays(today, 1)`.
> test: fix a test that would always fail if run on first day of month

- docs-site/src/examples/customTimeInput.js
- src/input_time.tsx
- src/test/time_input_test.test.tsx
Closes #4949
As I mentioned in the ticket, the issue is with the Time Input of the React Date Picker (both with the default Time Input - `showTimeInput` with `shouldCloseOnSelect` turned off and the Custom Time Input - `customInput`)
The issue is whenever we open the datepicker for the first time, and try to change the time before changing the date, now the time input won't get the focus and we need to do double click to get the focus.  Then onwards, single click itself will bring the focus.  The issue occurs only for the first update.
We are getting the issue because whenever we open the date picker, we auto-focus the selected date or the current date by setting it's tabIndex to 0 and all the other element's tab-index to -1.  As a result we need to get the focus on other elements we need …
> 🐛 Resolve the double-click focus issue of Time input and custom time component example

- docs-site/src/components/Examples/index.js
- docs-site/src/examples/hideTimeCaption.js
- src/test/timepicker_test.test.tsx
- src/time.tsx
**Linked issue**: #5099
**Problem**
It was previously not possible to completely hide the caption of the time picker.
**Changes**
Added `showTimeCaption` option to `DatePicker` to hide the time caption.
Added `Hide Time Caption` example to the docs.
Added tests to check custom caption text and hidden state.
> Added option to hide time caption

- src/time.tsx
Our main website is getting an error: https://reactdatepicker.com/
`TypeError: k.format is not a function`
Possible fix for https://github.com/Hacker0x01/react-datepicker/issues/5108
> try fixing JS error on website

- package.json
- yarn.lock
Reverts Hacker0x01/react-datepicker#5102
This upgrade breaks our demo website. Reverting until we've found a fix.
Ref https://github.com/Hacker0x01/react-datepicker/issues/5108
> Revert "chore(deps): bump date-fns from 3.6.0 to 4.1.0"

- src/test/datepicker_test.test.tsx
Closes #5137
I accidentally found this issue with the existing test cases. The issue we're having is with the test module `datepicker_test.test.js`. There currently 2 test blocks are having an issue as I mentioned in the attached screenshot
- `DatePicker › should be possible to preSelect minDate (no maxDate set)`
- `DatePicker › should be possible to preSelect minDate (maxDate set)`
**The Problem**
I shared one of the failed test cases in the above screenshot. The issue there is we're initially getting a selected day using `const selectedDayNode = getSelectedDayNode(data.container)` and then doing right and left arrow click over it. This test case will work in most of the days except the last day of a month. Because, let's consider 30th Sept, 2024 as the selected date. When the user press …
> Fix #5137: 🧪✅ Fix the accidental change of the complete month issue with the test cases by selecting to a earlier date in a month

- src/stylesheets/datepicker.scss
- src/stylesheets/variables.scss
**Linked issue**: [#5109](https://github.com/Hacker0x01/react-datepicker/issues/5109)
**Problem**
[Sass is preparing to remove darken and lighten](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/) in a future 2.0.0 release and had started throwing deprecation error.
**Changes**
Change lighten/darken to color.adjust
> Change lighten/darken to color.adjust

- src/portal.tsx
**Linked issue**: #5129
**Problem**
There is a warning printed by rollup during build of types, which is preventing the generation of the portal.d.ts file.
Specifically, the TS error is the following:
TS2742: The inferred type of render cannot be named without a reference to react-dom/ node_modules/@types/ react. This is likely not portable. A type annotation is necessary.
This warning is actually an error which is preventing the generation of the declaration file for the portal.tsx.
**Changes**
Added the return type to the render method of the portal class
> Fix types build by specifying return type on portal render method

- src/calendar.tsx
- src/test/calendar_test.test.tsx
Closes #5147
**Problem**
As I described in the linked ticket, the issue is if we select a date and disable the same date in the next or previous months, then when we navigate to the corresponding month and try using arrow keys (Tab) to navigate to the date, it won't work as there is no pre-selected date available in the month due to the fact that the corresponding date we selected previously is disabled in the corresponding month.
**Changes**
- Whenever month gets switched, instead of auto-preselecting the already selected day from the selected date.  I first checked if the same day in the month is disabled, if not pre-select the same day, else pre-select the first enabled date in the month.  If all the days are disabled in the rendered month, didn't pre-select any days.
> Fix #5147: 🐛 Fix navigation issue with disabled dates in date picker

- src/index.tsx
- src/test/datepicker_test.test.tsx
Close #5084 
As @avazhenin mentioned in the attached ticket, we're getting an issue while we try to switch to the next input control via Tab Key on Firefox browser.  
Even though @avazhenin shared his code sample along with a video explaining the issue,  I'll share a simple way to recreate the issue.  Goto `https://reactdatepicker.com/` via **FireFox** and click on any date input, now try to press tab when the calendar is getting rendered.  We expect it to auto-close the calendar and switch to the next code sample.  But instead of that it'll refocus the same date input again.  To make it work, we have to press ESC first (which will close the opened calendar popup) and then press Tab, it'll work.  In this case alone it'll work, because as the datepicker is already closed, it won't disturb …
> 🐛 Fix #5084: Fixfox Tab switch issue

- src/test/calendar_test.test.tsx
- src/test/test_utils.ts
Closes #5206
As I described in the issue, currently the test cases are failing as in one of the test cases we try to select the month which is same as the current month.  I fixed it by generating a random month other than the current month.  This is just a test case update.
> 🧪 test-fix: Update the test case to use the random month except the current month

- src/calendar.tsx
- src/test/calendar_test.test.tsx
**Linked issue**: #5193
**Problem**
Even though the min date is provided, when selecting the second month, "previous month" button still appears. It shouldn't happen, because the calendar from the screenshots starts at November. 
**Changes**
Changed the calculation logic that determines whether previous month button should appear or not (borrowed some code from `renderMonths`, big thanks to @pmacmillan). Added a test case, in which a calendar is rendered with min date, after that the date from the second month is selected and it is expected for "previous month" button not to appear.
*Calendar starts at November 7*
**Before**
**After**
> fix: "previous month" button appears when selecting a date

- src/calendar.tsx
**Problem**
The current CalendarProps type definition is incorrect, leading to type errors when using the component. This issue arises because `React.PropsWithChildren` is a generic type that requires a type argument to specify the component's props.
**Changes**
This PR fixes the type definition by correctly combining `React.PropsWithChildren` with `CalendarProps`. This ensures proper type checking and prevents potential runtime errors.
> fix(types): `PropsWithChildren` type argument issue

- src/stylesheets/datepicker.scss
- src/test/week_number_test.test.tsx
- src/week_number.tsx
Closes #5200 
As mentioned in the ticket, when `showWeekNumbers` is enabled in a datepicker, the keyboard select on the first day of the week alone highlights the week number.  When we select any other week days it's not highlighting.  This issue is not occuring in the mouse hover of any week days.  
As I shared in the above screenshot, we passed the start of the week to each corresponding week number and in the `<WeekNumber />` component we apply a class `react-datepicker__week-number--keyboard-selected` when the date prop (which is start of the week) is selected. 
**Changes**
- As a fix, I removed the setting of `react-datepicker__week-number--keyboard-selected` to <WeekNumber />.  The reason is because we are not applying any class to it when we hover the first day of the week using …
> Fix #5200: Fix the unnecessary highlight on the Week Number when the first day of the week is selected using Keyboard

- .stylelintrc.json
- docs-site/src/components/Examples/examples.scss
- docs-site/src/components/Examples/helpers.scss
- docs-site/src/components/Examples/hero.scss
- docs-site/src/components/Examples/style.scss
- src/stylesheets/datepicker.scss
- src/stylesheets/mixins.scss
This PR updates SCSS files to replace deprecated `@import` statements with `@use`.  The `@use` rule improves modularity, enhances namspace management, and aligns with modern SCSS standards.
**Changes**
- Replaced `@import` statements with `@use`
- Updated variable and mixin references as needed to accommodate `@use` namespaces.
> 🚨 Fix SCSS Lint issues - Change @import to @use

- src/test/calendar_test.test.tsx
Closes #5252
As mentioned in the linked ticket, we have an issue with one of the testcases as we didn't configure the `selectedDate`.  As a fix I just added the `selectedDate` same as `minDate`
> 🧪 Fix the test case failing issue by setting the selected date to be same as the configured least possible month date

- package.json
- yarn.lock
---
name: Remove unused prop-types dependency
about: Found an unused dependency and removed it
title: ""
labels: ""
assignees: ""
---
Was looking through dependencies and noticed that prop-types was in the dependency list.  This library is not actually imported in the core library and is instead only used inside the demo app.  The Readme also mentions that prop-types is not bundled and should be installed if needed.
**Problem**
**Changes**
Ran `yarn remove prop-types`
> Remove unused prop-types dependency

- src/year.tsx
The class `react-datepicker__year--selecting-range` was being added on the entire year wrapper which does not make sense. This causes several UI issues when applying custom CSS using this selector
> fix: remove wrong class assignment on year wrapper

- package.json
- yarn.lock
Added react ^19 and ^19.0.0-rc as peer dependency. Some projects like Next.js already utilize react 19 release candidate, so that installing react-datepicker can only be done with `--legacy-peer-deps`. I have tested the `react-datepicker` with Next.js and react 19 release candidate and it works. So I have added react ^19 and ^19.0.0-rc as peer dep
---
title: ""
labels: ""
assignees: ""
---
**Linked issue**: #(<none>) 
**Problem**
Using react-datepicker with Next.js only works with --legacy-peer-deps
**Changes**
Added react ^19 and ^19.0.0-rc as peer dep
- [X ] I have followed the [contributing guidelines](https://github.com/Hacker0x01/react-datepicker/blob/main/CONTRIBUTING.md).
- [X ] I have added sufficient test …
> Added react ^19 and ^19.0.0-rc as peer dep

- src/day.tsx
- src/index.tsx
- src/month.tsx
- src/year.tsx
---
title: "Fix types for startDate and endDate props"
labels: "Typescript"
assignees: "Sergey Kazarinov"
---
**Linked issue**: #5259  
**Problem**
Solves the type issue for startDate and endDate props when I select selectsRange
**Changes**
Extend the typing of startDate and endDate props. Added union type Date | null
> fix: types for startDate and endDate props (#5259)

- src/calendar.tsx
- src/calendar_icon.tsx
- src/index.tsx
- src/input_time.tsx
- src/month_dropdown.tsx
- src/month_dropdown_options.tsx
- src/month_year_dropdown.tsx
- src/month_year_dropdown_options.tsx
- src/popper_component.tsx
- src/time.tsx
- src/week.tsx
- src/week_number.tsx
- src/with_floating.tsx
- src/year_dropdown.tsx
- src/year_dropdown_options.tsx
**Linked issue**:  closes #5284
**Problem**
See issue
**Changes**
replace JSX.Element to React.ReactElement
> Fix #5284: replace JSX.Element to React.ReactElement

- docs/week_number.md
- src/test/week_number_test.test.tsx
- src/week.tsx
- src/week_number.tsx
Closes #5280
As mentioned in the linked ticket, we have an accessibility issue with the weekNumber of week-picker.  The week number hover stye is active for the numbers which don't have any week days enabled.  So, in this PR I removed the hover style of the week number if all the corresponding week days of the week number are disabled and also added a test cases for it.
> ♿️ Fix #5280: Disable the WeekNumber if all the corresponding week days are disabled

- docs-site/package.json
- docs-site/yarn.lock
- examples/hello-world/package.json
- examples/hello-world/yarn.lock
- package.json
- src/calendar.tsx
- src/calendar_icon.tsx
- src/input_time.tsx
- src/tab_loop.tsx
- src/with_floating.tsx
- src/year_dropdown_options.tsx
- yarn.lock
Closes https://github.com/Hacker0x01/react-datepicker/issues/5299
> Upgrade to React 19

- src/index.tsx
- src/test/datepicker_test.test.tsx
---
**Problem**
In MR https://github.com/Hacker0x01/react-datepicker/pull/4878, the behavior of the calendar popup when switching browser tabs has been fixed. However, the `props.onFocus` callback in the `handleFocus` method was blocked if a browser tab was switched before.
**Changes**
I've moved the `isOpenAllowed` flag condition checking so that the `props.onFocus` callback will execute as before, regardless of the calendar popup opening.
> Fix condition preventing props.onFocus execution

- package.json
- rollup.config.mjs
- src/date_utils.ts
- src/test/calendar_test.test.tsx
- src/test/date_utils_test.test.ts
- src/test/month_test.test.tsx
- yarn.lock
**Linked issue**: #5177, #5128
**Problem**
This PR update `date-fns` to the latest version, v4.1.0. Dependabot update breaks the docs website (which is a separate topic in itself, the build system over there is extremely outdated - happy to help with that), my changes fix these issues so the website is still functional.
**Changes**
- bumped version in package.json
- removed the logic in Rollup that marks date-fns exports as external
- adjusted imports to use `date-fns` directly, also in tests for consistency
This might seem like a bad decision, after all previous contributors were using direct date-fns exports to reduce the bundle size! This isn't actually correct after v4.1.0. Since v4, `date-fns` is marked as `type: "module"`, so really any somewhat up-to-date bundle will handle tree …
> chore(deps): upgrade date-fns to v4.1.0

- package.json
- rollup.config.mjs
- src/date_utils.ts
- src/test/calendar_test.test.tsx
- src/test/date_utils_test.test.ts
- src/test/month_test.test.tsx
- yarn.lock
**Linked issue**: #5177, #5128, #5326
**Problem**
This PR is a second attempt after #5326 to update `date-fns` to the latest version, v4.1.0. Dependabot update breaks the docs website (which is a separate topic in itself, the build system over there is extremely outdated - happy to help with that), my changes fix these issues so the website is still functional (this time for real, I triple checked).
**Changes**
- bumped `date-fns` version in package.json
- adjusted exports in package.json, namely removed `browser` field entirely and added more modern `exports` field
- removed the logic in Rollup that marks date-fns exports as external
- fixed UMD build so it actually works (it was probably broken for a very long time, though)
- adjusted imports to use `date-fns` directly, also in tests …
> chore(deps): upgrade date-fns to v4.1.0 (attempt no. 2)

- package.json
- Updated as @rollup/plugin-typescript v12.1.2 has some issue in parsing the nested directories of declarationDir ("./dist")
Related issues
https://github.com/rollup/plugins/issues/1813
https://github.com/rollup/plugins/issues/1772
> 🔧 Update the ES output path to be direct child of dist/ dir

- src/calendar_container.tsx
**Linked issue**: #5364 
**Problem**
The `CalendarContainerProps` interface currently extends `React.PropsWithChildren<HTMLDivElement>`, which causes TypeScript errors when using CalendarContainer in custom implementations. This incorrect type inheritance prevents proper type checking for HTML attributes.
**Changes**
- Updated `CalendarContainerProps` to extend `React.PropsWithChildren<React.HTMLAttributes<HTMLDivElement>>` instead of `HTMLDivElement`
- This change allows the component to properly type-check all valid HTML attributes that can be passed to a div element
- Fixes TypeScript errors that occur when using CalendarContainer in custom container implementations
N/A
This is a type-only change that fixes TypeScript errors while maintaining the same runtime behavior. The change makes …
> fix: correct type inheritance in CalendarContainer props

- src/index.tsx
- src/test/datepicker_test.test.tsx
Closes #5274
**Problem**
As mentioned in the linked ticket, the input value doesn't get reset when the open state is set to false (User just need the date input part, not the datepicker part).  In this case eventhough we didn't emit `onChange` event when the user press invalid input, when we click outside the input, the input value remains invalid.  
However if the user press tab, it's getting reset to the previously received valid value and it's also handled properly when open prop is controlled by our package. 
**Changes**
We have open state and open prop.  I just set the open state to false on blur of the input, which will refresh the input value back to the valid, previously received value prop.
This change is very specific for `open={false}` case, as the other cases were already …
> Fix #5274: 🐛 Auto refresh the input value with the previously entered valid value if any invalid value is entered (when the open state is closed)

- src/index.tsx
This fixes an issue where `CalendarIconProps.icon` became a required property, causing a type error.  
- Changed `CalendarIconProps.icon` from required to optional using `Partial`.
- Updated related type definitions to ensure backward compatibility.
- Added tests to verify that the changes don't break existing functionality.  
- Ran `yarn test`, and all tests passed.  
This is my first open-source PR, so if there are any issues or improvements needed, I’m happy to make changes! 😊 
Closed #5405
> Fix: Make CalendarIconProps.icon optional to prevent type error

- package.json
When I explored the `package.json` file I found our `build` script is using `css:modules:dev` which actually compile scss to css in an expanded view, not compressed.  
I also noticed we are calling `css:modules:dev` twice.  
**Changes**
As a fix I just replaced the redundant `css:modules:dev` script run with `css:modules:prod`.  So that it'll also include the compressed css module file in the dist folder.
> 🔧 Update the production build script config to include css:modules:prod

- src/index.tsx
Closes #5366
**Problem**
As described in the linked ticket, the fix we made for the issue (related to FireFox Tab press) delays the blur and focus call to the next render cycle.  That's causing an issue when the consumer manually controls the open and the close state via onFocus event.  As a fix I just the defer the execution of the blur call after the state updates for setOpen.  
**Changes**
- Defer the blur call alone to fix the issue #5084
- Fix the bug caused in the commit d07308d3860389449e069ad766b966467d328a2c
- In the old PR itself we covered the fix made, which will also include the current fix update
> Fix #5366: 🐛 Fix the re-focus issue of the DatePicker element when the open state is controlled manually

- src/month.tsx
- src/test/month_test.test.tsx
Set CSS class for the current quarter, following the same pattern as other views
**Problem**
For calendar views such as Day, Month, and Year, the CSS class `react-datepicker__{view}-text--today` is applied. However, for the Quarter view, this class was not being set, even though the corresponding style is present.
**Changes**
- Added the `react-datepicker__quarter-text--today` class, which will be applied when the quarter in the Quarter view is the current quarter of the year.
> fix: set css class for the current quarter

- src/calendar.tsx
- src/click_outside_wrapper.tsx
- src/day.tsx
- src/week_number.tsx
**Linked issue**: fix #5428 , fix #5136
**Problem**
see #5428
**Changes**
- Calendar component to Manth component to resume containerRef propagation.
> fix: 5428 ContainerRef Propagation

- src/index.tsx
**Problem**
Stray console.log in the deferBlur => requestAnimationFrame call
**Changes**
> Remove console.log from deferBlur

- src/test/year_picker_test.test.tsx
- src/year.tsx
Closes #5322
As mentioned in the linked ticket, we failed to update the `--selected` styling when the `selectsMultiple` is enabled on the Year Picker.  I added the fix for it by checking the `selectedDates` prop when the `selectsMultiple` is enabled, if not then to check the `selected` prop.
> 🐛🎨 Apply the `--selected` class for the YearPicker when the `selectsMultiple` is enabled

- src/day.tsx
- src/test/datepicker_test.test.tsx
- src/test/day_test.test.tsx
Closes #5502
As I mentioned in the linked issue, the 'react-datepicker__day--in-selecting-range' class over the days are getting applied for all the days in the EndDate Picker even if we select the endDate.
**Changes**
- Updated the condition to apply the mentioned class on the other months only if the endDate is not specified
> Fix #5502: 🐛 Fix '--in-selecting-range' class apply condition for End Date Picker

- src/test/calendar_test.test.tsx
- src/test/datepicker_test.test.tsx
- src/test/exclude_time_period_test.test.tsx
- src/test/exclude_times_test.test.tsx
- src/test/min_time_test.test.tsx
- src/test/show_time_test.test.tsx
- src/test/test_utils.ts
- src/test/time_input_test.test.tsx
- src/test/timepicker_test.test.tsx
- src/time.tsx
Closes #5466
As mentioned in the ticket, the Time Picker height is not getting updated when we switch between months, so sometimes when we switch from 30 days month to 31 days month and vice a versa, we have some UI-issues.  I added a Resize-Observer and update the time picker height whenever calendar popup height changes and updated the test cases for it.
> 🎨🔨 Re-adjust the height of TimePicker on Calendar resize due to number of days

- src/index.tsx
---
title: "Fix readOnly prop"
labels: bug
assignees: "Sergey Kazarinov"
---
**Problem**
- When I set readOnly prop and I have a clearButton, I can click on it and the date will be deleted
- If I use inline calendare, also I can change date when I have the readOnly prop
**Changes**
- If set readOnly prop, clearButton is hidde
- If set readOnly prop, I cannot change date to inline calendar
> Fix readOnly prop for a clearButton and inline calendare

- src/test/year_picker_test.test.tsx
- src/year.tsx
Closes #5573
As mentioned in the attached ticket, we're having an issue that the year picker is highlighting all the available years when do date is entered.  In this PR I added a fix for it along with the test cases to validate the fix.
> Fix #5573 🐛 Fix the Selected Year Picker style when no date is selected

- src/date_utils.ts
- src/index.tsx
- src/test/datepicker_test.test.tsx
This PR addresses the issue with parsing date ranges when `dateFormat` contains dashes (`-`).
**Problem**
Currently, when entering a date manually via input using a `dateFormat` with dashes (such as `dd-MM-yyyy`), the `startDate` and `endDate` are not parsed correctly. The issue arises because the current parser uses `.split('-')`, which only captures parts of the first date.
**Changes**
This PR modifies the parser to use `.split(' - ')` as the default separator for date ranges. To avoid breaking changes, this adjustment is applied only to `dateFormats` that contain dashes.
> Parse date range with dashes

- package.json
This PR exposes the source SCSS files via the package's exports so projects can import them.
**Problem**
This project's SCSS has a lot of useful variables (e.g. `$datepicker__selected-color`), but no obvious way to change their default values. This way, a project can import the SCSS files with overrides for the variables, instead of setting a bunch of individual attributes. For example:
```
@use 'react-datepicker/src/stylesheets/variables.scss' with (
$datepicker__selected-color: #000000,
$datepicker__font-family: inherit,
);
@use 'react-datepicker/src/stylesheets/datepicker.scss';
```
If there is a better way of doing this, please let me know!
**Changes**
Simply add a line to `exports` in package.json with a wildcard for all SCSS files.
> Include SCSS files in exports

- src/index.tsx
- src/test/datepicker_test.test.tsx
**Linked issue**: #5520
**Problem**
As mentioned in the linked issue, the datepicker needs 2 esc key press to close.  This is not happening always.  If the control is there in any days, then one `ESC` key itself is closing the date picker.  But if it's there in the DatePicker header (For E.g., Previous or Next month navigation button), then the first `ESC` key will just move the focus back to the DatePicker Input and then second Esc key only will close the DatePicker.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to a page with react-datepicker rendered.
2. Click on the input field to open the calendar and click back and next navigate button for more than one times.
3. Press Escape.
4. Observe that the calendar remains open (It just moves the focus to the input).
5. Press Escape …
> 🐛 Add missing datepicker close call onPopperKeyDown event - to handle ESC keydown event outside the day component

- src/day.tsx
- src/test/datepicker_test.test.tsx
Close #5599
As mentioned in the linked issue, one of my previous PRs https://github.com/Hacker0x01/react-datepicker/pull/5503 is causing an issue in applying `--in-selecting-range` over the hovered days.
We by default pre-select a selected date on the other months also.  As a result the same date on the other months will be programatically pre-selected (even-though we didn't hover or select) and we use the same state to know the date till we want to highlight.  The same issue also exist for startDate picker also, when navigating to the previous months - as we pre-select the already selected dates for the other months.  So, as a fix I undo my existing fix.
> 🐛 Fix EndDatePicker selection range progress

- src/calendar.tsx
- src/test/calendar_test.test.tsx
This changes the type of `previousYearButtonLabel` and `nextYearButtonLabel` to be `React.ReactNode`. This mirrors `previousMonthButtonLabel` and `nextMonthButtonLabel`, which is already of type React.ReactNode.
**Problem**
When using month picker, the `YearButtonLabel`s allow for specifying a ReactNode (the code [here](https://github.com/Hacker0x01/react-datepicker/blob/main/src/calendar.tsx#L723-L725) implies that it is expected to not always be a string), but typescript rightfully complains because the type doesn't line up.
**Changes**
This PR changes `previousYearButtonLabel` and `nextYearButtonLabel` to be the type `React.ReactNode` instead of `string`
NA
> fix(calendar): Change type on YearButtonLabel to be the type ReactNode.

- src/test/year_picker_test.test.tsx
- src/year.tsx
**Linked issue**: #5669
**Problem**
As I mentioned in the ticket, we're not applying `--keyboard-selected` class over the active year of YearPicker, when there is no selected year set by default.
**Changes**
I just removed the guard that prevent applying  `--keyboard-selected` class when the `selected` prop is not available.
> 🐛 Enable --keyboard-selected class to the YearPicker irrespective of the availability of selected prop

- CLAUDE.md
- src/calendar.tsx
- src/index.tsx
- src/test/datepicker_test.test.tsx
**Problem**
We'd like to configure the name of the click outside ignore class.
**Changes**
Add clickOutsideIgnoreClass to the DatePicker component
> feat: expose outsideClickIgnoreClass

- docs-site/src/components/Examples/index.jsx
- docs-site/src/examples/customRangeSeparator.js
- docs/index.md
- src/date_utils.ts
- src/index.tsx
- src/test/date_utils_test.test.ts
- src/test/datepicker_test.test.tsx
Closes #4741
**Problem**
As requested in the attached ticket, added a support to customize the separator of the Range Date Picker using a new prop `rangeSeparator`.
**Changes**
- Introduced `rangeSeparator` prop to allow custom separators in date range formatting.
- Updated `safeDateRangeFormat` to utilize the custom separator.
- Added example for date range selection with a custom separator in documentation.
- Enhanced tests to verify functionality of the new `rangeSeparator` feature.
> feat: ✨ Add customizable range separator for date range selection in DatePicker

- docs-site/src/components/Examples/examples.scss
- docs-site/src/components/Examples/index.jsx
- docs-site/src/examples/customWeekClassName.js
- src/test/week_test.test.tsx
- src/week.tsx
**Linked issue**: #5744 
**Problem**
See ticket.
**Changes**
I added a `weekClassName` prop to the `Week` component. I also added tests and a custom example.
I would personally make the function signature `(date: Date) => string | undefined` to allow the consumers to return `undefined` declaring that they do not want to add an extra class for this particular week. 
To follow the convention here I decided to keep it as `(date: Date) => string` to be inline with what all the other classname functions are doing. Slightly less elegant but the callers can still opt out by returning an empty string I guess.
> Week classname support

- src/date_utils.ts
- src/index.tsx
- src/test/date_utils_test.test.ts
- src/test/datepicker_test.test.tsx
**Linked issue**: #5759
**Problem**
As mentioned in the linked ticket, we are having an issue when the user tries to clear the `startDate` value (when the `endDate` is available) using the date input, suddenly the datepicker becomes unresponsive.  User can't see any value in the date input and they won't be able to select any new value from the date picker popup also.
**Changes**
- Update Input Value get logic to return empty string only when both `startDate` & `endDate` is null.  Because the current logic is returning empty string when the `startDate` is not available regardless of checking the existence of the `endDate`
- Update Input change logic to properly handle start date change when `endDate` is available.  It'll either set the `startDate` by retaining the endDate (if its less …
> 🐛 Refactor DatePicker component to handle null startDate date range selection properly

- src/month_dropdown.tsx
- src/month_dropdown_options.tsx
- src/test/month_dropdown_test.test.tsx
- src/test/year_dropdown_options_test.test.tsx
- src/test/year_dropdown_test.test.tsx
- src/year_dropdown.tsx
- src/year_dropdown_options.tsx
**Linked issue**: #5609 
**Problem**
The year and month dropdowns are not accessible via keyboard. The dropdown toggles cannot be focused, and the dropdown options cannot be navigated using arrow keys or selected with the Enter key.
**Changes**
- Changed the dropdown read view components from div to button to allow keyboard focusing.
- Added keyboard support for dropdown option components. Arrow keys can now be used to navigate the list, and the Enter key can be used to select an option.
> Add dropdown keyboard accessibility

- src/day.tsx
- src/month.tsx
- src/test/day_test.test.tsx
**Linked issue**: #5258 
**Problem**
When I open a date range picker with swapRange, I select the first date. Then, when I hover or focus on the second date, if the second date is before the first date, all dates within this range do not have the following in range classes: react-datepicker__day--in-selecting-range, react-datepicker__day--selecting-range-start, react-datepicker__day--selecting-range-end.
https://github.com/user-attachments/assets/6a1cb8c1-bc32-43ac-8f1f-1916b7ba8c3f
**Changes**
- All days within the selected range now correctly receive the in range classes.
- The classes `react-datepicker__day--selecting-range-start` and `react-datepicker__day--selecting-range-end` are now dynamically setted based on `selectionDate` and `startDate`, but only when the `swapRange` prop is …
> fix: Improve behaviour of highlight dates with swapRange

- src/stylesheets/datepicker.scss
**Linked issue**: #5829 
**Problem**
Wrong alignment of the day names in the header.
**Changes**
Small changes in scss file. Added the same style which have other rows in grid.
Before: 
After:
> fix: Center align day names in DatePicker for improved layout

- docs-site/package.json
- docs-site/src/components/tsxTransformer.ts
- docs-site/yarn.lock
Configures esbuild-wasm’s initialize to load the WASM from a URL pinned to the installed package version, preventing mismatches between the JS wrapper and the WASM binary. Also upgrades esbuild-wasm to 0.25.10.
**Problem**
Using an unpinned `WASM` URL could fetch a different version than the installed `esbuild-wasm` JS, causing runtime errors and version conflicts.
**Linked PR:** https://github.com/Hacker0x01/react-datepicker/pull/5865
**Changes**
- Configure initialize to use: https://unpkg.com/esbuild-wasm@${version}/esbuild.wasm
- Upgrade esbuild-wasm to 0.25.10.
> 🐛 Configure esbuild-wasm initialize to use installed package version

- docs-site/src/components/Example/index.tsx
Ensures the transpilation/loading indicator displays correctly when toggling between the TypeScript and JavaScript tabs in the docs-site, preventing the brief, misleading error flash.
**Problem**
On tab switch, the loading state wasn’t activated early enough and previous error state could render momentarily, causing a transient error display.
**Changes**
- Fix the loading state
- Update the error message properly on transpilation error
**Current Issue**
https://github.com/user-attachments/assets/1b95b6e2-3b0d-483a-aa88-1aa02d200c21
**After the Fix**
https://github.com/user-attachments/assets/3b0b723d-7601-47a8-aa64-ad38e885864d
> Fix loading indicator flicker when switching TypeScript/JavaScript tabs in docs-site
